"""General expression tree utility."""

__all__ = [
    "BUILTIN_CONSTANTS",
    "BUILTIN_FUNCTIONS",
    "AlternativesPattern",
    "BinaryExpression",
    "BinaryExpressionPattern",
    "BinaryOperation",
    "BuiltinConstants",
    "BuiltinFunctions",
    "CallExpression",
    "CallExpressionPattern",
    "CapturePattern",
    "EntryLookupError",
    "EntryRegistrationError",
    "Expression",
    "FunctionArityError",
    "FunctionSort",
    "IdentifierExpression",
    "IdentifierPattern",
    "LiteralExpression",
    "LiteralPattern",
    "LiteralType",
    "MatchBindings",
    "NativeConstant",
    "NativeFunction",
    "NativeResultSortError",
    "NonFiniteCastError",
    "PartialPiecewiseError",
    "Pattern",
    "PiecewiseExpression",
    "PiecewiseExpressionPattern",
    "PredicatePattern",
    "RegisteredEntry",
    "RegisteredFunction",
    "RewriteRule",
    "RewriteRuleApplier",
    "StringLiteralPrecisionError",
    "UnaryExpression",
    "UnaryExpressionPattern",
    "UnaryOperation",
    "UnboundVariableError",
    "UndecidableError",
    "UnsupportedNumpyLoweringError",
    "WildcardPattern",
    "apply_rewrite_rule",
    "apply_rewrite_rules",
    "call",
    "check_expression_type",
    "convert_expression_to_sympy_expression",
    "convert_expression_to_z3_expression",
    "convert_sympy_expression_to_expression",
    "does_pattern_match",
    "evaluate_expression",
    "evaluate_expression_with_numpy",
    "get_core_data_type_from_literal_type",
    "get_registered_entries",
    "get_registered_entry",
    "get_result_core_data_type_for_sort",
    "inline_functions",
    "is_core_data_type_compatible_with_sort",
    "is_entry_registered",
    "is_python_value_compatible_with_sort",
    "logical_and",
    "logical_not",
    "logical_or",
    "make_binary_expression",
    "make_unary_expression",
    "match_pattern",
    "pformat_expression",
    "piecewise",
    "register_function",
    "register_native_constant",
    "register_native_function",
    "substitute_sympy_expression_variables",
    "synthesize_expression_type",
]

from .builtins import (
    BUILTIN_CONSTANTS,
    BUILTIN_FUNCTIONS,
    BuiltinConstants,
    BuiltinFunctions,
)
from .core import (
    BinaryExpression,
    BinaryOperation,
    CallExpression,
    Expression,
    IdentifierExpression,
    LiteralExpression,
    LiteralType,
    PiecewiseExpression,
    UnaryExpression,
    UnaryOperation,
    call,
    logical_and,
    logical_not,
    logical_or,
    make_binary_expression,
    make_unary_expression,
    piecewise,
)
from .errors import (
    NativeResultSortError,
    NonFiniteCastError,
    PartialPiecewiseError,
    StringLiteralPrecisionError,
    UnboundVariableError,
    UndecidableError,
    UnsupportedNumpyLoweringError,
)
from .passes.evaluate import evaluate_expression
from .passes.inline import FunctionArityError, inline_functions
from .passes.numpy import evaluate_expression_with_numpy
from .passes.sympy import (
    convert_expression_to_sympy_expression,
    convert_sympy_expression_to_expression,
    substitute_sympy_expression_variables,
)
from .passes.type_checker import (
    check_expression_type,
    get_core_data_type_from_literal_type,
    synthesize_expression_type,
)
from .passes.z3 import convert_expression_to_z3_expression
from .pattern import (
    AlternativesPattern,
    BinaryExpressionPattern,
    CallExpressionPattern,
    CapturePattern,
    IdentifierPattern,
    LiteralPattern,
    MatchBindings,
    Pattern,
    PiecewiseExpressionPattern,
    PredicatePattern,
    RewriteRule,
    RewriteRuleApplier,
    UnaryExpressionPattern,
    WildcardPattern,
    apply_rewrite_rule,
    apply_rewrite_rules,
    does_pattern_match,
    match_pattern,
)
from .pprint import pformat_expression
from .registry import (
    EntryLookupError,
    EntryRegistrationError,
    NativeConstant,
    NativeFunction,
    RegisteredEntry,
    RegisteredFunction,
    get_registered_entries,
    get_registered_entry,
    is_entry_registered,
    register_function,
    register_native_constant,
    register_native_function,
)
from .sort import (
    FunctionSort,
    get_result_core_data_type_for_sort,
    is_core_data_type_compatible_with_sort,
    is_python_value_compatible_with_sort,
)
