"""Expression IR: syntax, entry registry, sorts, and the passes over them.

The package is self-contained. It owns the expression tree, the
process-wide registry of functions and constants, the ``FunctionSort``
vocabulary, the built-in functions and constants seeded into the
registry at import, and the passes that evaluate, inline, rewrite,
pretty-print, and lower expressions to SymPy, Z3, or NumPy. None of it
depends on the IR type system; assigning IR types to expressions is the
job of the type-checking layer, which sits above this package.
"""

__all__ = [
    "BUILTIN_CONSTANTS",
    "BUILTIN_FUNCTIONS",
    "AlternativesPattern",
    "BinaryExpression",
    "BinaryExpressionPattern",
    "BinaryOperation",
    "BuiltinConstants",
    "BuiltinFunctions",
    "CallExpression",
    "CallExpressionPattern",
    "CallTargetResolver",
    "CapturePattern",
    "EntryLookupError",
    "EntryRegistrationError",
    "Expression",
    "FunctionArityError",
    "FunctionSort",
    "IdentifierExpression",
    "IdentifierPattern",
    "LiteralExpression",
    "LiteralPattern",
    "LiteralType",
    "MatchBindings",
    "NativeConstant",
    "NativeFunction",
    "NativeResultSortError",
    "Pattern",
    "PredicatePattern",
    "RegisteredEntry",
    "RegisteredFunction",
    "RewriteRule",
    "RewriteRuleApplier",
    "StringLiteralPrecisionError",
    "TernaryExpression",
    "TernaryExpressionPattern",
    "UnaryExpression",
    "UnaryExpressionPattern",
    "UnaryOperation",
    "UnboundVariableError",
    "UndecidableError",
    "UnsupportedNumpyLoweringError",
    "WildcardPattern",
    "apply_rewrite_rule",
    "apply_rewrite_rules",
    "assert_expression_implies",
    "assert_holds_for_all_free_assignments",
    "call",
    "convert_expression_to_sympy_expression",
    "convert_expression_to_z3_expression",
    "convert_sympy_expression_to_expression",
    "does_expression_imply",
    "does_pattern_match",
    "evaluate_expression",
    "evaluate_expression_with_numpy",
    "get_registered_entries",
    "get_registered_entry",
    "holds_for_all_free_assignments",
    "inline_functions",
    "is_entry_registered",
    "is_python_value_compatible_with_sort",
    "logical_and",
    "logical_not",
    "logical_or",
    "make_binary_expression",
    "make_unary_expression",
    "match_pattern",
    "pformat_expression",
    "register_function",
    "register_native_constant",
    "register_native_function",
    "simplify_expression",
    "substitute_sympy_expression_variables",
    "ternary",
]

from .builtins import (
    BUILTIN_CONSTANTS,
    BUILTIN_FUNCTIONS,
    BuiltinConstants,
    BuiltinFunctions,
)
from .core import (
    BinaryExpression,
    BinaryOperation,
    CallExpression,
    Expression,
    IdentifierExpression,
    LiteralExpression,
    LiteralType,
    TernaryExpression,
    UnaryExpression,
    UnaryOperation,
    call,
    logical_and,
    logical_not,
    logical_or,
    make_binary_expression,
    make_unary_expression,
    ternary,
)
from .errors import (
    NativeResultSortError,
    StringLiteralPrecisionError,
    UnboundVariableError,
    UndecidableError,
    UnsupportedNumpyLoweringError,
)
from .passes.evaluate import evaluate_expression
from .passes.inline import FunctionArityError, inline_functions
from .passes.numpy import evaluate_expression_with_numpy
from .passes.sympy import (
    convert_expression_to_sympy_expression,
    convert_sympy_expression_to_expression,
    simplify_expression,
    substitute_sympy_expression_variables,
)
from .passes.z3 import (
    assert_expression_implies,
    assert_holds_for_all_free_assignments,
    convert_expression_to_z3_expression,
    does_expression_imply,
    holds_for_all_free_assignments,
)
from .pattern import (
    AlternativesPattern,
    BinaryExpressionPattern,
    CallExpressionPattern,
    CapturePattern,
    IdentifierPattern,
    LiteralPattern,
    MatchBindings,
    Pattern,
    PredicatePattern,
    RewriteRule,
    RewriteRuleApplier,
    TernaryExpressionPattern,
    UnaryExpressionPattern,
    WildcardPattern,
    apply_rewrite_rule,
    apply_rewrite_rules,
    does_pattern_match,
    match_pattern,
)
from .pprint import pformat_expression
from .registry import (
    CallTargetResolver,
    EntryLookupError,
    EntryRegistrationError,
    NativeConstant,
    NativeFunction,
    RegisteredEntry,
    RegisteredFunction,
    get_registered_entries,
    get_registered_entry,
    is_entry_registered,
    register_function,
    register_native_constant,
    register_native_function,
)
from .sort import FunctionSort, is_python_value_compatible_with_sort
