[cosmic-ray]
module-path = "src/fhy_core/symbolic/constraint/core.py"
timeout = 120.0
excluded-modules = []
test-command = "pytest -x --no-header -q -o addopts='' -m 'not slow' tests"

[cosmic-ray.distributor]
name = "local"
