"""Constrained parameters.

A parameter composes a value :class:`ParamDomain` with a variable and a set of
constraints. Build the common kinds with the ``create_*`` factory functions, or
construct a :class:`Param` directly with a domain.
"""

__all__ = [
    "CategoricalDomain",
    "CategoricalValue",
    "IntegerDomain",
    "IntervalIntegerDomain",
    "OrdinalDomain",
    "OrdinalValue",
    "Param",
    "ParamAssignment",
    "ParamDomain",
    "ParamError",
    "PermutationDomain",
    "PermutationMemberValue",
    "RealDomain",
    "SerializableEqualValue",
    "SerializableOrderableValue",
    "create_categorical_param",
    "create_integer_param",
    "create_integer_param_between",
    "create_integer_param_with_lower_bound",
    "create_integer_param_with_upper_bound",
    "create_interval_integer_param",
    "create_interval_integer_param_between",
    "create_interval_integer_param_exactly",
    "create_interval_integer_param_with_lower_bound",
    "create_interval_integer_param_with_upper_bound",
    "create_interval_natural_param",
    "create_natural_param",
    "create_ordinal_param",
    "create_permutation_param",
    "create_real_param",
    "create_real_param_between",
    "create_real_param_with_lower_bound",
    "create_real_param_with_upper_bound",
    "create_single_valid_value_param",
]

from .core import (
    CategoricalValue,
    OrdinalValue,
    Param,
    ParamAssignment,
    ParamError,
    PermutationMemberValue,
    SerializableEqualValue,
    SerializableOrderableValue,
    create_categorical_param,
    create_integer_param,
    create_integer_param_between,
    create_integer_param_with_lower_bound,
    create_integer_param_with_upper_bound,
    create_interval_integer_param,
    create_interval_integer_param_between,
    create_interval_integer_param_exactly,
    create_interval_integer_param_with_lower_bound,
    create_interval_integer_param_with_upper_bound,
    create_interval_natural_param,
    create_natural_param,
    create_ordinal_param,
    create_permutation_param,
    create_real_param,
    create_real_param_between,
    create_real_param_with_lower_bound,
    create_real_param_with_upper_bound,
    create_single_valid_value_param,
)
from .domains import (
    CategoricalDomain,
    IntegerDomain,
    IntervalIntegerDomain,
    OrdinalDomain,
    ParamDomain,
    PermutationDomain,
    RealDomain,
)
