//! Equivalence test replaying the golden built-in catalogue recorded from the
//! Python oracle against `fhy_core::symbolic::expression::builtins`.
//!
//! The golden data is generated by
//! `rust/fhy-core/tests/golden/generate_builtin_cases.py` and committed at
//! `rust/fhy-core/tests/golden/builtin_cases.json`. It lists the composed
//! functions (name, parameter name hints, parameter sorts, result sort, and
//! body wire form with each identifier written as `{"parameter": index}`),
//! the native function signatures, the constants (sort and IEEE 754 bits),
//! the symbolic and functional prints of each body (identifiers by name
//! hint), and the registration order. This test encodes each Rust body,
//! rewrites its identifiers to parameter positions, and compares the wire
//! forms exactly: numbers compare by kind (an integer token never equals a
//! float token) and then by value. It compares the prints as exact text.
//! Public API only.

use fhy_core::identifier::Identifier;
use fhy_core::symbolic::expression::builtins::{
    ComposedFunction, NativeConstantSpec, NativeFunctionSignature, composed_functions,
    find_composed_function, find_native_constant, find_native_function, native_constants,
    native_functions,
};
use fhy_core::symbolic::expression::{
    FormatOptions, FunctionSort, IdentifierStyle, Notation, format_expression,
};
use serde_json::{Map, Value, json};

const GOLDEN_JSON: &str = include_str!("golden/builtin_cases.json");

/// Number of composed functions the catalogue records.
const COMPOSED_COUNT: usize = 16;

/// Number of native function signatures the catalogue records.
const NATIVE_FUNCTION_COUNT: usize = 19;

/// Number of constants the catalogue records.
const NATIVE_CONSTANT_COUNT: usize = 4;

/// Return the golden array under `key`, failing the test if it is absent.
fn read_array<'a>(document: &'a Value, key: &str) -> &'a Vec<Value> {
    document[key]
        .as_array()
        .unwrap_or_else(|| panic!("golden data has a `{key}` array"))
}

/// Return the golden string under `key` of `record`.
fn read_str<'a>(record: &'a Value, key: &str) -> &'a str {
    record[key]
        .as_str()
        .unwrap_or_else(|| panic!("golden record {record} has a string `{key}`"))
}

/// Return the sort a golden sort name denotes.
fn parse_sort(sort: &Value) -> FunctionSort {
    serde_json::from_value(sort.clone()).unwrap_or_else(|error| panic!("bad sort {sort}: {error}"))
}

/// Return the sorts a golden sort-name array denotes.
fn parse_sorts(sorts: &Value) -> Vec<FunctionSort> {
    sorts
        .as_array()
        .unwrap_or_else(|| panic!("{sorts} is a sort array"))
        .iter()
        .map(parse_sort)
        .collect()
}

/// Return whether a JSON number was written as an integer token.
fn is_integer_token(number: &serde_json::Number) -> bool {
    !number.to_string().contains(['.', 'e', 'E'])
}

/// Compare two wire values: structure and strings exactly, integer tokens by
/// their digits, float tokens by their value, and never an integer token
/// with a float token.
fn compare_wire(actual: &Value, expected: &Value, path: &str) -> Result<(), String> {
    match (actual, expected) {
        (Value::Number(actual_number), Value::Number(expected_number)) => {
            let same = match (
                is_integer_token(actual_number),
                is_integer_token(expected_number),
            ) {
                (true, true) => actual_number.to_string() == expected_number.to_string(),
                (false, false) => {
                    let parse = |number: &serde_json::Number| {
                        number.to_string().parse::<f64>().map(f64::to_bits).ok()
                    };
                    parse(actual_number) == parse(expected_number)
                }
                _ => false,
            };
            if same {
                Ok(())
            } else {
                Err(format!(
                    "{path}: {actual_number} vs expected {expected_number}"
                ))
            }
        }
        (Value::Object(actual_map), Value::Object(expected_map)) => {
            let actual_keys: Vec<&String> = actual_map.keys().collect();
            let expected_keys: Vec<&String> = expected_map.keys().collect();
            if actual_keys != expected_keys {
                return Err(format!(
                    "{path}: keys {actual_keys:?} vs expected {expected_keys:?}"
                ));
            }
            for (key, value) in actual_map {
                compare_wire(value, &expected_map[key], &format!("{path}.{key}"))?;
            }
            Ok(())
        }
        (Value::Array(actual_items), Value::Array(expected_items)) => {
            if actual_items.len() != expected_items.len() {
                return Err(format!(
                    "{path}: {} items vs expected {}",
                    actual_items.len(),
                    expected_items.len()
                ));
            }
            for (index, (item, expected_item)) in
                actual_items.iter().zip(expected_items).enumerate()
            {
                compare_wire(item, expected_item, &format!("{path}[{index}]"))?;
            }
            Ok(())
        }
        _ if actual == expected => Ok(()),
        _ => Err(format!("{path}: {actual} vs expected {expected}")),
    }
}

/// Return `wire` with every identifier replaced by `{"parameter": index}`,
/// its position in `parameters`.
fn replace_parameters(wire: &Value, parameters: &[Identifier]) -> Result<Value, String> {
    match wire {
        Value::Object(map)
            if map.len() == 2 && map.contains_key("id") && map.contains_key("name_hint") =>
        {
            let id = map["id"]
                .as_u64()
                .ok_or_else(|| format!("bad id in {wire}"))?;
            let index = parameters
                .iter()
                .position(|parameter| parameter.id() == id)
                .ok_or_else(|| format!("identifier {wire} is not a parameter"))?;
            Ok(json!({"parameter": index}))
        }
        Value::Object(map) => map
            .iter()
            .map(|(key, value)| Ok((key.clone(), replace_parameters(value, parameters)?)))
            .collect::<Result<Map<String, Value>, String>>()
            .map(Value::Object),
        Value::Array(items) => items
            .iter()
            .map(|item| replace_parameters(item, parameters))
            .collect::<Result<Vec<Value>, String>>()
            .map(Value::Array),
        other => Ok(other.clone()),
    }
}

/// Compare the listed names with the golden records' names, in order.
fn check_order(section: &str, actual: &[&str], records: &[Value]) -> Result<(), String> {
    let expected: Vec<&str> = records
        .iter()
        .map(|record| read_str(record, "name"))
        .collect();
    if actual == expected.as_slice() {
        Ok(())
    } else {
        Err(format!(
            "{section}: order {actual:?} vs expected {expected:?}"
        ))
    }
}

/// Compare one composed function with its golden record.
fn check_composed_function(record: &Value) -> Result<(), String> {
    let name = read_str(record, "name");
    let function = find_composed_function(name).ok_or("not in the catalogue")?;
    let parameter_names: Vec<&str> = function
        .parameters()
        .iter()
        .map(Identifier::name_hint)
        .collect();
    let expected_names: Vec<&str> = record["parameter_names"]
        .as_array()
        .ok_or("no parameter_names array")?
        .iter()
        .map(|value| value.as_str().unwrap_or_default())
        .collect();
    if parameter_names != expected_names {
        return Err(format!(
            "parameters {parameter_names:?} vs expected {expected_names:?}"
        ));
    }
    let expected_sorts = parse_sorts(&record["parameter_sorts"]);
    if function.parameter_sorts() != expected_sorts.as_slice() {
        return Err(format!(
            "parameter sorts {:?} vs expected {expected_sorts:?}",
            function.parameter_sorts()
        ));
    }
    let expected_result = parse_sort(&record["result_sort"]);
    if function.result_sort() != expected_result {
        return Err(format!(
            "result sort {} vs expected {expected_result}",
            function.result_sort()
        ));
    }
    let wire = serde_json::to_value(function.body())
        .map_err(|error| format!("body encode failed: {error}"))?;
    let body = replace_parameters(&wire, function.parameters())?;
    compare_wire(&body, &record["body"], "body")?;
    check_print(
        function,
        Notation::Symbolic,
        read_str(record, "symbolic_print"),
    )?;
    check_print(
        function,
        Notation::Functional,
        read_str(record, "functional_print"),
    )
}

/// Compare a composed body printed in `notation`, identifiers by name hint,
/// with its golden print.
fn check_print(
    function: &ComposedFunction,
    notation: Notation,
    expected: &str,
) -> Result<(), String> {
    let printed = format_expression(
        function.body(),
        FormatOptions::new(notation, IdentifierStyle::NameHint),
    );
    if printed == expected {
        Ok(())
    } else {
        Err(format!(
            "{notation:?} print {printed:?} vs expected {expected:?}"
        ))
    }
}

/// Compare one native function signature with its golden record.
fn check_native_function(record: &Value) -> Result<(), String> {
    let name = read_str(record, "name");
    let function = find_native_function(name).ok_or("not in the catalogue")?;
    let expected_sorts = parse_sorts(&record["parameter_sorts"]);
    if function.parameter_sorts() != expected_sorts.as_slice() {
        return Err(format!(
            "parameter sorts {:?} vs expected {expected_sorts:?}",
            function.parameter_sorts()
        ));
    }
    let expected_result = parse_sort(&record["result_sort"]);
    if function.result_sort() == expected_result {
        Ok(())
    } else {
        Err(format!(
            "result sort {} vs expected {expected_result}",
            function.result_sort()
        ))
    }
}

/// Compare one constant with its golden record, its value by its exact bits.
fn check_native_constant(record: &Value) -> Result<(), String> {
    let name = read_str(record, "name");
    let constant = find_native_constant(name).ok_or("not in the catalogue")?;
    let expected_sort = parse_sort(&record["sort"]);
    if constant.sort() != expected_sort {
        return Err(format!(
            "sort {} vs expected {expected_sort}",
            constant.sort()
        ));
    }
    let bits_text = read_str(record, "value_bits");
    let expected_bits = u64::from_str_radix(bits_text.trim_start_matches("0x"), 16)
        .map_err(|error| format!("bad value_bits {bits_text}: {error}"))?;
    let actual_bits = constant.value().to_bits();
    if actual_bits == expected_bits {
        Ok(())
    } else {
        Err(format!(
            "value bits {actual_bits:#018x} vs expected {bits_text} ({})",
            read_str(record, "value_repr")
        ))
    }
}

/// Replay every record of one section with `check`, collecting each
/// disagreement under the record's name.
fn replay_section(
    section: &str,
    records: &[Value],
    check: impl Fn(&Value) -> Result<(), String>,
    mismatches: &mut Vec<String>,
) {
    for record in records {
        if let Err(message) = check(record) {
            mismatches.push(format!("{section} {}: {message}", read_str(record, "name")));
        }
    }
}

/// Compare the catalogue's tables, in the registry's order (constants,
/// natives, composed functions), with the golden registration order.
fn check_registration_order(document: &Value) -> Result<(), String> {
    let actual: Vec<&str> = native_constants()
        .iter()
        .map(NativeConstantSpec::name)
        .chain(native_functions().iter().map(NativeFunctionSignature::name))
        .chain(composed_functions().iter().map(ComposedFunction::name))
        .collect();
    let expected: Vec<&str> = read_array(document, "registration_order")
        .iter()
        .map(|name| name.as_str().unwrap_or_default())
        .collect();
    if actual == expected {
        Ok(())
    } else {
        Err(format!(
            "registration order {actual:?} vs expected {expected:?}"
        ))
    }
}

/// Parse a golden document, check its size, replay every section, and fail
/// with the disagreements found.
fn replay_document(json: &str, corpus_path: Option<&str>) {
    let document: Value = serde_json::from_str(json).expect("golden data is valid JSON");
    let composed = read_array(&document, "composed_functions");
    let natives = read_array(&document, "native_functions");
    let constants = read_array(&document, "native_constants");
    assert_eq!(composed.len(), COMPOSED_COUNT, "golden composed functions");
    assert_eq!(
        natives.len(),
        NATIVE_FUNCTION_COUNT,
        "golden native functions"
    );
    assert_eq!(constants.len(), NATIVE_CONSTANT_COUNT, "golden constants");

    let mut mismatches = Vec::new();
    let composed_names: Vec<&str> = composed_functions()
        .iter()
        .map(ComposedFunction::name)
        .collect();
    let native_names: Vec<&str> = native_functions()
        .iter()
        .map(NativeFunctionSignature::name)
        .collect();
    let constant_names: Vec<&str> = native_constants()
        .iter()
        .map(NativeConstantSpec::name)
        .collect();
    for outcome in [
        check_order("composed functions", &composed_names, composed),
        check_order("native functions", &native_names, natives),
        check_order("native constants", &constant_names, constants),
        check_registration_order(&document),
    ] {
        if let Err(message) = outcome {
            mismatches.push(message);
        }
    }
    replay_section(
        "composed",
        composed,
        check_composed_function,
        &mut mismatches,
    );
    replay_section("native", natives, check_native_function, &mut mismatches);
    replay_section(
        "constant",
        constants,
        check_native_constant,
        &mut mismatches,
    );

    let location = corpus_path
        .map(|path| format!(" in {path}"))
        .unwrap_or_default();
    assert!(
        mismatches.is_empty(),
        "found {} mismatch(es){location}:\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
}

/// Test the committed catalogue agrees with the Python oracle's.
#[test]
fn builtins_match_the_python_oracle() {
    replay_document(GOLDEN_JSON, None);
}

/// Test a catalogue corpus, named by `FHY_BUILTIN_CORPUS`, agrees with the
/// Python oracle's.
#[test]
#[ignore = "requires a corpus generated from the Python oracle"]
fn builtins_match_the_python_oracle_on_an_expanded_corpus() {
    let path = std::env::var("FHY_BUILTIN_CORPUS").expect("FHY_BUILTIN_CORPUS names a corpus file");
    let json = std::fs::read_to_string(&path).expect("the corpus file is readable");

    replay_document(&json, Some(&path));
}
