//! Equivalence test replaying golden operation scripts from the Python
//! `deterministic_identifiers_by_name_hint` oracle against
//! `fhy_core::testing::DeterministicIdentifierScope`.
//!
//! The golden data is generated by
//! `rust/fhy-core/tests/golden/generate_deterministic_identifier_cases.py` and
//! committed at `rust/fhy-core/tests/golden/deterministic_identifier_cases.json`.
//! This test only uses the public `fhy_core::identifier` and
//! `fhy_core::testing` APIs.
//!
//! Every script starts outside any scope by creating an anchor identifier,
//! then runs `enter`, `exit` (LIFO, via a stack of guards) and `new(hint)`
//! operations on one thread. The one observation checked for each `new` is
//! its identifier's id minus the anchor's id, which is only meaningful when
//! nothing else in this process allocates an id while a script runs. Both
//! `#[test]` functions below therefore hold one shared `static` `Mutex<()>`
//! for their whole duration, so the default and the ignored expanded-corpus
//! test can never interleave, even under `--include-ignored`. Nothing in
//! this binary may touch the shipped constants
//! (`fhy_core::op_attribute::*`, `fhy_core::value_domain::*`) or allocate an
//! identifier outside a script's own operations.

use std::sync::{Mutex, PoisonError};

use fhy_core::identifier::Identifier;
use fhy_core::testing::DeterministicIdentifierScope;
use serde_json::Value;

const GOLDEN_JSON: &str = include_str!("golden/deterministic_identifier_cases.json");

/// Serializes every script this binary replays, so exact relative ids are
/// never disturbed by another test's identifier allocations.
static REPLAY_LOCK: Mutex<()> = Mutex::new(());

/// Lock [`REPLAY_LOCK`] for the caller's whole replay, recovering from
/// poisoning: the lock only ever guards plain data replay, so a poisoning
/// panic leaves nothing to actually repair.
fn lock_replay() -> std::sync::MutexGuard<'static, ()> {
    REPLAY_LOCK.lock().unwrap_or_else(PoisonError::into_inner)
}

/// Replay one script's operations on the current thread, comparing each
/// `new`'s observation against the golden data.
///
/// `enter` and `exit` push and pop a stack of guards, since Rust drives a
/// scope through RAII rather than the Python singleton's own enter/exit
/// counting.
fn replay_case(case: &Value, mismatches: &mut Vec<String>) {
    let name = case["name"].as_str().expect("case has a name");
    let ops = case["ops"].as_array().expect("case has an ops array");

    let anchor_id = Identifier::new("anchor").id();
    let mut guards: Vec<DeterministicIdentifierScope> = Vec::new();

    for (index, op) in ops.iter().enumerate() {
        match op["op"].as_str().expect("op has a kind") {
            "enter" => guards.push(DeterministicIdentifierScope::enter()),
            "exit" => {
                let _dropped = guards
                    .pop()
                    .unwrap_or_else(|| panic!("case {name} op {index}: exit with no open scope"));
            }
            "new" => {
                let hint = op["hint"].as_str().expect("new op has a hint");
                let expected_relative_id = op["expected"]["relative_id"]
                    .as_u64()
                    .expect("new expectation has a non-negative `relative_id`");

                let identifier = Identifier::new(hint);
                let actual_relative_id = identifier
                    .id()
                    .checked_sub(anchor_id)
                    .expect("a script's identifier id must not precede its anchor's id");

                if actual_relative_id != expected_relative_id {
                    mismatches.push(format!(
                        "case {name} op {index}: expected relative_id={expected_relative_id}, \
                         got {actual_relative_id}"
                    ));
                }
            }
            other => panic!("case {name} op {index}: unknown op kind {other:?}"),
        }
    }

    assert!(
        guards.is_empty(),
        "case {name}: golden script left {} scope(s) open",
        guards.len()
    );
}

/// Assert the golden data is large enough that an empty or truncated file
/// cannot pass this test.
fn assert_case_and_op_counts(cases: &[Value]) {
    assert!(
        cases.len() >= 100,
        "expected at least 100 golden cases, found {}",
        cases.len()
    );
    let total_ops: usize = cases
        .iter()
        .map(|case| case["ops"].as_array().map_or(0, Vec::len))
        .sum();
    assert!(
        total_ops >= 1000,
        "expected at least 1000 golden ops, found {total_ops}"
    );
}

/// Parse a golden document, check its size, replay every case, and return
/// the mismatches found.
fn replay_golden_document(json: &str) -> Vec<String> {
    let document: Value = serde_json::from_str(json).expect("golden data is valid JSON");
    let cases = document["cases"]
        .as_array()
        .expect("golden data has a `cases` array");

    assert_case_and_op_counts(cases);

    let mut mismatches = Vec::new();
    for case in cases {
        replay_case(case, &mut mismatches);
    }
    mismatches
}

/// Test the Rust `DeterministicIdentifierScope` scope reproduces every
/// observation the Python oracle recorded for the golden operation scripts.
#[test]
fn deterministic_identifiers_match_the_python_oracle() {
    let _replay = lock_replay();

    let mismatches = replay_golden_document(GOLDEN_JSON);

    assert!(
        mismatches.is_empty(),
        "found {} mismatch(es):\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
}

/// Test the Rust scope reproduces every observation the Python oracle
/// recorded for an expanded corpus, read from the file named by
/// `FHY_DETERMINISTIC_IDENTIFIER_CORPUS` and written with the generator's
/// corpus options.
#[test]
#[ignore = "requires an expanded corpus generated from the Python oracle"]
fn deterministic_identifiers_match_the_python_oracle_on_an_expanded_corpus() {
    let _replay = lock_replay();

    let path = std::env::var("FHY_DETERMINISTIC_IDENTIFIER_CORPUS")
        .expect("FHY_DETERMINISTIC_IDENTIFIER_CORPUS names an expanded corpus file");
    let json = std::fs::read_to_string(&path).expect("expanded corpus file is readable");

    let mismatches = replay_golden_document(&json);

    assert!(
        mismatches.is_empty(),
        "found {} mismatch(es) in {path}:\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
}
