//! Equivalence test replaying golden expression trees from the Python
//! expression oracle against `fhy_core::symbolic::expression`.
//!
//! The golden data is generated by
//! `rust/fhy-core/tests/golden/generate_expression_cases.py` and committed at
//! `rust/fhy-core/tests/golden/expression_cases.json`. Each case gives a tree
//! by its wire form (compact JSON text), with identifiers written as
//! `{"slot": name}`, and records the tree's children, free identifiers,
//! substitution results, screen verdicts, and structural equality against
//! other trees; the tree's own wire form is its round trip. Nodes are named
//! by paths into a wire form (`/`-joined `__data__` field names, with a list
//! index after a list field), a substitution result by the paths of the
//! leaves it replaces, and a compared tree by a case index with an optional
//! leaf edit. A second section records payloads the oracle refuses to
//! decode. This test mints one identifier per slot and case, resolves every
//! path on the Rust side, and compares wire forms with identifiers turned
//! back into slots; numbers compare by kind (an integer token never equals a
//! float token) and then by value. Public API only.

use std::collections::hash_map::DefaultHasher;
use std::collections::{BTreeSet, HashMap};
use std::hash::{Hash, Hasher};

use fhy_core::identifier::Identifier;
use fhy_core::symbolic::expression::{
    BinaryOperation, BooleanPosition, Expression, ExpressionBuildError, NoRegisteredSorts,
    NonBooleanLogicalOperandError, validate_logical_operands, validate_predicate,
};
use fhy_core::symbolic::symbol_type::SymbolType;
use serde_json::{Map, Value, json};

const GOLDEN_JSON: &str = include_str!("golden/expression_cases.json");

const MIN_CASES: usize = 90;

const MIN_DECODE_ERRORS: usize = 15;

/// The identifier slots the golden trees use.
const SLOTS: [&str; 5] = ["x", "y", "z", "p", "q"];

/// The identifiers minted for one case's slots, in both directions.
struct SlotTable {
    by_slot: HashMap<String, Identifier>,
    by_id: HashMap<u64, String>,
}

impl SlotTable {
    /// Mint one identifier per slot.
    fn new() -> Self {
        let by_slot: HashMap<String, Identifier> = SLOTS
            .iter()
            .map(|slot| ((*slot).to_owned(), Identifier::new(slot)))
            .collect();
        let by_id = by_slot
            .iter()
            .map(|(slot, identifier)| (identifier.id(), slot.clone()))
            .collect();
        Self { by_slot, by_id }
    }

    /// Return the identifier minted for `slot`.
    fn find_identifier(&self, slot: &str) -> Identifier {
        self.by_slot
            .get(slot)
            .unwrap_or_else(|| panic!("unknown slot {slot}"))
            .clone()
    }

    /// Return `wire` with every slot placeholder replaced by its identifier.
    fn bind(&self, wire: &Value) -> Value {
        match wire {
            Value::Object(map) if map.len() == 1 && map.contains_key("slot") => {
                let identifier = self.find_identifier(map["slot"].as_str().expect("a slot name"));
                json!({"id": identifier.id(), "name_hint": identifier.name_hint()})
            }
            Value::Object(map) => Value::Object(
                map.iter()
                    .map(|(key, value)| (key.clone(), self.bind(value)))
                    .collect::<Map<String, Value>>(),
            ),
            Value::Array(items) => Value::Array(items.iter().map(|item| self.bind(item)).collect()),
            other => other.clone(),
        }
    }

    /// Return `wire` with every identifier replaced by its slot placeholder.
    fn unbind(&self, wire: &Value) -> Result<Value, String> {
        match wire {
            Value::Object(map)
                if map.len() == 2 && map.contains_key("id") && map.contains_key("name_hint") =>
            {
                let id = map["id"]
                    .as_u64()
                    .ok_or_else(|| format!("bad id in {wire}"))?;
                let slot = self
                    .by_id
                    .get(&id)
                    .ok_or_else(|| format!("identifier {wire} is no slot's"))?;
                Ok(json!({"slot": slot}))
            }
            Value::Object(map) => map
                .iter()
                .map(|(key, value)| Ok((key.clone(), self.unbind(value)?)))
                .collect::<Result<Map<String, Value>, String>>()
                .map(Value::Object),
            Value::Array(items) => items
                .iter()
                .map(|item| self.unbind(item))
                .collect::<Result<Vec<Value>, String>>()
                .map(Value::Array),
            other => Ok(other.clone()),
        }
    }

    /// Decode a slot-form wire value.
    fn decode(&self, wire: &Value) -> Result<Expression, String> {
        serde_json::from_value(self.bind(wire)).map_err(|error| format!("decode failed: {error}"))
    }

    /// Encode an expression to a slot-form wire value.
    fn encode(&self, expression: &Expression) -> Result<Value, String> {
        let wire =
            serde_json::to_value(expression).map_err(|error| format!("encode failed: {error}"))?;
        self.unbind(&wire)
    }
}

/// Return whether a JSON number was written as an integer token.
fn is_integer_token(number: &serde_json::Number) -> bool {
    !number.to_string().contains(['.', 'e', 'E'])
}

/// Compare two wire values: structure and strings exactly, integer tokens by
/// their digits, float tokens by their value, and never an integer token
/// with a float token.
fn compare_wire(actual: &Value, expected: &Value, path: &str) -> Result<(), String> {
    match (actual, expected) {
        (Value::Number(actual_number), Value::Number(expected_number)) => {
            let same = match (
                is_integer_token(actual_number),
                is_integer_token(expected_number),
            ) {
                (true, true) => actual_number.to_string() == expected_number.to_string(),
                (false, false) => {
                    let parse = |number: &serde_json::Number| {
                        number.to_string().parse::<f64>().map(f64::to_bits).ok()
                    };
                    parse(actual_number) == parse(expected_number)
                }
                _ => false,
            };
            if same {
                Ok(())
            } else {
                Err(format!(
                    "{path}: {actual_number} vs expected {expected_number}"
                ))
            }
        }
        (Value::Object(actual_map), Value::Object(expected_map)) => {
            let actual_keys: Vec<&String> = actual_map.keys().collect();
            let expected_keys: Vec<&String> = expected_map.keys().collect();
            if actual_keys != expected_keys {
                return Err(format!(
                    "{path}: keys {actual_keys:?} vs expected {expected_keys:?}"
                ));
            }
            for (key, value) in actual_map {
                compare_wire(value, &expected_map[key], &format!("{path}.{key}"))?;
            }
            Ok(())
        }
        (Value::Array(actual_items), Value::Array(expected_items)) => {
            if actual_items.len() != expected_items.len() {
                return Err(format!(
                    "{path}: {} items vs expected {}",
                    actual_items.len(),
                    expected_items.len()
                ));
            }
            for (index, (item, expected_item)) in
                actual_items.iter().zip(expected_items).enumerate()
            {
                compare_wire(item, expected_item, &format!("{path}[{index}]"))?;
            }
            Ok(())
        }
        _ if actual == expected => Ok(()),
        _ => Err(format!("{path}: {actual} vs expected {expected}")),
    }
}

/// Return the default hash of `expression`.
fn hash_of(expression: &Expression) -> u64 {
    let mut hasher = DefaultHasher::new();
    expression.hash(&mut hasher);
    hasher.finish()
}

/// Return the position a golden verdict names.
fn parse_position(position: &Value) -> BooleanPosition {
    let case_index = || {
        usize::try_from(position["case_index"].as_u64().expect("a case index"))
            .expect("a small case index")
    };
    match position["kind"].as_str().expect("a position kind") {
        "negated_operand" => BooleanPosition::NegatedOperand,
        "logical_operand" => BooleanPosition::LogicalOperand {
            operation: serde_json::from_value::<BinaryOperation>(position["operation"].clone())
                .expect("a wire operation name"),
        },
        "case_condition" => BooleanPosition::CaseCondition {
            case_index: case_index(),
        },
        "case_value" => BooleanPosition::CaseValue {
            case_index: case_index(),
        },
        "otherwise" => BooleanPosition::Otherwise,
        "predicate_root" => BooleanPosition::PredicateRoot,
        other => panic!("unknown position kind {other}"),
    }
}

/// Parse wire text recorded as compact JSON.
fn parse_wire(text: &Value) -> Value {
    serde_json::from_str(text.as_str().expect("wire text is a string"))
        .expect("wire text is valid JSON")
}

/// Return the node of `wire` at `path`.
fn resolve_path<'a>(wire: &'a Value, path: &str) -> Result<&'a Value, String> {
    let mut node = wire;
    for step in path.split('/').filter(|step| !step.is_empty()) {
        node = match step.parse::<usize>() {
            Ok(index) => node.get(index),
            Err(_) => node["__data__"].get(step),
        }
        .ok_or_else(|| format!("no node at `{path}` in {wire}"))?;
    }
    Ok(node)
}

/// Return `wire` with the node at `path` replaced by `replacement`.
fn replace_at_path(wire: &Value, path: &str, replacement: Value) -> Result<Value, String> {
    let mut rewritten = wire.clone();
    let mut node = &mut rewritten;
    for step in path.split('/').filter(|step| !step.is_empty()) {
        node = match step.parse::<usize>() {
            Ok(index) => node.get_mut(index),
            Err(_) => node.get_mut("__data__").and_then(|data| data.get_mut(step)),
        }
        .ok_or_else(|| format!("no node at `{path}` in {wire}"))?;
    }
    *node = replacement;
    Ok(rewritten)
}

/// Compare a screen's outcome with the golden verdict, resolving its paths
/// in the tree or in the bound value it names.
fn check_verdict(
    table: &SlotTable,
    tree: &Value,
    environment: &Map<String, Value>,
    outcome: &Result<(), NonBooleanLogicalOperandError>,
    verdict: &Value,
) -> Result<(), String> {
    match (outcome, verdict) {
        (Ok(()), Value::Null) => Ok(()),
        (Ok(()), _) => Err(format!("passed, expected a refusal {verdict}")),
        (Err(error), Value::Null) => Err(format!("refused ({error}), expected a pass")),
        (Err(error), _) => {
            let bound;
            let source = match &verdict["source"] {
                Value::Null => tree,
                slot => {
                    let slot = slot.as_str().expect("a source slot");
                    bound = parse_wire(&environment[slot]);
                    &bound
                }
            };
            let path = |field: &str| verdict[field].as_str().expect("a path").to_owned();
            let operand = table.decode(resolve_path(source, &path("operand"))?)?;
            let parent = match &verdict["parent"] {
                Value::Null => None,
                _ => Some(table.decode(resolve_path(source, &path("parent"))?)?),
            };
            let position = parse_position(&verdict["position"]);
            if error.operand() != &operand
                || error.parent() != parent.as_ref()
                || error.position() != position
            {
                return Err(format!("refused with {error:?}, expected {verdict}"));
            }
            Ok(())
        }
    }
}

/// Decode a slot-to-wire-text map.
fn decode_environment(
    table: &SlotTable,
    wire: &Value,
) -> Result<HashMap<Identifier, Expression>, String> {
    wire.as_object()
        .expect("an environment map")
        .iter()
        .map(|(slot, value)| {
            Ok((
                table.find_identifier(slot),
                table.decode(&parse_wire(value))?,
            ))
        })
        .collect()
}

/// Replay one tree case, recording every disagreement with the oracle;
/// `trees` holds every case's tree, for the comparisons.
fn replay_case(case: &Value, trees: &[Value], mismatches: &mut Vec<String>) {
    let name = case["name"].as_str().expect("a case has a name");
    let table = SlotTable::new();
    if let Err(message) = check_case(&table, case, trees) {
        mismatches.push(format!("{name}: {message}"));
    }
}

/// Check every observation of one case, stopping at the first disagreement.
fn check_case(table: &SlotTable, case: &Value, trees: &[Value]) -> Result<(), String> {
    let tree = parse_wire(&case["tree"]);
    let expression = table.decode(&tree)?;
    check_children(table, &expression, &tree, case)?;
    check_free_identifiers(table, &expression, case)?;
    compare_wire(&table.encode(&expression)?, &tree, "round_trip")?;
    check_substitutions(table, &expression, &tree, case)?;
    check_screens(table, &expression, &tree, case)?;
    check_comparisons(table, &expression, case, trees)
}

/// Check the children against the nodes at the recorded paths.
fn check_children(
    table: &SlotTable,
    expression: &Expression,
    tree: &Value,
    case: &Value,
) -> Result<(), String> {
    let expected_paths = case["children"].as_array().expect("a children list");
    let children: Vec<&Expression> = expression.children().collect();
    if children.len() != expected_paths.len() {
        return Err(format!(
            "{} children, expected {}",
            children.len(),
            expected_paths.len()
        ));
    }
    for (index, (child, path)) in children.iter().zip(expected_paths).enumerate() {
        let expected = resolve_path(tree, path.as_str().expect("a child path"))?;
        compare_wire(
            &table.encode(child)?,
            expected,
            &format!("children[{index}]"),
        )?;
    }
    Ok(())
}

/// Check the free identifiers against the recorded slots.
fn check_free_identifiers(
    table: &SlotTable,
    expression: &Expression,
    case: &Value,
) -> Result<(), String> {
    let free: BTreeSet<String> = expression
        .free_identifiers()
        .iter()
        .map(|identifier| table.by_id[&identifier.id()].clone())
        .collect();
    let expected_free: BTreeSet<String> = case["free_identifiers"]
        .as_array()
        .expect("a free-identifier list")
        .iter()
        .map(|slot| slot.as_str().expect("a slot").to_owned())
        .collect();
    if free == expected_free {
        Ok(())
    } else {
        Err(format!(
            "free identifiers {free:?}, expected {expected_free:?}"
        ))
    }
}

/// Return the tree with the identifier leaf at each of `replaced_paths`
/// replaced by the wire of its slot in `mapping`.
fn rewrite_leaves(tree: &Value, mapping: &Value, replaced_paths: &Value) -> Result<Value, String> {
    let mut rewritten = tree.clone();
    for path in replaced_paths.as_array().expect("a path list") {
        let path = path.as_str().expect("a leaf path");
        let slot = resolve_path(tree, path)?["__data__"]["identifier"]["slot"]
            .as_str()
            .ok_or_else(|| format!("no identifier leaf at `{path}`"))?;
        rewritten = replace_at_path(&rewritten, path, parse_wire(&mapping[slot]))?;
    }
    Ok(rewritten)
}

/// Check each substitution's result, rebuilt from its replaced leaves, or
/// its refusal.
fn check_substitutions(
    table: &SlotTable,
    expression: &Expression,
    tree: &Value,
    case: &Value,
) -> Result<(), String> {
    let substitutions = case["substitutions"].as_array().expect("a list");
    for (index, substitution) in substitutions.iter().enumerate() {
        let mapping = decode_environment(table, &substitution["mapping"])?;
        let outcome = expression.substitute(&mapping);
        match (outcome, substitution.get("replaced")) {
            (Ok(result), Some(replaced_paths)) => {
                let expected = rewrite_leaves(tree, &substitution["mapping"], replaced_paths)?;
                let path = format!("substitutions[{index}]");
                compare_wire(&table.encode(&result)?, &expected, &path)?;
            }
            (Err(ExpressionBuildError::NonBooleanConditionLiteral { .. }), None) => {}
            (outcome, _) => {
                return Err(format!(
                    "substitution {index}: {outcome:?}, expected {substitution}"
                ));
            }
        }
    }
    Ok(())
}

/// Check both screens under each recorded environment and declared types.
fn check_screens(
    table: &SlotTable,
    expression: &Expression,
    tree: &Value,
    case: &Value,
) -> Result<(), String> {
    let screens = case["screens"].as_array().expect("a list");
    for (index, screen) in screens.iter().enumerate() {
        let environment_wires = screen["environment"].as_object().expect("an environment");
        let environment = decode_environment(table, &screen["environment"])?;
        let symbol_types: HashMap<Identifier, SymbolType> = screen["symbol_types"]
            .as_object()
            .expect("a symbol-type map")
            .iter()
            .map(|(slot, symbol_type)| {
                let symbol_type =
                    serde_json::from_value(symbol_type.clone()).expect("a symbol type name");
                (table.find_identifier(slot), symbol_type)
            })
            .collect();
        let operands_outcome =
            validate_logical_operands(expression, &environment, &symbol_types, &NoRegisteredSorts);
        let predicate_outcome =
            validate_predicate(expression, &environment, &symbol_types, &NoRegisteredSorts);
        check_verdict(
            table,
            tree,
            environment_wires,
            &operands_outcome,
            &screen["logical_operands"],
        )
        .map_err(|message| format!("screens[{index}] logical operands: {message}"))?;
        check_verdict(
            table,
            tree,
            environment_wires,
            &predicate_outcome,
            &screen["predicate"],
        )
        .map_err(|message| format!("screens[{index}] predicate: {message}"))?;
    }
    Ok(())
}

/// Return the tree a comparison names: a case's tree, with the leaf at
/// `path` replaced by `leaf` when the comparison edits one.
fn build_compared_tree(reference: &Value, trees: &[Value]) -> Result<Value, String> {
    let index = usize::try_from(reference["case"].as_u64().expect("a case index"))
        .expect("a small case index");
    let tree = &trees[index];
    match &reference["path"] {
        Value::Null => Ok(tree.clone()),
        path => replace_at_path(
            tree,
            path.as_str().expect("a leaf path"),
            parse_wire(&reference["leaf"]),
        ),
    }
}

/// Check equality in both directions, and hashing of equal trees, against
/// each recorded comparison.
fn check_comparisons(
    table: &SlotTable,
    expression: &Expression,
    case: &Value,
    trees: &[Value],
) -> Result<(), String> {
    let comparisons = case["comparisons"].as_array().expect("a list");
    for (index, comparison) in comparisons.iter().enumerate() {
        let other = table.decode(&build_compared_tree(&comparison["other"], trees)?)?;
        let expected = comparison["equivalent"].as_bool().expect("a verdict");
        let forward = expression == &other;
        let backward = &other == expression;
        if forward != expected || backward != expected {
            return Err(format!(
                "comparisons[{index}]: equality is {forward} forward and {backward} backward, \
                 expected {expected}"
            ));
        }
        if expected && hash_of(expression) != hash_of(&other) {
            return Err(format!(
                "comparisons[{index}]: equal trees hash differently"
            ));
        }
    }
    Ok(())
}

/// Check one payload the oracle refuses is refused.
fn replay_decode_error(case: &Value, mismatches: &mut Vec<String>) {
    let name = case["name"].as_str().expect("a named payload");
    let table = SlotTable::new();
    if let Ok(expression) = table.decode(&parse_wire(&case["payload"])) {
        mismatches.push(format!(
            "{name}: decoded to {expression:?}, the oracle refuses it with {}",
            case["oracle_error"]
        ));
    }
}

/// Parse a golden document, check its size, replay every case and refused
/// payload, and fail with the disagreements found.
fn replay_document(json: &str, corpus_path: Option<&str>) {
    let document: Value = serde_json::from_str(json).expect("golden data is valid JSON");
    let cases = document["cases"].as_array().expect("a `cases` array");
    let decode_errors = document["decode_errors"]
        .as_array()
        .expect("a `decode_errors` array");
    assert!(
        cases.len() >= MIN_CASES,
        "only {} golden cases",
        cases.len()
    );
    assert!(
        decode_errors.len() >= MIN_DECODE_ERRORS,
        "only {} refused payloads",
        decode_errors.len()
    );

    let trees: Vec<Value> = cases.iter().map(|case| parse_wire(&case["tree"])).collect();

    let mut mismatches = Vec::new();
    for case in cases {
        replay_case(case, &trees, &mut mismatches);
    }
    for case in decode_errors {
        replay_decode_error(case, &mut mismatches);
    }

    let location = corpus_path
        .map(|path| format!(" in {path}"))
        .unwrap_or_default();
    assert!(
        mismatches.is_empty(),
        "found {} mismatch(es){location}:\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
}

/// Test every committed expression case and refused payload agrees with the
/// Python oracle.
#[test]
fn expressions_match_the_python_oracle() {
    replay_document(GOLDEN_JSON, None);
}

/// Test an expanded corpus, named by `FHY_EXPRESSION_CORPUS`, agrees with
/// the Python oracle.
#[test]
#[ignore = "requires an expanded corpus generated from the Python oracle"]
fn expressions_match_the_python_oracle_on_an_expanded_corpus() {
    let path = std::env::var("FHY_EXPRESSION_CORPUS")
        .expect("FHY_EXPRESSION_CORPUS names an expanded corpus file");
    let json = std::fs::read_to_string(&path).expect("the expanded corpus file is readable");

    replay_document(&json, Some(&path));
}
