//! Equivalence test replaying golden literal cases from the Python literal
//! oracle against `fhy_core::symbolic::expression::LiteralValue`.
//!
//! The golden data is generated by
//! `rust/fhy-core/tests/golden/generate_literal_cases.py` and committed at
//! `rust/fhy-core/tests/golden/literal_cases.json`. Each case names one
//! literal (a Boolean, an integer of any size, a float by its bit pattern, or
//! a text) with the oracle's verdict on the text grammar, its canonical key,
//! whether it is integer-valued, its `Display` text, and the sorts it has; a
//! second section records the oracle's equality over every pair of a sample.
//! Public API only.

use fhy_core::symbolic::expression::{FunctionSort, LiteralValue};
use num_bigint::BigInt;
use serde_json::Value;

const GOLDEN_JSON: &str = include_str!("golden/literal_cases.json");

const MIN_CASES: usize = 400;

const MIN_PAIRS: usize = 600;

/// The sorts a case records, keyed by their text.
const SORTS: [FunctionSort; 4] = [
    FunctionSort::Bool,
    FunctionSort::Nat,
    FunctionSort::Int,
    FunctionSort::Real,
];

/// Build the literal a golden spec names, or return the grammar refusal of a
/// text spec.
fn build_literal_from_spec(spec: &Value) -> Result<LiteralValue, String> {
    let kind = spec["kind"].as_str().expect("a spec names its kind");
    match kind {
        "bool" => Ok(LiteralValue::from(
            spec["value"]
                .as_bool()
                .expect("a Boolean spec holds a Boolean"),
        )),
        "int" => {
            let digits = spec["value"]
                .as_number()
                .expect("an integer spec holds a number")
                .to_string();
            Ok(LiteralValue::from(
                digits
                    .parse::<BigInt>()
                    .expect("an integer spec holds digits"),
            ))
        }
        "float" => {
            let bits = u64::from_str_radix(
                spec["bits"].as_str().expect("a float spec holds its bits"),
                16,
            )
            .expect("float bits are hexadecimal");
            Ok(LiteralValue::from(f64::from_bits(bits)))
        }
        "text" => LiteralValue::parse_text(spec["value"].as_str().expect("a text spec"))
            .map_err(|error| error.to_string()),
        _ => panic!("unknown literal kind {kind}"),
    }
}

/// Replay one literal case, recording every disagreement with the oracle.
fn replay_case(case: &Value, mismatches: &mut Vec<String>) {
    let name = case["name"].as_str().expect("a case has a name");
    let accepted = case["accepted"]
        .as_bool()
        .expect("a case records acceptance");
    let literal = match (build_literal_from_spec(&case["literal"]), accepted) {
        (Ok(literal), true) => literal,
        (Err(_), false) => return,
        (Ok(literal), false) => {
            mismatches.push(format!(
                "{name}: accepted {literal:?}, the oracle refuses it"
            ));
            return;
        }
        (Err(error), true) => {
            mismatches.push(format!("{name}: refused ({error}), the oracle accepts it"));
            return;
        }
    };
    let expected_key = case["canonical_key"].as_str().expect("a key");
    let key = literal.canonical_key();
    if key != expected_key {
        mismatches.push(format!("{name}: key {key:?}, expected {expected_key:?}"));
    }
    let expected_integer_valued = case["is_integer_valued"].as_bool().expect("a flag");
    if literal.is_integer_valued() != expected_integer_valued {
        mismatches.push(format!(
            "{name}: is_integer_valued {}, expected {expected_integer_valued}",
            literal.is_integer_valued()
        ));
    }
    let expected_text = case["text"].as_str().expect("a text");
    let text = literal.to_string();
    if text != expected_text {
        mismatches.push(format!(
            "{name}: Display {text:?}, expected {expected_text:?}"
        ));
    }
    for sort in SORTS {
        let expected = case["sorts"][sort.as_str()]
            .as_bool()
            .expect("a verdict per sort");
        if sort.accepts_literal(&literal) != expected {
            mismatches.push(format!(
                "{name}: {sort} accepts it is {}, expected {expected}",
                !expected
            ));
        }
    }
}

/// Replay one equality pair, recording a disagreement with the oracle.
fn replay_pair(pair: &Value, mismatches: &mut Vec<String>) {
    let left_name = pair["left"]["name"].as_str().expect("a named literal");
    let right_name = pair["right"]["name"].as_str().expect("a named literal");
    let left = build_literal_from_spec(&pair["left"]["literal"]).expect("sample literals parse");
    let right = build_literal_from_spec(&pair["right"]["literal"]).expect("sample literals parse");
    let expected = pair["equivalent"].as_bool().expect("a verdict");
    if (left == right) != expected {
        mismatches.push(format!(
            "{left_name} == {right_name} is {}, expected {expected}",
            !expected
        ));
    }
}

/// Parse a golden document, check its size, replay every case and pair, and
/// fail with the disagreements found.
fn replay_document(json: &str, corpus_path: Option<&str>) {
    let document: Value = serde_json::from_str(json).expect("golden data is valid JSON");
    let cases = document["cases"].as_array().expect("a `cases` array");
    let pairs = document["equivalence_pairs"]
        .as_array()
        .expect("an `equivalence_pairs` array");
    assert!(
        cases.len() >= MIN_CASES,
        "only {} golden cases",
        cases.len()
    );
    assert!(
        pairs.len() >= MIN_PAIRS,
        "only {} golden pairs",
        pairs.len()
    );

    let mut mismatches = Vec::new();
    for case in cases {
        replay_case(case, &mut mismatches);
    }
    for pair in pairs {
        replay_pair(pair, &mut mismatches);
    }

    let location = corpus_path
        .map(|path| format!(" in {path}"))
        .unwrap_or_default();
    assert!(
        mismatches.is_empty(),
        "found {} mismatch(es){location}:\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
}

/// Test every committed literal case and pair agrees with the Python
/// oracle.
#[test]
fn literal_values_match_the_python_oracle() {
    replay_document(GOLDEN_JSON, None);
}

/// Test an expanded corpus, named by `FHY_LITERAL_CORPUS`, agrees with the
/// Python oracle.
#[test]
#[ignore = "requires an expanded corpus generated from the Python oracle"]
fn literal_values_match_the_python_oracle_on_an_expanded_corpus() {
    let path = std::env::var("FHY_LITERAL_CORPUS")
        .expect("FHY_LITERAL_CORPUS names an expanded corpus file");
    let json = std::fs::read_to_string(&path).expect("the expanded corpus file is readable");

    replay_document(&json, Some(&path));
}
