//! Equivalence test replaying golden pattern-matching and rewrite cases from
//! the Python pattern oracle against `fhy_core::symbolic::expression::pattern`.
//!
//! The golden data is generated by
//! `rust/fhy-core/tests/golden/generate_pattern_cases.py` and committed at
//! `rust/fhy-core/tests/golden/pattern_cases.json`. Trees are given by their
//! wire form with identifiers written as `{"slot": name}`; patterns and rules
//! are declarative specs, described in the generator, whose predicates,
//! guards and rewrites this test implements exactly as the generator does.
//! Match cases record the bindings in binding order, no match, or a failing
//! predicate; rewrite cases record the output tree, whether it is a new
//! node, and the fired rules in walk order, or the failing rule, or a
//! refused rebuild. This test mints one identifier per slot and case and
//! compares wire forms with identifiers turned back into slots. Public API
//! only.

use std::collections::HashMap;
use std::error::Error;
use std::fmt;

use fhy_core::identifier::Identifier;
use fhy_core::symbolic::expression::pattern::{
    CallbackError, MatchBindings, Pattern, RewriteError, RewriteRule, apply_rewrite_rules,
    match_pattern,
};
use fhy_core::symbolic::expression::{
    BinaryOperation, Expression, ExpressionBuildError, ExpressionKind, LiteralValue, UnaryOperation,
};
use serde_json::{Map, Value, json};

const GOLDEN_JSON: &str = include_str!("golden/pattern_cases.json");

const MIN_MATCH_CASES: usize = 180;

const MIN_REWRITE_CASES: usize = 85;

/// The identifier slots the golden trees and patterns use.
const SLOTS: [&str; 5] = ["x", "y", "z", "p", "q"];

/// A scripted callback failure, naming the rule whose callback failed.
#[derive(Debug)]
struct ScriptError(usize);

impl fmt::Display for ScriptError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "scripted failure in rule {}", self.0)
    }
}

impl Error for ScriptError {}

/// The identifiers minted for one case's slots, in both directions.
struct SlotTable {
    by_slot: HashMap<String, Identifier>,
    by_id: HashMap<u64, String>,
}

impl SlotTable {
    /// Mint one identifier per slot.
    fn new() -> Self {
        let by_slot: HashMap<String, Identifier> = SLOTS
            .iter()
            .map(|slot| ((*slot).to_owned(), Identifier::new(slot)))
            .collect();
        let by_id = by_slot
            .iter()
            .map(|(slot, identifier)| (identifier.id(), slot.clone()))
            .collect();
        Self { by_slot, by_id }
    }

    /// Return the identifier minted for `slot`.
    fn find_identifier(&self, slot: &str) -> Identifier {
        self.by_slot
            .get(slot)
            .unwrap_or_else(|| panic!("unknown slot {slot}"))
            .clone()
    }

    /// Return `wire` with every slot placeholder replaced by its identifier.
    fn bind(&self, wire: &Value) -> Value {
        match wire {
            Value::Object(map) if map.len() == 1 && map.contains_key("slot") => {
                let identifier = self.find_identifier(map["slot"].as_str().expect("a slot name"));
                json!({"id": identifier.id(), "name_hint": identifier.name_hint()})
            }
            Value::Object(map) => Value::Object(
                map.iter()
                    .map(|(key, value)| (key.clone(), self.bind(value)))
                    .collect::<Map<String, Value>>(),
            ),
            Value::Array(items) => Value::Array(items.iter().map(|item| self.bind(item)).collect()),
            other => other.clone(),
        }
    }

    /// Return `wire` with every identifier replaced by its slot placeholder.
    fn unbind(&self, wire: &Value) -> Result<Value, String> {
        match wire {
            Value::Object(map)
                if map.len() == 2 && map.contains_key("id") && map.contains_key("name_hint") =>
            {
                let id = map["id"]
                    .as_u64()
                    .ok_or_else(|| format!("bad id in {wire}"))?;
                let slot = self
                    .by_id
                    .get(&id)
                    .ok_or_else(|| format!("identifier {wire} is no slot's"))?;
                Ok(json!({"slot": slot}))
            }
            Value::Object(map) => map
                .iter()
                .map(|(key, value)| Ok((key.clone(), self.unbind(value)?)))
                .collect::<Result<Map<String, Value>, String>>()
                .map(Value::Object),
            Value::Array(items) => items
                .iter()
                .map(|item| self.unbind(item))
                .collect::<Result<Vec<Value>, String>>()
                .map(Value::Array),
            other => Ok(other.clone()),
        }
    }

    /// Decode a slot-form wire value.
    fn decode(&self, wire: &Value) -> Result<Expression, String> {
        serde_json::from_value(self.bind(wire)).map_err(|error| format!("decode failed: {error}"))
    }

    /// Encode an expression to a slot-form wire value.
    fn encode(&self, expression: &Expression) -> Result<Value, String> {
        let wire =
            serde_json::to_value(expression).map_err(|error| format!("encode failed: {error}"))?;
        self.unbind(&wire)
    }
}

/// Return whether a JSON number was written as an integer token.
fn is_integer_token(number: &serde_json::Number) -> bool {
    !number.to_string().contains(['.', 'e', 'E'])
}

/// Compare two wire values: structure and strings exactly, integer tokens by
/// their digits, float tokens by their value, and never an integer token
/// with a float token.
fn compare_wire(actual: &Value, expected: &Value, path: &str) -> Result<(), String> {
    match (actual, expected) {
        (Value::Number(actual_number), Value::Number(expected_number)) => {
            let same = match (
                is_integer_token(actual_number),
                is_integer_token(expected_number),
            ) {
                (true, true) => actual_number.to_string() == expected_number.to_string(),
                (false, false) => {
                    let parse = |number: &serde_json::Number| {
                        number.to_string().parse::<f64>().map(f64::to_bits).ok()
                    };
                    parse(actual_number) == parse(expected_number)
                }
                _ => false,
            };
            if same {
                Ok(())
            } else {
                Err(format!(
                    "{path}: {actual_number} vs expected {expected_number}"
                ))
            }
        }
        (Value::Object(actual_map), Value::Object(expected_map)) => {
            let actual_keys: Vec<&String> = actual_map.keys().collect();
            let expected_keys: Vec<&String> = expected_map.keys().collect();
            if actual_keys != expected_keys {
                return Err(format!(
                    "{path}: keys {actual_keys:?} vs expected {expected_keys:?}"
                ));
            }
            for (key, value) in actual_map {
                compare_wire(value, &expected_map[key], &format!("{path}.{key}"))?;
            }
            Ok(())
        }
        (Value::Array(actual_items), Value::Array(expected_items)) => {
            if actual_items.len() != expected_items.len() {
                return Err(format!(
                    "{path}: {} items vs expected {}",
                    actual_items.len(),
                    expected_items.len()
                ));
            }
            for (index, (item, expected_item)) in
                actual_items.iter().zip(expected_items).enumerate()
            {
                compare_wire(item, expected_item, &format!("{path}[{index}]"))?;
            }
            Ok(())
        }
        _ if actual == expected => Ok(()),
        _ => Err(format!("{path}: {actual} vs expected {expected}")),
    }
}

/// Return the literal value a spec's raw wire value denotes.
fn decode_literal_value(table: &SlotTable, value: &Value) -> LiteralValue {
    let wire = json!({"__type__": "literal_expression", "__data__": {"value": value}});
    let expression = table.decode(&wire).expect("a literal the grammar accepts");
    let ExpressionKind::Literal(literal) = expression.kind() else {
        panic!("a literal wire form decodes to a literal");
    };
    literal.clone()
}

/// Return the optional string field `key` of `spec`.
fn read_optional_str<'a>(spec: &'a Value, key: &str) -> Option<&'a str> {
    match &spec[key] {
        Value::Null => None,
        value => Some(value.as_str().expect("a string field")),
    }
}

/// Return the array field `key` of `spec`.
fn read_array<'a>(spec: &'a Value, key: &str) -> &'a Vec<Value> {
    spec[key].as_array().expect("an array field")
}

/// Return the named predicate, failing with `rule_index` for `fail`.
fn build_predicate(name: &str, rule_index: usize) -> Pattern {
    match name {
        "is_literal" => Pattern::predicate(|expression| {
            Ok(matches!(expression.kind(), ExpressionKind::Literal(_)))
        }),
        "is_identifier" => Pattern::predicate(|expression| {
            Ok(matches!(expression.kind(), ExpressionKind::Identifier(_)))
        }),
        "has_children" => {
            Pattern::predicate(|expression| Ok(expression.children().next().is_some()))
        }
        "fail" => Pattern::predicate(move |_| Err(CallbackError::new(ScriptError(rule_index)))),
        other => panic!("unknown predicate {other}"),
    }
}

/// Return the pattern a spec describes; its predicates fail with
/// `rule_index`.
fn build_pattern(spec: &Value, table: &SlotTable, rule_index: usize) -> Pattern {
    let build = |child: &Value| build_pattern(child, table, rule_index);
    match spec["kind"].as_str().expect("a pattern kind") {
        "wildcard" => Pattern::wildcard(),
        "capture" => Pattern::capture(
            spec["name"].as_str().expect("a capture name"),
            build(&spec["sub_pattern"]),
        )
        .expect("a non-empty capture name"),
        "literal" => Pattern::literal(match &spec["value"] {
            Value::Null => None,
            value => Some(decode_literal_value(table, value)),
        }),
        "identifier" => Pattern::identifier(
            read_optional_str(spec, "slot").map(|slot| table.find_identifier(slot)),
        ),
        "unary" => Pattern::unary(
            read_optional_str(spec, "operation").map(|operation| {
                serde_json::from_value::<UnaryOperation>(json!(operation))
                    .expect("a unary operation")
            }),
            build(&spec["operand"]),
        ),
        "binary" => Pattern::binary(
            read_optional_str(spec, "operation").map(|operation| {
                serde_json::from_value::<BinaryOperation>(json!(operation))
                    .expect("a binary operation")
            }),
            build(&spec["left"]),
            build(&spec["right"]),
        ),
        "piecewise" => Pattern::piecewise(
            match &spec["cases"] {
                Value::Null => None,
                cases => Some(
                    cases
                        .as_array()
                        .expect("a case list")
                        .iter()
                        .map(|case| (build(&case[0]), build(&case[1])))
                        .collect(),
                ),
            },
            build(&spec["otherwise"]),
        )
        .expect("no empty case list"),
        "call" => Pattern::call(
            read_optional_str(spec, "function_name"),
            match &spec["arguments"] {
                Value::Null => None,
                arguments => Some(
                    arguments
                        .as_array()
                        .expect("a list")
                        .iter()
                        .map(build)
                        .collect(),
                ),
            },
        ),
        "alternatives" => {
            Pattern::alternatives(read_array(spec, "alternatives").iter().map(build).collect())
                .expect("at least one alternative")
        }
        "predicate" => build_predicate(
            spec["predicate"].as_str().expect("a predicate name"),
            rule_index,
        ),
        other => panic!("unknown pattern kind {other}"),
    }
}

/// Return the expression `bindings` binds to `capture`, failing with
/// `rule_index` when it is unbound.
fn find_bound(
    bindings: &MatchBindings,
    capture: &str,
    rule_index: usize,
) -> Result<Expression, CallbackError> {
    bindings
        .get(capture)
        .cloned()
        .ok_or_else(|| CallbackError::new(ScriptError(rule_index)))
}

/// Return the rule a spec describes, at position `rule_index`.
fn build_rule(spec: &Value, table: &SlotTable, rule_index: usize) -> RewriteRule {
    let pattern = build_pattern(&spec["pattern"], table, rule_index);
    let rewrite_spec = &spec["rewrite"];
    let mut rule = match rewrite_spec["kind"].as_str().expect("a rewrite kind") {
        "capture" => {
            let capture = rewrite_spec["capture"]
                .as_str()
                .expect("a capture")
                .to_owned();
            RewriteRule::new(pattern, move |bindings| {
                find_bound(bindings, &capture, rule_index)
            })
        }
        "literal" => {
            let replacement = Expression::from(decode_literal_value(table, &rewrite_spec["value"]));
            RewriteRule::new(pattern, move |_| Ok(replacement.clone()))
        }
        "negate_capture" => {
            let capture = rewrite_spec["capture"]
                .as_str()
                .expect("a capture")
                .to_owned();
            RewriteRule::new(pattern, move |bindings| {
                Ok(-find_bound(bindings, &capture, rule_index)?)
            })
        }
        "fail" => RewriteRule::new(pattern, move |_| {
            Err(CallbackError::new(ScriptError(rule_index)))
        }),
        other => panic!("unknown rewrite kind {other}"),
    };
    let guard_spec = &spec["guard"];
    if !guard_spec.is_null() {
        rule = match guard_spec["kind"].as_str().expect("a guard kind") {
            "always" => rule.with_guard(|_| Ok(true)),
            "never" => rule.with_guard(|_| Ok(false)),
            "fail" => rule.with_guard(move |_| Err(CallbackError::new(ScriptError(rule_index)))),
            "bound_is_literal" => {
                let capture = guard_spec["capture"]
                    .as_str()
                    .expect("a capture")
                    .to_owned();
                rule.with_guard(move |bindings| {
                    let bound = find_bound(bindings, &capture, rule_index)?;
                    Ok(matches!(bound.kind(), ExpressionKind::Literal(_)))
                })
            }
            other => panic!("unknown guard kind {other}"),
        };
    }
    match read_optional_str(spec, "name") {
        Some(name) => rule.with_name(name),
        None => rule,
    }
}

/// Check one match case against the oracle's result.
fn check_match_case(table: &SlotTable, case: &Value) -> Result<(), String> {
    let expression = table.decode(&case["tree"])?;
    let pattern = build_pattern(&case["pattern"], table, 0);
    let expected = &case["result"];
    match (match_pattern(&pattern, &expression), expected) {
        (Err(error), _) if expected.get("error").is_some() => {
            if error.inner().downcast_ref::<ScriptError>().is_some() {
                Ok(())
            } else {
                Err(format!("failed with a foreign error {error:?}"))
            }
        }
        (Ok(None), Value::Null) => Ok(()),
        (Ok(Some(bindings)), _) if expected.get("bindings").is_some() => {
            let expected_bindings = read_array(expected, "bindings");
            let names: Vec<&str> = bindings.names().collect();
            let expected_names: Vec<&str> = expected_bindings
                .iter()
                .map(|entry| entry[0].as_str().expect("a capture name"))
                .collect();
            if names != expected_names {
                return Err(format!("bound {names:?}, expected {expected_names:?}"));
            }
            for entry in expected_bindings {
                let name = entry[0].as_str().expect("a capture name");
                let bound = bindings.get(name).expect("a listed name is bound");
                compare_wire(
                    &table.encode(bound)?,
                    &entry[1],
                    &format!("bindings.{name}"),
                )?;
            }
            Ok(())
        }
        (outcome, _) => Err(format!("got {outcome:?}, expected {expected}")),
    }
}

/// Check one rewrite case against the oracle's result.
fn check_rewrite_case(table: &SlotTable, case: &Value) -> Result<(), String> {
    let expression = table.decode(&case["tree"])?;
    let rules: Vec<RewriteRule> = read_array(case, "rules")
        .iter()
        .enumerate()
        .map(|(index, spec)| build_rule(spec, table, index))
        .collect();
    let expected = &case["result"];
    match apply_rewrite_rules(&expression, &rules) {
        Ok(outcome) => {
            if expected.get("error").is_some() {
                return Err(format!("rewrote to {outcome:?}, expected {expected}"));
            }
            compare_wire(
                &table.encode(outcome.output())?,
                &expected["output"],
                "output",
            )?;
            let expected_changed = expected["changed"].as_bool().expect("a changed flag");
            if outcome.is_changed() != expected_changed {
                return Err(format!(
                    "changed is {}, expected {expected_changed}",
                    outcome.is_changed()
                ));
            }
            let fired: Vec<(usize, Option<&str>)> = outcome
                .fired()
                .iter()
                .map(|fired| (fired.rule_index(), fired.name()))
                .collect();
            let expected_fired: Vec<(usize, Option<&str>)> = read_array(expected, "fired")
                .iter()
                .map(|fired| {
                    let index = fired["rule_index"].as_u64().expect("a rule index");
                    (
                        usize::try_from(index).expect("a small rule index"),
                        read_optional_str(fired, "name"),
                    )
                })
                .collect();
            if fired == expected_fired {
                Ok(())
            } else {
                Err(format!("fired {fired:?}, expected {expected_fired:?}"))
            }
        }
        Err(error) => check_rewrite_error(&error, expected),
    }
}

/// Check a failed walk against the oracle's recorded failure.
fn check_rewrite_error(error: &RewriteError, expected: &Value) -> Result<(), String> {
    let expected_error = &expected["error"];
    let matches_expected = match (error, expected_error["kind"].as_str()) {
        (
            RewriteError::Callback {
                rule_index, source, ..
            },
            Some("callback"),
        ) => {
            let expected_index = expected_error["rule_index"].as_u64().expect("a rule index");
            let scripted = source.inner().downcast_ref::<ScriptError>();
            u64::try_from(*rule_index).ok() == Some(expected_index)
                && scripted.is_some_and(|scripted| scripted.0 == *rule_index)
        }
        (
            RewriteError::Rebuild(ExpressionBuildError::NonBooleanConditionLiteral { .. }),
            Some("non_boolean_condition_literal"),
        ) => true,
        _ => false,
    };
    if matches_expected {
        Ok(())
    } else {
        Err(format!("failed with {error:?}, expected {expected}"))
    }
}

/// Parse a golden document, check its size, replay every case, and fail
/// with the disagreements found.
fn replay_document(json: &str, corpus_path: Option<&str>) {
    let document: Value = serde_json::from_str(json).expect("golden data is valid JSON");
    let match_cases = read_array(&document, "match_cases");
    let rewrite_cases = read_array(&document, "rewrite_cases");
    assert!(
        match_cases.len() >= MIN_MATCH_CASES,
        "only {} golden match cases",
        match_cases.len()
    );
    assert!(
        rewrite_cases.len() >= MIN_REWRITE_CASES,
        "only {} golden rewrite cases",
        rewrite_cases.len()
    );

    let mut mismatches = Vec::new();
    for case in match_cases {
        let name = case["name"].as_str().expect("a case has a name");
        if let Err(message) = check_match_case(&SlotTable::new(), case) {
            mismatches.push(format!("match {name}: {message}"));
        }
    }
    for case in rewrite_cases {
        let name = case["name"].as_str().expect("a case has a name");
        if let Err(message) = check_rewrite_case(&SlotTable::new(), case) {
            mismatches.push(format!("rewrite {name}: {message}"));
        }
    }

    let location = corpus_path
        .map(|path| format!(" in {path}"))
        .unwrap_or_default();
    assert!(
        mismatches.is_empty(),
        "found {} mismatch(es){location}:\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
}

/// Test every committed match and rewrite case agrees with the Python
/// oracle.
#[test]
fn patterns_match_the_python_oracle() {
    replay_document(GOLDEN_JSON, None);
}

/// Test an expanded corpus, named by `FHY_PATTERN_CORPUS`, agrees with the
/// Python oracle.
#[test]
#[ignore = "requires an expanded corpus generated from the Python oracle"]
fn patterns_match_the_python_oracle_on_an_expanded_corpus() {
    let path = std::env::var("FHY_PATTERN_CORPUS")
        .expect("FHY_PATTERN_CORPUS names an expanded corpus file");
    let json = std::fs::read_to_string(&path).expect("the expanded corpus file is readable");

    replay_document(&json, Some(&path));
}
