//! Equivalence test replaying golden printed expressions from the Python
//! printer oracle against `fhy_core::symbolic::expression::format_expression`.
//!
//! The golden data is generated by
//! `rust/fhy-core/tests/golden/generate_pprint_cases.py` and committed at
//! `rust/fhy-core/tests/golden/pprint_cases.json`. Each case gives a tree by
//! its wire form, with identifiers written as `{"slot": name}`, and records
//! its text in both notations with name hints, and in both notations with
//! ids as segments: verbatim strings and `{"slot": name}` placeholders. The
//! document's `slots` block gives each slot's name hint.
//!
//! This test mints one identifier per slot and case, decodes the tree with
//! those identifiers (a decoded identifier keeps its payload's id), prints
//! it under all four option combinations, and expands each placeholder to
//! `name_hint::id` with the id of the identifier minted for that slot.
//! Public API only.

mod common;

use std::collections::BTreeMap;

use common::{read_expanded_corpus, replay_golden_document};
use fhy_core::identifier::Identifier;
use fhy_core::symbolic::expression::{
    Expression, FormatOptions, IdentifierStyle, Notation, format_expression,
};
use serde_json::{Map, Value, json};

const GOLDEN_JSON: &str = include_str!("golden/pprint_cases.json");

const MIN_CASES: usize = 150;

/// The recorded texts of a case: the key, the notation, and whether ids are
/// shown.
const RECORDED_TEXTS: [(&str, Notation, IdentifierStyle); 4] = [
    ("symbolic", Notation::Symbolic, IdentifierStyle::NameHint),
    (
        "functional",
        Notation::Functional,
        IdentifierStyle::NameHint,
    ),
    (
        "symbolic_with_ids",
        Notation::Symbolic,
        IdentifierStyle::NameHintWithId,
    ),
    (
        "functional_with_ids",
        Notation::Functional,
        IdentifierStyle::NameHintWithId,
    ),
];

/// Return the name hint of every slot, from the document's `slots` block.
fn read_slot_name_hints(json: &str) -> BTreeMap<String, String> {
    let document: Value = serde_json::from_str(json).expect("golden data is valid JSON");
    document["slots"]
        .as_object()
        .expect("a `slots` object")
        .iter()
        .map(|(slot, name_hint)| {
            (
                slot.clone(),
                name_hint.as_str().expect("a name hint").to_owned(),
            )
        })
        .collect()
}

/// The identifiers minted for one case's slots.
struct SlotTable {
    by_slot: BTreeMap<String, Identifier>,
}

impl SlotTable {
    /// Mint one identifier per slot, named by the slot's name hint.
    fn new(name_hints: &BTreeMap<String, String>) -> Self {
        let by_slot = name_hints
            .iter()
            .map(|(slot, name_hint)| (slot.clone(), Identifier::new(name_hint)))
            .collect();
        Self { by_slot }
    }

    /// Return the identifier minted for `slot`.
    fn find_identifier(&self, slot: &str) -> Result<&Identifier, String> {
        self.by_slot
            .get(slot)
            .ok_or_else(|| format!("unknown slot {slot}"))
    }

    /// Return `wire` with every slot placeholder replaced by its identifier.
    fn bind(&self, wire: &Value) -> Result<Value, String> {
        match wire {
            Value::Object(map) if map.len() == 1 && map.contains_key("slot") => {
                let slot = map["slot"].as_str().ok_or("a slot name is a string")?;
                let identifier = self.find_identifier(slot)?;
                Ok(json!({"id": identifier.id(), "name_hint": identifier.name_hint()}))
            }
            Value::Object(map) => map
                .iter()
                .map(|(key, value)| Ok((key.clone(), self.bind(value)?)))
                .collect::<Result<Map<String, Value>, String>>()
                .map(Value::Object),
            Value::Array(items) => items
                .iter()
                .map(|item| self.bind(item))
                .collect::<Result<Vec<Value>, String>>()
                .map(Value::Array),
            other => Ok(other.clone()),
        }
    }

    /// Decode a slot-form wire value.
    fn decode(&self, wire: &Value) -> Result<Expression, String> {
        serde_json::from_value(self.bind(wire)?).map_err(|error| format!("decode failed: {error}"))
    }

    /// Return the text a recorded value stands for: a string as it is, or a
    /// segment list with each slot placeholder written as `name_hint::id`
    /// of the identifier minted for the slot.
    fn expand(&self, recorded: &Value) -> Result<String, String> {
        if let Some(text) = recorded.as_str() {
            return Ok(text.to_owned());
        }
        let segments = recorded
            .as_array()
            .ok_or_else(|| format!("a text or a segment list, got {recorded}"))?;
        segments
            .iter()
            .map(|segment| match segment {
                Value::String(text) => Ok(text.clone()),
                Value::Object(map) => {
                    let slot = map["slot"].as_str().ok_or("a slot name is a string")?;
                    let identifier = self.find_identifier(slot)?;
                    Ok(format!("{}::{}", identifier.name_hint(), identifier.id()))
                }
                other => Err(format!("unknown segment {other}")),
            })
            .collect()
    }
}

/// Check one case's four recorded texts.
fn check_case(name_hints: &BTreeMap<String, String>, case: &Value) -> Result<(), String> {
    let table = SlotTable::new(name_hints);
    let expression = table.decode(&case["tree"])?;
    for (key, notation, identifiers) in RECORDED_TEXTS {
        let expected = table.expand(&case[key])?;
        let actual = format_expression(&expression, FormatOptions::new(notation, identifiers));
        if actual != expected {
            return Err(format!("{key}: {actual:?} vs expected {expected:?}"));
        }
    }
    Ok(())
}

/// Parse a golden document, check its size and slots, replay every case, and
/// fail with the disagreements found.
fn replay_document(json: &str, corpus_path: Option<&str>) {
    let name_hints = read_slot_name_hints(json);

    replay_golden_document(
        json,
        MIN_CASES,
        0,
        corpus_path,
        |_| {
            assert!(
                name_hints.len() >= 2,
                "only {} slots in the golden document",
                name_hints.len()
            );
        },
        |case, mismatches| {
            let name = case["name"].as_str().unwrap_or("<unnamed>");
            if let Err(mismatch) = check_case(&name_hints, case) {
                mismatches.push(format!("{name}: {mismatch}"));
            }
        },
    );
}

/// Test every committed printed-expression case agrees with the Python
/// oracle.
#[test]
fn printed_expressions_match_the_python_oracle() {
    replay_document(GOLDEN_JSON, None);
}

/// Test an expanded corpus, named by `FHY_PPRINT_CORPUS`, agrees with the
/// Python oracle.
#[test]
#[ignore = "requires an expanded corpus generated from the Python oracle"]
fn printed_expressions_match_the_python_oracle_on_an_expanded_corpus() {
    let (path, json) = read_expanded_corpus("FHY_PPRINT_CORPUS");

    replay_document(&json, Some(&path));
}
