//! Equivalence test replaying golden operation scripts from the Python
//! `provenance` and `diagnostic` oracles against `fhy_core::provenance` and
//! `fhy_core::diagnostic`.
//!
//! The golden data is generated by
//! `rust/fhy-core/tests/golden/generate_provenance_diagnostic_cases.py` and
//! committed at `rust/fhy-core/tests/golden/provenance_diagnostic_cases.json`.
//! This test only uses the public `fhy_core::identifier`,
//! `fhy_core::interned`, `fhy_core::provenance` and `fhy_core::diagnostic`
//! APIs.
//!
//! Provenance inputs and results are compared in their wire (dict) form and
//! by their rendered text. Note kinds are named by slot: a script's fresh slot
//! is bound to a freshly minted identifier the first time the script uses it,
//! and the four default slots are bound to the shipped kinds. No script
//! clears the `NoteKind` registry, so the replays need no lock.

mod common;

use std::collections::HashMap;
use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};

use fhy_core::diagnostic::{
    Diagnostic, DiagnosticLevel, Note, NoteKind, ValidationReport, get_other_note_kind,
    get_rationale_note_kind, get_remark_note_kind, get_suggestion_note_kind,
};
use fhy_core::identifier::Identifier;
use fhy_core::interned::{Canonical, Interned};
use fhy_core::provenance::{
    CallSiteProvenance, FileProvenance, FusedProvenance, NamedProvenance, Position, Provenance,
    ProvenanceError, Span,
};
use serde::Serialize;
use serde::de::DeserializeOwned;
use serde_json::{Value, json};

const GOLDEN_JSON: &str = include_str!("golden/provenance_diagnostic_cases.json");

const MIN_CASES: usize = 45;

const MIN_OPS: usize = 350;

/// A function returning one of the shipped note kinds.
type GetDefaultKind = fn() -> &'static Canonical<NoteKind>;

/// Each default slot paired with the function returning the shipped kind
/// bound to it, in the golden data's `default_note_kind_slots` order.
const NOTE_KIND_DEFAULTS: [(&str, GetDefaultKind); 4] = [
    ("rationale", get_rationale_note_kind),
    ("suggestion", get_suggestion_note_kind),
    ("remark", get_remark_note_kind),
    ("other", get_other_note_kind),
];

// =============================================================================
// Shared helpers
// =============================================================================

fn compute_hash<T: Hash>(value: &T) -> u64 {
    let mut hasher = DefaultHasher::new();
    value.hash(&mut hasher);
    hasher.finish()
}

/// Encode `value` to its JSON value.
fn encode<T: Serialize + ?Sized>(value: &T) -> Value {
    serde_json::to_value(value).expect("values encode to JSON")
}

/// Decode a golden input the oracle accepted.
///
/// # Panics
///
/// Panics if `value` does not decode, which means the Rust decode rejects a
/// payload the oracle built from.
fn decode_input<T: DeserializeOwned>(value: &Value, what: &str) -> T {
    serde_json::from_value(value.clone())
        .unwrap_or_else(|error| panic!("golden {what} {value} does not decode: {error}"))
}

/// Read an optional unsigned integer field.
fn read_optional_u64(value: &Value) -> Option<u64> {
    if value.is_null() {
        None
    } else {
        Some(value.as_u64().expect("a golden integer fits in u64"))
    }
}

/// Read an optional `[line, column]` pair as a position.
fn read_optional_position(value: &Value) -> Option<Position> {
    if value.is_null() {
        return None;
    }
    let pair = value.as_array().expect("a golden position is a pair");
    let line = pair[0].as_u64().expect("a golden line fits in u64");
    let column = pair[1].as_u64().expect("a golden column fits in u64");
    Some(Position::try_new(line, column).expect("a golden position is valid"))
}

/// Read an optional string field.
fn read_optional_str(value: &Value) -> Option<&str> {
    value.as_str()
}

/// Compare `actual` with `expected`, recording a mismatch labelled `what`.
fn check_equal<T: PartialEq + std::fmt::Debug>(
    location: &str,
    what: &str,
    actual: &T,
    expected: &T,
    mismatches: &mut Vec<String>,
) {
    if actual != expected {
        mismatches.push(format!(
            "{location}: {what} is {actual:?}, expected {expected:?}"
        ));
    }
}

/// Compare a provenance-family value's wire form and text with the golden
/// `expected` value and `str`.
fn check_value_and_text<T: Serialize + ToString>(
    location: &str,
    actual: &T,
    expected: &Value,
    mismatches: &mut Vec<String>,
) {
    check_equal(
        location,
        "encoded value",
        &encode(actual),
        &expected["value"],
        mismatches,
    );
    check_equal(
        location,
        "text",
        &actual.to_string(),
        &expected["str"]
            .as_str()
            .expect("golden text is a string")
            .to_owned(),
        mismatches,
    );
}

// =============================================================================
// Provenance replay
// =============================================================================

/// Return the Rust error the oracle's constructor error for `op` maps to.
///
/// The oracle raises `ValueError` with a message naming the offending
/// field; the Rust constructors return a variant carrying the same values.
///
/// # Panics
///
/// Panics on a message this table does not map, so a new oracle error cannot
/// pass unnoticed.
fn map_constructor_error(op: &Value, message: &str) -> ProvenanceError {
    if message.starts_with("\"line\" must be >= 1") {
        ProvenanceError::ZeroLine
    } else if message.starts_with("\"column\" must be >= 1") {
        ProvenanceError::ZeroColumn
    } else if message.starts_with("\"end_offset\" must be >= \"start_offset\"") {
        ProvenanceError::EndOffsetBeforeStartOffset {
            start_offset: op["start_offset"].as_u64().expect("offset"),
            end_offset: op["end_offset"].as_u64().expect("offset"),
        }
    } else if message.starts_with("\"end_position\" must be >= \"start_position\"") {
        ProvenanceError::EndPositionBeforeStartPosition {
            start_position: read_optional_position(&op["start_position"]).expect("position"),
            end_position: read_optional_position(&op["end_position"]).expect("position"),
        }
    } else if message == "\"name\" must be non-empty" {
        ProvenanceError::EmptyName
    } else {
        panic!("no Rust error is mapped for the oracle error {message:?}")
    }
}

/// Compare a constructor's result with the golden expectation: the encoded
/// value and text on success, or the mapped error variant.
fn check_constructed<T: Serialize + ToString + std::fmt::Debug>(
    location: &str,
    op: &Value,
    result: Result<T, ProvenanceError>,
    mismatches: &mut Vec<String>,
) {
    let expected = &op["expected"];
    match (result, expected.get("error")) {
        (Ok(value), None) => check_value_and_text(location, &value, expected, mismatches),
        (Err(error), Some(expected_error)) => {
            let message = expected_error["message"].as_str().expect("error message");
            check_equal(
                location,
                "error",
                &error,
                &map_constructor_error(op, message),
                mismatches,
            );
        }
        (Ok(value), Some(expected_error)) => mismatches.push(format!(
            "{location}: built {value:?}, expected error {expected_error}"
        )),
        (Err(error), None) => mismatches.push(format!(
            "{location}: got error {error:?}, expected {expected}"
        )),
    }
}

fn replay_position_new(location: &str, op: &Value, mismatches: &mut Vec<String>) {
    let line = op["line"].as_u64().expect("golden line fits in u64");
    let column = op["column"].as_u64().expect("golden column fits in u64");

    let result = Position::try_new(line, column);

    check_constructed(location, op, result, mismatches);
}

fn replay_span_new(location: &str, op: &Value, mismatches: &mut Vec<String>) {
    let result = Span::try_new(
        read_optional_u64(&op["start_offset"]),
        read_optional_u64(&op["end_offset"]),
        read_optional_position(&op["start_position"]),
        read_optional_position(&op["end_position"]),
    );

    if let Ok(span) = &result {
        check_equal(
            location,
            "is_unknown",
            &Some(span.is_unknown()),
            &op["expected"]["is_unknown"].as_bool(),
            mismatches,
        );
    }
    check_constructed(location, op, result, mismatches);
}

fn replay_file_new(location: &str, op: &Value, mismatches: &mut Vec<String>) {
    let path = op["file_path"].as_str().expect("golden path is a string");
    let span: Option<Span> = decode_input(&op["span"], "span");

    let provenance = Provenance::File(FileProvenance::new(path, span));

    check_value_and_text(location, &provenance, &op["expected"], mismatches);
}

fn replay_named_new(location: &str, op: &Value, mismatches: &mut Vec<String>) {
    let name = op["name"].as_str().expect("golden name is a string");
    let child: Provenance = decode_input(&op["child"], "child");

    let result = NamedProvenance::try_new(name, child).map(Provenance::Named);

    check_constructed(location, op, result, mismatches);
}

fn replay_call_site_new(location: &str, op: &Value, mismatches: &mut Vec<String>) {
    let called: Provenance = decode_input(&op["callee"], "callee");
    let call_site: Provenance = decode_input(&op["caller"], "caller");

    let provenance = Provenance::CallSite(CallSiteProvenance::new(called, call_site));

    check_value_and_text(location, &provenance, &op["expected"], mismatches);
}

fn replay_fused_new(location: &str, op: &Value, mismatches: &mut Vec<String>) {
    let sources: Vec<Provenance> = decode_input(&op["sources"], "sources");
    let metadata = read_optional_str(&op["metadata"]).map(str::to_owned);

    let provenance = Provenance::Fused(FusedProvenance::new(sources, metadata));

    check_value_and_text(location, &provenance, &op["expected"], mismatches);
}

fn replay_fuse(location: &str, op: &Value, mismatches: &mut Vec<String>) {
    let inputs: Vec<Provenance> = decode_input(&op["inputs"], "inputs");
    let metadata = read_optional_str(&op["metadata"]);

    let fused = Provenance::fuse(inputs, metadata);

    check_value_and_text(location, &fused, &op["expected"], mismatches);
}

fn replay_equals(location: &str, op: &Value, mismatches: &mut Vec<String>) {
    let left: Provenance = decode_input(&op["left"], "left");
    let right: Provenance = decode_input(&op["right"], "right");
    let expected = op["expected"]["result"]
        .as_bool()
        .expect("equals expectation is a boolean");

    let actual = left == right;

    check_equal(location, "equality", &actual, &expected, mismatches);
    if actual && compute_hash(&left) != compute_hash(&right) {
        mismatches.push(format!("{location}: equal provenances hash differently"));
    }
}

/// Decode `payload` as a `T` and compare the outcome with the golden
/// expectation.
///
/// The oracle records a rejected payload with its Python error class; the
/// two runtimes word and classify decode errors differently, so only the
/// rejection itself is compared.
fn check_decode<T: DeserializeOwned + Serialize + ToString>(
    location: &str,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let expected = &op["expected"];
    match (
        serde_json::from_value::<T>(op["payload"].clone()),
        expected.get("error"),
    ) {
        (Ok(value), None) => check_value_and_text(location, &value, expected, mismatches),
        (Err(_), Some(_)) => {}
        (Ok(value), Some(expected_error)) => mismatches.push(format!(
            "{location}: decoded {}, expected error {expected_error}",
            encode(&value)
        )),
        (Err(error), None) => mismatches.push(format!(
            "{location}: got decode error {error}, expected {expected}"
        )),
    }
}

fn replay_decode(location: &str, op: &Value, mismatches: &mut Vec<String>) {
    match op["family"].as_str().expect("decode family is a string") {
        "position" => check_decode::<Position>(location, op, mismatches),
        "span" => check_decode::<Span>(location, op, mismatches),
        "provenance" => check_decode::<Provenance>(location, op, mismatches),
        family => panic!("{location}: unknown decode family {family:?}"),
    }
}

fn replay_provenance_op(location: &str, op: &Value, mismatches: &mut Vec<String>) {
    match op["op"].as_str().expect("op name is a string") {
        "position_new" => replay_position_new(location, op, mismatches),
        "span_new" => replay_span_new(location, op, mismatches),
        "file_new" => replay_file_new(location, op, mismatches),
        "named_new" => replay_named_new(location, op, mismatches),
        "call_site_new" => replay_call_site_new(location, op, mismatches),
        "fused_new" => replay_fused_new(location, op, mismatches),
        "fuse" => replay_fuse(location, op, mismatches),
        "equals" => replay_equals(location, op, mismatches),
        "decode" => replay_decode(location, op, mismatches),
        name => panic!("{location}: unknown provenance op {name:?}"),
    }
}

// =============================================================================
// Diagnostic replay
// =============================================================================

/// Per-script table binding note-kind slots to identifiers.
///
/// The default slots are bound to the shipped kinds' names; a fresh slot is
/// bound to an identifier minted the first time the script uses it.
struct SlotTable {
    by_slot: HashMap<String, Identifier>,
    by_id: HashMap<u64, String>,
}

impl SlotTable {
    /// Return a table with only the default slots bound.
    fn create_with_defaults() -> Self {
        let mut table = Self {
            by_slot: HashMap::new(),
            by_id: HashMap::new(),
        };
        for (slot, get_kind) in NOTE_KIND_DEFAULTS {
            table.bind(slot, get_kind().name().clone());
        }
        table
    }

    fn bind(&mut self, slot: &str, identifier: Identifier) {
        self.by_id.insert(identifier.id(), slot.to_owned());
        self.by_slot.insert(slot.to_owned(), identifier);
    }

    /// Return `slot`'s identifier, minting a fresh one on first use.
    fn resolve_identifier(&mut self, slot: &str) -> Identifier {
        if let Some(identifier) = self.by_slot.get(slot) {
            return identifier.clone();
        }
        let identifier = Identifier::new(slot);
        self.bind(slot, identifier.clone());
        identifier
    }

    /// Return the canonical kind registered under `slot`'s identifier.
    ///
    /// # Panics
    ///
    /// Panics if no kind is registered under it, which would mean the golden
    /// data uses a slot the oracle never registered.
    fn resolve_kind(&mut self, slot: &str) -> Canonical<NoteKind> {
        let identifier = self.resolve_identifier(slot);
        NoteKind::intern_registry()
            .get(&identifier)
            .unwrap_or_else(|| panic!("note-kind slot {slot:?} is not registered"))
    }

    /// Return the slot bound to `id`.
    ///
    /// # Panics
    ///
    /// Panics if `id` was never bound.
    fn find_slot(&self, id: u64) -> &str {
        self.by_id
            .get(&id)
            .unwrap_or_else(|| panic!("identifier id {id} is not bound to any slot"))
    }

    /// Return an encoded note with its kind's id replaced by the id's slot.
    fn normalize_note(&self, encoded: &Value) -> Value {
        let mut normalized = encoded.clone();
        let id = encoded["kind"]["name"]["id"]
            .as_u64()
            .expect("an encoded note kind has a numeric id");
        normalized["kind"]["name"]["id"] = json!(self.find_slot(id));
        normalized
    }

    /// Return a golden note payload with a slot-valued kind id replaced by
    /// the slot's id; any other id is kept as written.
    fn denormalize_note(&mut self, normalized: &Value) -> Value {
        let mut payload = normalized.clone();
        if let Some(slot) = normalized["kind"]["name"]["id"].as_str() {
            let id = self.resolve_identifier(slot).id();
            payload["kind"]["name"]["id"] = json!(id);
        }
        payload
    }
}

fn replay_note_kind_new(
    slots: &mut SlotTable,
    location: &str,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"].as_str().expect("slot is a string");
    let description = op["description"].as_str().expect("description is a string");
    let expected = &op["expected"];

    let outcome = NoteKind::new(slots.resolve_identifier(slot), description);

    check_equal(
        location,
        "registered",
        &Some(outcome.is_registered()),
        &expected["registered"].as_bool(),
        mismatches,
    );
    check_equal(
        location,
        "canonical description",
        &Some(outcome.canonical().description()),
        &expected["canonical_description"].as_str(),
        mismatches,
    );
}

fn replay_note_new(
    slots: &mut SlotTable,
    location: &str,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let message = op["message"].as_str().expect("message is a string");
    let kind = slots.resolve_kind(op["kind_slot"].as_str().expect("kind slot is a string"));
    let expected = &op["expected"];

    let note = Note::new(message, kind);

    check_equal(
        location,
        "encoded note",
        &slots.normalize_note(&encode(&note)),
        &expected["value"],
        mismatches,
    );
    check_equal(
        location,
        "text",
        &Some(note.to_string()),
        &expected["str"].as_str().map(str::to_owned),
        mismatches,
    );
}

fn replay_note_decode(
    slots: &mut SlotTable,
    location: &str,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let payload = slots.denormalize_note(&op["payload"]);
    let expected = &op["expected"];

    let result = serde_json::from_value::<Note>(payload);

    match (result, expected.get("error")) {
        (Ok(note), None) => {
            check_equal(
                location,
                "encoded note",
                &slots.normalize_note(&encode(&note)),
                &expected["value"],
                mismatches,
            );
            check_equal(
                location,
                "text",
                &Some(note.to_string()),
                &expected["str"].as_str().map(str::to_owned),
                mismatches,
            );
            check_equal(
                location,
                "kind slot",
                &Some(slots.find_slot(note.kind().name().id())),
                &expected["kind_slot"].as_str(),
                mismatches,
            );
            let is_canonical =
                NoteKind::intern_registry().get(note.kind().name()).as_ref() == Some(note.kind());
            check_equal(
                location,
                "kind is canonical",
                &Some(is_canonical),
                &expected["kind_is_canonical"].as_bool(),
                mismatches,
            );
        }
        (Err(_), Some(_)) => {}
        (Ok(note), Some(expected_error)) => mismatches.push(format!(
            "{location}: decoded {note:?}, expected error {expected_error}"
        )),
        (Err(error), None) => mismatches.push(format!(
            "{location}: got decode error {error}, expected {expected}"
        )),
    }
}

/// Read a golden level name.
fn read_level(value: &Value) -> DiagnosticLevel {
    match value.as_str().expect("a level is a string") {
        "error" => DiagnosticLevel::Error,
        "warning" => DiagnosticLevel::Warning,
        "info" => DiagnosticLevel::Info,
        level => panic!("unknown golden level {level:?}"),
    }
}

/// Build the diagnostic a golden spec describes.
fn build_diagnostic(slots: &mut SlotTable, spec: &Value) -> Diagnostic {
    let kind = slots.resolve_kind(spec["kind_slot"].as_str().expect("kind slot"));
    Diagnostic::new(
        read_level(&spec["level"]),
        Note::new(spec["message"].as_str().expect("message"), kind),
        spec["source"].as_str().expect("source"),
        read_optional_str(&spec["detail"]).map(str::to_owned),
    )
}

/// Return the positions in `report` of the diagnostics `selected` yields,
/// found by address so equal diagnostics stay distinguishable.
fn find_indices<'a>(
    report: &ValidationReport,
    selected: impl Iterator<Item = &'a Diagnostic>,
) -> Vec<u64> {
    selected
        .map(|diagnostic| {
            let index = report
                .diagnostics()
                .iter()
                .position(|candidate| std::ptr::eq(candidate, diagnostic))
                .expect("a filtered diagnostic is one of the report's own");
            u64::try_from(index).expect("indices fit in u64")
        })
        .collect()
}

/// Read a golden list of indices.
fn read_indices(value: &Value) -> Vec<u64> {
    value
        .as_array()
        .expect("indices are a list")
        .iter()
        .map(|index| index.as_u64().expect("an index is an integer"))
        .collect()
}

fn replay_report(slots: &mut SlotTable, location: &str, op: &Value, mismatches: &mut Vec<String>) {
    let diagnostics: Vec<Diagnostic> = op["diagnostics"]
        .as_array()
        .expect("diagnostics are a list")
        .iter()
        .map(|spec| build_diagnostic(slots, spec))
        .collect();
    let expected = &op["expected"];

    let report = ValidationReport::new(diagnostics, Vec::new());

    check_equal(
        location,
        "format",
        &Some(report.format()),
        &expected["format"].as_str().map(str::to_owned),
        mismatches,
    );
    check_equal(
        location,
        "has_errors",
        &Some(report.has_errors()),
        &expected["has_errors"].as_bool(),
        mismatches,
    );
    for (name, actual) in [
        ("errors", find_indices(&report, report.errors())),
        ("warnings", find_indices(&report, report.warnings())),
        ("infos", find_indices(&report, report.infos())),
    ] {
        check_equal(
            location,
            name,
            &actual,
            &read_indices(&expected[name]),
            mismatches,
        );
    }
    let failure_text = report.into_result().err().map(|error| error.to_string());
    check_equal(
        location,
        "failure text",
        &failure_text,
        &expected["failure_text"].as_str().map(str::to_owned),
        mismatches,
    );
}

fn replay_diagnostic_op(
    slots: &mut SlotTable,
    location: &str,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    match op["op"].as_str().expect("op name is a string") {
        "note_kind_new" => replay_note_kind_new(slots, location, op, mismatches),
        "note_new" => replay_note_new(slots, location, op, mismatches),
        "note_decode" => replay_note_decode(slots, location, op, mismatches),
        "report" => replay_report(slots, location, op, mismatches),
        name => panic!("{location}: unknown diagnostic op {name:?}"),
    }
}

// =============================================================================
// Case replay
// =============================================================================

fn replay_case(case: &Value, mismatches: &mut Vec<String>) {
    let name = case["name"].as_str().expect("case has a name");
    let ops = case["ops"].as_array().expect("case has ops");
    match case["type"].as_str().expect("case has a type") {
        "provenance" => {
            for (index, op) in ops.iter().enumerate() {
                replay_provenance_op(&format!("case {name} op {index}"), op, mismatches);
            }
        }
        "diagnostic" => {
            let mut slots = SlotTable::create_with_defaults();
            for (index, op) in ops.iter().enumerate() {
                replay_diagnostic_op(
                    &mut slots,
                    &format!("case {name} op {index}"),
                    op,
                    mismatches,
                );
            }
        }
        kind => panic!("case {name}: unknown case type {kind:?}"),
    }
}

/// Assert the golden data's default note-kind slots are the slots this
/// replay binds, in order.
fn assert_default_slots_match_rust(document: &Value) {
    let actual: Vec<&str> = document["default_note_kind_slots"]
        .as_array()
        .expect("golden data has `default_note_kind_slots`")
        .iter()
        .map(|slot| slot.as_str().expect("a slot is a string"))
        .collect();
    let expected: Vec<&str> = NOTE_KIND_DEFAULTS.iter().map(|(slot, _)| *slot).collect();
    assert_eq!(
        actual, expected,
        "Rust's default note-kind slots have drifted from the golden data"
    );
}

/// Test the Rust provenance and diagnostic types reproduce every
/// observation the Python oracle recorded for the golden scripts.
#[test]
fn provenance_and_diagnostic_match_the_python_oracle() {
    common::replay_golden_document(
        GOLDEN_JSON,
        MIN_CASES,
        MIN_OPS,
        None,
        assert_default_slots_match_rust,
        replay_case,
    );
}

/// Test the Rust provenance and diagnostic types reproduce every
/// observation the Python oracle recorded for an expanded corpus, read from
/// the file named by `FHY_PROVENANCE_DIAGNOSTIC_CORPUS`.
#[test]
#[ignore = "requires an expanded corpus generated from the Python oracle"]
fn provenance_and_diagnostic_match_the_python_oracle_on_an_expanded_corpus() {
    let (path, json) = common::read_expanded_corpus("FHY_PROVENANCE_DIAGNOSTIC_CORPUS");

    common::replay_golden_document(
        &json,
        MIN_CASES,
        MIN_OPS,
        Some(&path),
        assert_default_slots_match_rust,
        replay_case,
    );
}
