//! Equivalence test replaying golden operation scripts from the Python
//! `OpAttribute`/`ValueDomain` oracle against `fhy_core::op_attribute` and
//! `fhy_core::value_domain`.
//!
//! The golden data is generated by
//! `rust/fhy-core/tests/golden/generate_tag_type_cases.py` and committed at
//! `rust/fhy-core/tests/golden/tag_type_cases.json`. This test only uses the public
//! `fhy_core::identifier`, `fhy_core::interned`, `fhy_core::op_attribute` and
//! `fhy_core::value_domain` APIs.
//!
//! Every script in the golden data runs against the process-global
//! `OpAttribute` and `ValueDomain` registries, because their constructors
//! have no other registry to intern into. Each `#[test]` function below
//! therefore replays its whole corpus as one sequential loop, and both hold
//! one shared `static` `Mutex<()>` for their whole duration: cargo runs
//! `#[test]` functions on separate threads, so without it the default and
//! the ignored expanded-corpus test would race a `clear()` in one script
//! against an intern in the other under `--include-ignored`.

mod common;

use std::collections::HashMap;
use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};
use std::sync::{Mutex, MutexGuard, PoisonError};

use fhy_core::identifier::Identifier;
use fhy_core::interned::{Canonical, InternOutcome, Interned};
use fhy_core::op_attribute::{
    OpAttribute, get_associative, get_commutative, get_elementwise, get_pure,
};
use fhy_core::value_domain::{ValueDomain, get_address_domain, get_data_domain};
use serde::de::DeserializeOwned;
use serde_json::{Map, Value, json};

const GOLDEN_JSON: &str = include_str!("golden/tag_type_cases.json");

/// Minimum number of golden cases this corpus must carry.
const MIN_CASES: usize = 100;

/// Minimum total number of golden ops, across every case, this corpus must
/// carry.
const MIN_OPS: usize = 1000;

/// Distance above a freshly minted id at which `bind_ahead` binds a slot, and
/// between the ids of successive ahead slots in one script, mirroring the
/// generator's `_AHEAD_ID_SPACING`.
const AHEAD_ID_SPACING: u64 = 1_000_000;

/// Per-script table binding the identifier slots named in the golden data to
/// the `Identifier` minted for them in this process.
///
/// A slot's identifier is minted once, the first time the script refers to
/// it (mirroring the generator), and reused for the rest of the script. The
/// reverse lookup turns a registry's identifier back into the slot name the
/// golden data expects, so an encoded value or a domain's parent can be
/// compared in normalized (slot) form.
///
/// A `bind_ahead` op instead binds a slot to an id ahead of the counter and
/// leaves it unrestored until an op needs the slot's `Identifier`, as the
/// generator does, so an `is_counter_past` op sees only what a decode did.
#[derive(Default)]
struct SlotTable {
    by_slot: HashMap<String, Identifier>,
    by_id: HashMap<u64, String>,
    ahead: HashMap<String, u64>,
    ahead_count: u64,
}

impl SlotTable {
    /// Bind the fresh `slot` to an id ahead of the counter, unrestored.
    ///
    /// # Panics
    ///
    /// Panics if `slot` is already bound.
    fn bind_ahead(&mut self, slot: &str) {
        assert!(
            !self.by_slot.contains_key(slot) && !self.ahead.contains_key(slot),
            "slot {slot:?} is already bound"
        );
        self.ahead_count += 1;
        let id = Identifier::new(slot).id() + AHEAD_ID_SPACING * self.ahead_count;
        self.by_id.insert(id, slot.to_string());
        self.ahead.insert(slot.to_string(), id);
    }

    /// Return `slot`'s id, minting an identifier on first use but leaving an
    /// ahead slot's id unrestored.
    fn resolve_id(&mut self, slot: &str) -> u64 {
        match self.ahead.get(slot) {
            Some(&id) => id,
            None => self.resolve_identifier(slot).id(),
        }
    }

    fn bind_slot(&mut self, slot: &str, identifier: Identifier) {
        self.by_id.insert(identifier.id(), slot.to_string());
        self.by_slot.insert(slot.to_string(), identifier);
    }

    /// Return `slot`'s identifier, minting a fresh one on first use.
    fn resolve_identifier(&mut self, slot: &str) -> Identifier {
        if let Some(identifier) = self.by_slot.get(slot) {
            return identifier.clone();
        }
        let identifier = match self.ahead.remove(slot) {
            Some(id) => Identifier::restore(id, slot.to_string()),
            None => Identifier::new(slot),
        };
        self.bind_slot(slot, identifier.clone());
        identifier
    }

    /// Return the slot name bound to `id`.
    ///
    /// # Panics
    ///
    /// Panics if `id` was never bound, which would mean the golden data
    /// refers to an identifier this replay never minted or seeded.
    fn find_slot_for_id(&self, id: u64) -> &str {
        self.by_id.get(&id).map_or_else(
            || panic!("identifier id {id} is not bound to any slot"),
            String::as_str,
        )
    }
}

/// Return `value`'s hash under the default hasher.
fn compute_hash<T: Hash>(value: &T) -> u64 {
    let mut hasher = DefaultHasher::new();
    value.hash(&mut hasher);
    hasher.finish()
}

fn create_op_attribute_slots() -> SlotTable {
    let mut slots = SlotTable::default();
    slots.bind_slot("commutative", get_commutative().name().clone());
    slots.bind_slot("associative", get_associative().name().clone());
    slots.bind_slot("pure", get_pure().name().clone());
    slots.bind_slot("elementwise", get_elementwise().name().clone());
    slots
}

fn create_value_domain_slots() -> SlotTable {
    let mut slots = SlotTable::default();
    slots.bind_slot("data", get_data_domain().name().clone());
    slots.bind_slot("address", get_address_domain().name().clone());
    slots
}

// =============================================================================
// Normalization: a real encoded value has a numeric `id`; a normalized one
// (as recorded in the golden data) has the slot name that id belongs to.
// =============================================================================

fn denormalize_identifier(value: &Value, slots: &mut SlotTable) -> Value {
    let slot = value["id"]
        .as_str()
        .expect("a normalized identifier's id is a slot name");
    let name_hint = value["name_hint"]
        .as_str()
        .expect("a normalized identifier has a name_hint");
    json!({"id": slots.resolve_id(slot), "name_hint": name_hint})
}

fn denormalize_op_attribute(value: &Value, slots: &mut SlotTable) -> Value {
    json!({
        "name": denormalize_identifier(&value["name"], slots),
        "description": value["description"],
    })
}

fn denormalize_value_domain(value: &Value, slots: &mut SlotTable) -> Value {
    let parent = &value["parent"];
    let parent_value = if parent.is_null() {
        Value::Null
    } else {
        denormalize_value_domain(parent, slots)
    };
    json!({
        "name": denormalize_identifier(&value["name"], slots),
        "description": value["description"],
        "parent": parent_value,
    })
}

/// Return an encoded identifier with its id replaced by the id's slot, as the
/// generator's `_normalize_identifier_dict` does. Every other field is kept,
/// so a field the Rust encoding adds or drops still differs from the golden
/// encoding.
fn normalize_encoded_identifier(encoded: &Value, slots: &SlotTable) -> Value {
    let mut normalized = encoded.clone();
    if let Some(id) = encoded["id"].as_u64() {
        normalized["id"] = Value::from(slots.find_slot_for_id(id));
    }
    normalized
}

/// Return an encoded attribute or domain with each identifier's id replaced
/// by its slot, recursing into a domain's parent, as the generator's
/// `_normalize_attribute_dict` and `_normalize_domain_dict` do. Every other
/// field is kept.
fn normalize_encoded_tag(encoded: &Value, slots: &SlotTable) -> Value {
    let mut normalized = encoded.clone();
    if let Some(name) = encoded.get("name") {
        normalized["name"] = normalize_encoded_identifier(name, slots);
    }
    if let Some(parent) = encoded.get("parent").filter(|parent| !parent.is_null()) {
        normalized["parent"] = normalize_encoded_tag(parent, slots);
    }
    normalized
}

/// Return a real (denormalized) payload with one structural defect applied,
/// mirroring the generator's `_apply_defect`.
///
/// `defect["path"]` names the field to damage, as the keys leading to it from
/// the payload's root. `remove` deletes that field, `set` replaces or adds it
/// with the literal `defect["value"]`, `wrap` nests it one level deeper under
/// `defect["key"]` (an empty path wraps the whole payload), and `lift`
/// replaces it with its own `defect["key"]` member.
///
/// # Panics
///
/// Panics if the defect is malformed or its path does not lead to a field of
/// the payload, which would mean the golden data and this replay disagree
/// about the defect format.
fn apply_defect(mut payload: Value, defect: &Value) -> Value {
    let kind = defect["kind"].as_str().expect("a defect has a kind");
    let path: Vec<&str> = defect["path"]
        .as_array()
        .expect("a defect has a path")
        .iter()
        .map(|key| key.as_str().expect("a defect path holds field names"))
        .collect();
    let wrap_key = || {
        defect["key"]
            .as_str()
            .expect("a wrap or lift defect has a key")
    };

    let Some((field_name, container_path)) = path.split_last() else {
        assert_eq!(kind, "wrap", "only a wrap defect may have an empty path");
        let mut wrapper = Map::new();
        wrapper.insert(wrap_key().to_string(), payload);
        return Value::Object(wrapper);
    };
    let mut container = &mut payload;
    for key in container_path {
        container = &mut container[*key];
    }
    let fields = container
        .as_object_mut()
        .expect("a defect path leads through objects");
    let field_name = (*field_name).to_string();
    match kind {
        "remove" => {
            fields
                .remove(&field_name)
                .expect("a remove defect names a present field");
        }
        "set" => {
            fields.insert(field_name, defect["value"].clone());
        }
        "wrap" => {
            let inner = fields
                .remove(&field_name)
                .expect("a wrap defect names a present field");
            let mut wrapper = Map::new();
            wrapper.insert(wrap_key().to_string(), inner);
            fields.insert(field_name, Value::Object(wrapper));
        }
        "lift" => {
            let lifted = fields[&field_name][wrap_key()].clone();
            assert!(!lifted.is_null(), "a lift defect names a present member");
            fields.insert(field_name, lifted);
        }
        other => panic!("unknown defect kind {other:?}"),
    }
    payload
}

/// Denormalize a decode op's payload and apply its defect, if it has one.
fn build_decode_payload(op: &Value, denormalize: impl FnOnce(&Value) -> Value) -> Value {
    let real_payload = denormalize(&op["payload"]);
    match op.get("defect") {
        Some(defect) => apply_defect(real_payload, defect),
        None => real_payload,
    }
}

/// Text both runtimes put in the error for a payload that conflicts with the
/// canonical instance for its key.
const CANONICAL_CONFLICT_MESSAGE: &str = "conflicts with the canonical instance";

/// Decode `payload` as a canonical handle and compare the outcome's kind
/// with the golden expectation.
///
/// Returns the handle when both sides decoded it. The oracle records a
/// rejected payload as `{"error": <Python error class name>, "conflict":
/// <bool>}`, where `conflict` says whether it rejected the payload as a
/// conflict with the canonical instance rather than for its structure. The
/// Rust decode must reject the same payloads for the same kind of reason;
/// the two runtimes word structural errors differently, so only the kind is
/// compared. Any disagreement, in either direction, becomes a mismatch and
/// returns `None`, as does an agreed rejection.
fn decode_or_check_rejection<T>(
    payload: Value,
    name: &str,
    index: usize,
    expected: &Value,
    mismatches: &mut Vec<String>,
) -> Option<Canonical<T>>
where
    Canonical<T>: DeserializeOwned,
{
    let expected_error = expected["error"].as_str();
    match (
        serde_json::from_value::<Canonical<T>>(payload),
        expected_error,
    ) {
        (Ok(restored), None) => Some(restored),
        (Err(error), Some(_))
            if error.to_string().contains(CANONICAL_CONFLICT_MESSAGE)
                == expected["conflict"]
                    .as_bool()
                    .expect("a decode rejection records whether it is a conflict") =>
        {
            None
        }
        (Ok(_), Some(expected_error)) => {
            mismatches.push(format!(
                "case {name} op {index}: expected error {expected_error:?}, got a decoded value"
            ));
            None
        }
        (Err(error), _) => {
            mismatches.push(format!(
                "case {name} op {index}: expected {expected}, got error {error}"
            ));
            None
        }
    }
}

/// Check whether the id counter has passed a slot's id against the golden
/// expectation, minting one identifier to find out.
fn check_is_counter_past(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"].as_str().expect("is_counter_past op has a slot");
    let id = slots.resolve_id(slot);
    let expected = op["expected"]["result"]
        .as_bool()
        .expect("is_counter_past expectation has a boolean `result`");

    let actual = Identifier::new("counter-probe").id() > id;

    if actual != expected {
        mismatches.push(format!(
            "case {name} op {index}: expected the counter past {slot:?} to be {expected}, \
             got {actual}"
        ));
    }
}

// =============================================================================
// `op_attribute` op replay
// =============================================================================

fn check_new_attribute(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"].as_str().expect("new op has a slot");
    let description = op["description"]
        .as_str()
        .expect("new op has a description");
    let identifier = slots.resolve_identifier(slot);

    let outcome = OpAttribute::new(identifier, description);
    let expected = &op["expected"];
    let expected_registered = expected["registered"]
        .as_bool()
        .expect("new expectation has `registered`");
    let expected_description = expected["canonical_description"]
        .as_str()
        .expect("new expectation has `canonical_description`");

    let actual_registered = outcome.is_registered();
    let canonical = outcome.into_canonical();

    if actual_registered != expected_registered || canonical.description() != expected_description {
        mismatches.push(format!(
            "case {name} op {index}: expected registered={expected_registered} \
             canonical_description={expected_description:?}, got registered={actual_registered} \
             canonical_description={:?}",
            canonical.description()
        ));
    }
}

fn check_get_attribute(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"].as_str().expect("get op has a slot");
    let identifier = slots.resolve_identifier(slot);
    let expected_description = op["expected"]["canonical_description"].as_str();

    let actual = OpAttribute::intern_registry().get(&identifier);
    let actual_description = actual.as_ref().map(|canonical| canonical.description());

    if actual_description != expected_description {
        mismatches.push(format!(
            "case {name} op {index}: expected canonical_description={expected_description:?}, \
             got {actual_description:?}"
        ));
    }
}

fn check_require_attribute(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"].as_str().expect("require op has a slot");
    let identifier = slots.resolve_identifier(slot);
    let expected = &op["expected"];

    match OpAttribute::intern_registry().require(&identifier) {
        Ok(canonical) => {
            let expected_description = expected["canonical_description"].as_str();
            if Some(canonical.description()) != expected_description {
                mismatches.push(format!(
                    "case {name} op {index}: expected canonical_description={expected_description:?}, \
                     got {:?}",
                    canonical.description()
                ));
            }
        }
        Err(error) => {
            let expected_error = expected["error"].as_str();
            if expected_error != Some("KeyError") {
                mismatches.push(format!(
                    "case {name} op {index}: expected {expected:?}, got error {error}"
                ));
            }
        }
    }
}

fn check_encode_attribute(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"].as_str().expect("encode op has a slot");
    let identifier = slots.resolve_identifier(slot);
    let canonical = OpAttribute::intern_registry()
        .require(&identifier)
        .expect("golden data only encodes an already-registered slot");

    let encoded = serde_json::to_value(&*canonical).expect("a canonical attribute encodes to JSON");
    let actual_encoding = normalize_encoded_tag(&encoded, slots);
    let expected_encoding = &op["expected"]["encoding"];

    if &actual_encoding != expected_encoding {
        mismatches.push(format!(
            "case {name} op {index}: expected encoding={expected_encoding}, got {actual_encoding}"
        ));
    }
}

fn check_decode_attribute(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let real_payload = build_decode_payload(op, |payload| denormalize_op_attribute(payload, slots));
    let expected = &op["expected"];
    let Some(restored) =
        decode_or_check_rejection::<OpAttribute>(real_payload, name, index, expected, mismatches)
    else {
        return;
    };

    let expected_slot = expected["canonical_slot"]
        .as_str()
        .expect("decode expectation has `canonical_slot`");
    let expected_description = expected["canonical_description"]
        .as_str()
        .expect("decode expectation has `canonical_description`");
    let actual_slot = slots.find_slot_for_id(restored.name().id());

    if actual_slot != expected_slot || restored.description() != expected_description {
        mismatches.push(format!(
            "case {name} op {index}: expected canonical_slot={expected_slot:?} \
             canonical_description={expected_description:?}, got canonical_slot={actual_slot:?} \
             canonical_description={:?}",
            restored.description()
        ));
    }
}

fn check_eq_attribute(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot_a = op["slot_a"].as_str().expect("eq op has slot_a");
    let slot_b = op["slot_b"].as_str().expect("eq op has slot_b");
    let a = OpAttribute::intern_registry()
        .require(&slots.resolve_identifier(slot_a))
        .expect("golden data only asks eq about registered slots");
    let b = OpAttribute::intern_registry()
        .require(&slots.resolve_identifier(slot_b))
        .expect("golden data only asks eq about registered slots");
    let expected = op["expected"]["result"]
        .as_bool()
        .expect("eq expectation has `result`");

    let actual = *a == *b;
    if actual != expected {
        mismatches.push(format!(
            "case {name} op {index}: expected result={expected}, got {actual}"
        ));
    }
}

/// Compare a slot's canonical attribute against a fresh, non-canonical
/// duplicate built for the same identifier.
///
/// `OpAttribute::new` on an already-registered identifier returns
/// `AlreadyCanonical { canonical, discarded }`; comparing those two exercises
/// `==` the way a discarded duplicate would, which `check_eq_attribute`
/// (always comparing two already-canonical, differently-named instances)
/// never reaches. This is the only way the golden data can catch `==`
/// wrongly including `description`, which equality must ignore.
fn check_eq_with_duplicate_attribute(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"]
        .as_str()
        .expect("eq_with_duplicate op has a slot");
    let other_description = op["other_description"]
        .as_str()
        .expect("eq_with_duplicate op has an other_description");
    let identifier = slots.resolve_identifier(slot);

    let outcome = OpAttribute::new(identifier, other_description);
    let InternOutcome::AlreadyCanonical {
        canonical,
        discarded,
    } = outcome
    else {
        panic!(
            "case {name} op {index}: golden data only builds eq_with_duplicate for an \
             already-registered slot"
        );
    };
    let expected = op["expected"]["result"]
        .as_bool()
        .expect("eq_with_duplicate expectation has `result`");

    let actual = *canonical == discarded;
    if actual != expected {
        mismatches.push(format!(
            "case {name} op {index}: expected result={expected}, got {actual}"
        ));
    }
}

fn replay_op_attribute_case(case: &Value, mismatches: &mut Vec<String>) {
    let name = case["name"].as_str().expect("case has a name");
    let ops = case["ops"].as_array().expect("case has an ops array");
    let mut slots = create_op_attribute_slots();

    for (index, op) in ops.iter().enumerate() {
        match op["op"].as_str().expect("op has a kind") {
            "new" => check_new_attribute(&mut slots, name, index, op, mismatches),
            "get" => check_get_attribute(&mut slots, name, index, op, mismatches),
            "require" => check_require_attribute(&mut slots, name, index, op, mismatches),
            "clear" => OpAttribute::intern_registry().clear(),
            "encode" => check_encode_attribute(&mut slots, name, index, op, mismatches),
            "decode" => check_decode_attribute(&mut slots, name, index, op, mismatches),
            "eq" => check_eq_attribute(&mut slots, name, index, op, mismatches),
            "eq_with_duplicate" => {
                check_eq_with_duplicate_attribute(&mut slots, name, index, op, mismatches);
            }
            "bind_ahead" => slots.bind_ahead(op["slot"].as_str().expect("op has a slot")),
            "is_counter_past" => check_is_counter_past(&mut slots, name, index, op, mismatches),
            other => panic!("case {name} op {index}: unknown op_attribute op kind {other:?}"),
        }
    }
}

// =============================================================================
// `value_domain` op replay
// =============================================================================

/// Resolve `op[key]` (a slot name, or `null`) into an already-registered
/// `ValueDomain` parent handle.
///
/// # Panics
///
/// Panics if `op[key]` names a slot with no canonical `ValueDomain`, since
/// the golden data only ever parents an operation on an already-registered
/// slot.
fn resolve_optional_parent(
    slots: &mut SlotTable,
    op: &Value,
    key: &str,
) -> Option<Canonical<ValueDomain>> {
    op[key].as_str().map(|parent_slot| {
        let parent_identifier = slots.resolve_identifier(parent_slot);
        ValueDomain::intern_registry()
            .require(&parent_identifier)
            .expect("golden data only names an already-registered slot for a parent field")
    })
}

fn check_new_domain(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"].as_str().expect("new op has a slot");
    let description = op["description"]
        .as_str()
        .expect("new op has a description");
    let identifier = slots.resolve_identifier(slot);
    let parent = resolve_optional_parent(slots, op, "parent_slot");

    let outcome = ValueDomain::new(identifier, description, parent);
    let expected = &op["expected"];
    let expected_registered = expected["registered"]
        .as_bool()
        .expect("new expectation has `registered`");
    let expected_description = expected["canonical_description"]
        .as_str()
        .expect("new expectation has `canonical_description`");
    let expected_parent_slot = expected["canonical_parent_slot"].as_str();

    let actual_registered = outcome.is_registered();
    let canonical = outcome.into_canonical();
    let actual_parent_slot = canonical
        .parent()
        .map(|parent| slots.find_slot_for_id(parent.name().id()));

    if actual_registered != expected_registered
        || canonical.description() != expected_description
        || actual_parent_slot != expected_parent_slot
    {
        mismatches.push(format!(
            "case {name} op {index}: expected registered={expected_registered} \
             canonical_description={expected_description:?} \
             canonical_parent_slot={expected_parent_slot:?}, got registered={actual_registered} \
             canonical_description={:?} canonical_parent_slot={actual_parent_slot:?}",
            canonical.description()
        ));
    }
}

fn check_get_domain(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"].as_str().expect("get op has a slot");
    let identifier = slots.resolve_identifier(slot);
    let expected = &op["expected"];
    let expected_description = expected["canonical_description"].as_str();
    let expected_parent_slot = expected["canonical_parent_slot"].as_str();

    let actual = ValueDomain::intern_registry().get(&identifier);
    let actual_description = actual.as_ref().map(|canonical| canonical.description());
    let actual_parent_slot = actual
        .as_ref()
        .and_then(|canonical| canonical.parent())
        .map(|parent| slots.find_slot_for_id(parent.name().id()));

    if actual_description != expected_description || actual_parent_slot != expected_parent_slot {
        mismatches.push(format!(
            "case {name} op {index}: expected canonical_description={expected_description:?} \
             canonical_parent_slot={expected_parent_slot:?}, got \
             canonical_description={actual_description:?} canonical_parent_slot={actual_parent_slot:?}"
        ));
    }
}

fn check_require_domain(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"].as_str().expect("require op has a slot");
    let identifier = slots.resolve_identifier(slot);
    let expected = &op["expected"];

    match ValueDomain::intern_registry().require(&identifier) {
        Ok(canonical) => {
            let expected_description = expected["canonical_description"].as_str();
            let expected_parent_slot = expected["canonical_parent_slot"].as_str();
            let actual_parent_slot = canonical
                .parent()
                .map(|parent| slots.find_slot_for_id(parent.name().id()));
            if Some(canonical.description()) != expected_description
                || actual_parent_slot != expected_parent_slot
            {
                mismatches.push(format!(
                    "case {name} op {index}: expected canonical_description={expected_description:?} \
                     canonical_parent_slot={expected_parent_slot:?}, got \
                     canonical_description={:?} canonical_parent_slot={actual_parent_slot:?}",
                    canonical.description()
                ));
            }
        }
        Err(error) => {
            let expected_error = expected["error"].as_str();
            if expected_error != Some("KeyError") {
                mismatches.push(format!(
                    "case {name} op {index}: expected {expected:?}, got error {error}"
                ));
            }
        }
    }
}

fn check_encode_domain(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"].as_str().expect("encode op has a slot");
    let identifier = slots.resolve_identifier(slot);
    let canonical = ValueDomain::intern_registry()
        .require(&identifier)
        .expect("golden data only encodes an already-registered slot");

    let encoded = serde_json::to_value(&*canonical).expect("a canonical domain encodes to JSON");
    let actual_encoding = normalize_encoded_tag(&encoded, slots);
    let expected_encoding = &op["expected"]["encoding"];

    if &actual_encoding != expected_encoding {
        mismatches.push(format!(
            "case {name} op {index}: expected encoding={expected_encoding}, got {actual_encoding}"
        ));
    }
}

fn check_decode_domain(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let real_payload = build_decode_payload(op, |payload| denormalize_value_domain(payload, slots));
    let expected = &op["expected"];
    let Some(restored) =
        decode_or_check_rejection::<ValueDomain>(real_payload, name, index, expected, mismatches)
    else {
        return;
    };

    let expected_slot = expected["canonical_slot"]
        .as_str()
        .expect("decode expectation has `canonical_slot`");
    let expected_description = expected["canonical_description"]
        .as_str()
        .expect("decode expectation has `canonical_description`");
    let expected_parent_slot = expected["canonical_parent_slot"].as_str();
    let actual_slot = slots.find_slot_for_id(restored.name().id());
    let actual_parent_slot = restored
        .parent()
        .map(|parent| slots.find_slot_for_id(parent.name().id()));

    if actual_slot != expected_slot
        || restored.description() != expected_description
        || actual_parent_slot != expected_parent_slot
    {
        mismatches.push(format!(
            "case {name} op {index}: expected canonical_slot={expected_slot:?} \
             canonical_description={expected_description:?} \
             canonical_parent_slot={expected_parent_slot:?}, got canonical_slot={actual_slot:?} \
             canonical_description={:?} canonical_parent_slot={actual_parent_slot:?}",
            restored.description()
        ));
    }
}

fn check_is_subdomain_of(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot_a = op["slot_a"]
        .as_str()
        .expect("is_subdomain_of op has slot_a");
    let slot_b = op["slot_b"]
        .as_str()
        .expect("is_subdomain_of op has slot_b");
    let a = ValueDomain::intern_registry()
        .require(&slots.resolve_identifier(slot_a))
        .expect("golden data only asks is_subdomain_of about registered slots");
    let b = ValueDomain::intern_registry()
        .require(&slots.resolve_identifier(slot_b))
        .expect("golden data only asks is_subdomain_of about registered slots");
    let expected = op["expected"]["result"]
        .as_bool()
        .expect("is_subdomain_of expectation has `result`");

    let actual = a.is_subdomain_of(&b);
    if actual != expected {
        mismatches.push(format!(
            "case {name} op {index}: expected result={expected}, got {actual}"
        ));
    }
}

fn check_eq_domain(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot_a = op["slot_a"].as_str().expect("eq op has slot_a");
    let slot_b = op["slot_b"].as_str().expect("eq op has slot_b");
    let a = ValueDomain::intern_registry()
        .require(&slots.resolve_identifier(slot_a))
        .expect("golden data only asks eq about registered slots");
    let b = ValueDomain::intern_registry()
        .require(&slots.resolve_identifier(slot_b))
        .expect("golden data only asks eq about registered slots");
    let expected = op["expected"]["result"]
        .as_bool()
        .expect("eq expectation has `result`");

    let actual = *a == *b;
    if actual != expected {
        mismatches.push(format!(
            "case {name} op {index}: expected result={expected}, got {actual}"
        ));
    }
}

/// Compare a slot's canonical domain against a fresh, non-canonical
/// duplicate built for the same identifier.
///
/// `ValueDomain::new` on an already-registered identifier returns
/// `AlreadyCanonical { canonical, discarded }`; comparing those two exercises
/// `==` the way a discarded duplicate would, which `check_eq_domain` (always
/// comparing two already-canonical, differently-named instances) never
/// reaches. This is the only way the golden data can catch `==` wrongly
/// dropping the `parent` comparison, which equality must include.
fn check_eq_with_duplicate_domain(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"]
        .as_str()
        .expect("eq_with_duplicate op has a slot");
    let other_description = op["other_description"]
        .as_str()
        .expect("eq_with_duplicate op has an other_description");
    let identifier = slots.resolve_identifier(slot);
    let other_parent = resolve_optional_parent(slots, op, "other_parent_slot");

    let outcome = ValueDomain::new(identifier, other_description, other_parent);
    let InternOutcome::AlreadyCanonical {
        canonical,
        discarded,
    } = outcome
    else {
        panic!(
            "case {name} op {index}: golden data only builds eq_with_duplicate for an \
             already-registered slot"
        );
    };
    let expected = op["expected"]["result"]
        .as_bool()
        .expect("eq_with_duplicate expectation has `result`");

    let actual = *canonical == discarded;
    if actual != expected {
        mismatches.push(format!(
            "case {name} op {index}: expected result={expected}, got {actual}"
        ));
    }
}

/// Test `is_subdomain_of` against a fresh duplicate rather than a canonical.
///
/// `is_subdomain_of` is defined in terms of `==`; passing a duplicate (built
/// the same way as `check_eq_with_duplicate_domain`) as `other` forces the
/// walk to compare against a value that shares a registered slot's name but
/// not necessarily its parent, which comparing two canonical handles never
/// exercises.
fn check_is_subdomain_of_with_duplicate(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let self_slot = op["self_slot"]
        .as_str()
        .expect("is_subdomain_of_with_duplicate op has self_slot");
    let other_slot = op["other_slot"]
        .as_str()
        .expect("is_subdomain_of_with_duplicate op has other_slot");
    let other_description = op["other_description"]
        .as_str()
        .expect("is_subdomain_of_with_duplicate op has an other_description");

    let self_domain = ValueDomain::intern_registry()
        .require(&slots.resolve_identifier(self_slot))
        .expect(
            "golden data only asks is_subdomain_of_with_duplicate about a registered self_slot",
        );
    let other_identifier = slots.resolve_identifier(other_slot);
    let other_parent = resolve_optional_parent(slots, op, "other_parent_slot");

    let outcome = ValueDomain::new(other_identifier, other_description, other_parent);
    let InternOutcome::AlreadyCanonical { discarded, .. } = outcome else {
        panic!(
            "case {name} op {index}: golden data only builds is_subdomain_of_with_duplicate for \
             an already-registered other_slot"
        );
    };

    let expected = op["expected"]["result"]
        .as_bool()
        .expect("is_subdomain_of_with_duplicate expectation has `result`");
    let actual = self_domain.is_subdomain_of(&discarded);
    if actual != expected {
        mismatches.push(format!(
            "case {name} op {index}: expected result={expected}, got {actual}"
        ));
    }
}

/// Set a slot's current canonical domain aside under the op's label.
fn hold_domain(
    slots: &mut SlotTable,
    held: &mut HashMap<String, Canonical<ValueDomain>>,
    op: &Value,
) {
    let slot = op["slot"].as_str().expect("hold op has a slot");
    let label = op["label"].as_str().expect("hold op has a label");
    let canonical = ValueDomain::intern_registry()
        .require(&slots.resolve_identifier(slot))
        .expect("golden data only holds a registered slot");
    held.insert(label.to_string(), canonical);
}

/// Compare a held domain with a slot's current canonical domain.
///
/// A held domain may predate a clear, so its parent is a different instance
/// from the current canonical's parent even when the two chains carry the
/// same names. Equal domains must also hash equally.
fn check_eq_held_domain(
    slots: &mut SlotTable,
    held: &HashMap<String, Canonical<ValueDomain>>,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let label = op["label"].as_str().expect("eq_held op has a label");
    let slot = op["slot"].as_str().expect("eq_held op has a slot");
    let held_domain = held
        .get(label)
        .unwrap_or_else(|| panic!("case {name} op {index}: nothing is held under {label:?}"));
    let canonical = ValueDomain::intern_registry()
        .require(&slots.resolve_identifier(slot))
        .expect("golden data only compares a held domain with a registered slot");
    let expected = op["expected"]["result"]
        .as_bool()
        .expect("eq_held expectation has `result`");

    let actual = **held_domain == *canonical;
    if actual != expected {
        mismatches.push(format!(
            "case {name} op {index}: expected result={expected}, got {actual}"
        ));
    }
    if actual && compute_hash(&**held_domain) != compute_hash(&*canonical) {
        mismatches.push(format!(
            "case {name} op {index}: equal domains hash differently"
        ));
    }
}

fn replay_value_domain_case(case: &Value, mismatches: &mut Vec<String>) {
    let name = case["name"].as_str().expect("case has a name");
    let ops = case["ops"].as_array().expect("case has an ops array");
    let mut slots = create_value_domain_slots();
    let mut held = HashMap::new();

    for (index, op) in ops.iter().enumerate() {
        match op["op"].as_str().expect("op has a kind") {
            "new" => check_new_domain(&mut slots, name, index, op, mismatches),
            "get" => check_get_domain(&mut slots, name, index, op, mismatches),
            "require" => check_require_domain(&mut slots, name, index, op, mismatches),
            "clear" => ValueDomain::intern_registry().clear(),
            "encode" => check_encode_domain(&mut slots, name, index, op, mismatches),
            "decode" => check_decode_domain(&mut slots, name, index, op, mismatches),
            "is_subdomain_of" => check_is_subdomain_of(&mut slots, name, index, op, mismatches),
            "eq" => check_eq_domain(&mut slots, name, index, op, mismatches),
            "eq_with_duplicate" => {
                check_eq_with_duplicate_domain(&mut slots, name, index, op, mismatches);
            }
            "is_subdomain_of_with_duplicate" => {
                check_is_subdomain_of_with_duplicate(&mut slots, name, index, op, mismatches);
            }
            "hold" => hold_domain(&mut slots, &mut held, op),
            "eq_held" => check_eq_held_domain(&mut slots, &held, name, index, op, mismatches),
            "bind_ahead" => slots.bind_ahead(op["slot"].as_str().expect("op has a slot")),
            "is_counter_past" => check_is_counter_past(&mut slots, name, index, op, mismatches),
            other => panic!("case {name} op {index}: unknown value_domain op kind {other:?}"),
        }
    }
}

// =============================================================================
// Document-level replay
// =============================================================================

fn replay_case(case: &Value, mismatches: &mut Vec<String>) {
    match case["type"].as_str().expect("case has a `type`") {
        "op_attribute" => replay_op_attribute_case(case, mismatches),
        "value_domain" => replay_value_domain_case(case, mismatches),
        other => panic!("case has an unknown type {other:?}"),
    }
}

/// Assert the golden data's default-slot names match the slots this replay
/// binds, so the two cannot silently drift apart.
fn assert_default_slots_match_rust(document: &Value) {
    let default_slots = document["default_slots"]
        .as_object()
        .expect("golden data has a `default_slots` object");

    let expected_op_attribute_slots: Vec<&str> =
        vec!["commutative", "associative", "pure", "elementwise"];
    let expected_value_domain_slots: Vec<&str> = vec!["data", "address"];

    for (kind, expected) in [
        ("op_attribute", &expected_op_attribute_slots),
        ("value_domain", &expected_value_domain_slots),
    ] {
        let actual: Vec<&str> = default_slots[kind]
            .as_array()
            .unwrap_or_else(|| panic!("default_slots.{kind} is not an array"))
            .iter()
            .map(|value| value.as_str().expect("a default slot name is a string"))
            .collect();
        assert_eq!(
            &actual, expected,
            "Rust's default slots for {kind} have drifted from the golden data"
        );
    }
}

/// Serializes the corpus replays, since every script clears and interns into
/// the process-global registries.
static REPLAY_LOCK: Mutex<()> = Mutex::new(());

/// Lock [`REPLAY_LOCK`] for the caller's whole replay, recovering from
/// poisoning: every script creates fresh identifiers, so a replay that
/// panicked leaves nothing behind that another replay reads.
fn lock_replay() -> MutexGuard<'static, ()> {
    REPLAY_LOCK.lock().unwrap_or_else(PoisonError::into_inner)
}

/// Test the Rust `OpAttribute` and `ValueDomain` registries reproduce every
/// observation the Python oracle recorded for the golden operation scripts.
#[test]
fn tag_type_registries_match_the_python_oracle() {
    let _replay = lock_replay();
    common::replay_golden_document(
        GOLDEN_JSON,
        MIN_CASES,
        MIN_OPS,
        None,
        assert_default_slots_match_rust,
        replay_case,
    );
}

/// Test the Rust registries reproduce every observation the Python oracle
/// recorded for an expanded corpus, read from the file named by
/// `FHY_TAG_TYPE_CORPUS` and written with the generator's corpus options.
#[test]
#[ignore = "requires an expanded corpus generated from the Python oracle"]
fn tag_type_registries_match_the_python_oracle_on_an_expanded_corpus() {
    let (path, json) = common::read_expanded_corpus("FHY_TAG_TYPE_CORPUS");
    let _replay = lock_replay();

    common::replay_golden_document(
        &json,
        MIN_CASES,
        MIN_OPS,
        Some(&path),
        assert_default_slots_match_rust,
        replay_case,
    );
}
