//! Equivalence test replaying golden operation scripts from the Python
//! `InternedMixin` oracle against `fhy_core::interned::InternRegistry`.
//!
//! The golden data is generated by
//! `rust/tests/golden/generate_interned_cases.py` and committed at
//! `rust/tests/golden/interned_cases.json`. This test only uses the public
//! `fhy_core::interned` API.

use fhy_core::interned::*;
use serde_json::Value;

/// Oracle-equivalent fixture type: a name-keyed tag carrying a `note` that
/// identifies the exact instance under test.
struct GoldenTag {
    name: String,
    note: String,
}

impl Interned for GoldenTag {
    type Key = String;

    fn intern_key(&self) -> &String {
        &self.name
    }

    // Required by `Interned`, but every script below builds its own local
    // registry via `InternRegistry::with_defaults`, so this process-wide
    // registry is never actually consulted.
    fn intern_registry() -> &'static InternRegistry<GoldenTag> {
        static REGISTRY: InternRegistry<GoldenTag> = InternRegistry::new();
        &REGISTRY
    }
}

fn build_golden_tag(name: &str, note: &str) -> GoldenTag {
    GoldenTag {
        name: name.to_string(),
        note: note.to_string(),
    }
}

fn create_no_defaults() -> Vec<GoldenTag> {
    Vec::new()
}

fn create_one_default() -> Vec<GoldenTag> {
    vec![build_golden_tag("a", "default-a")]
}

fn create_two_defaults() -> Vec<GoldenTag> {
    vec![
        build_golden_tag("a", "default-a"),
        build_golden_tag("b", "default-b"),
    ]
}

fn create_duplicate_defaults() -> Vec<GoldenTag> {
    vec![
        build_golden_tag("a", "default-a-first"),
        build_golden_tag("a", "default-a-second"),
    ]
}

/// Map a defaults-catalogue id from the golden data to the matching Rust
/// catalogue function.
fn select_catalogue_defaults(id: &str) -> fn() -> Vec<GoldenTag> {
    match id {
        "none" => create_no_defaults,
        "one" => create_one_default,
        "two" => create_two_defaults,
        "duplicate" => create_duplicate_defaults,
        other => panic!("unknown defaults catalogue id in golden data: {other}"),
    }
}

const GOLDEN_JSON: &str = include_str!("golden/interned_cases.json");

/// Assert the golden data is large enough that an empty or truncated file
/// cannot pass this test.
fn assert_case_and_op_counts(cases: &[Value]) {
    assert!(
        cases.len() >= 120,
        "expected at least 120 golden cases, found {}",
        cases.len()
    );
    let total_ops: usize = cases
        .iter()
        .map(|case| case["ops"].as_array().map_or(0, Vec::len))
        .sum();
    assert!(
        total_ops >= 1000,
        "expected at least 1000 golden ops, found {total_ops}"
    );
}

/// Assert every defaults-catalogue entry in the golden data matches the
/// corresponding Rust catalogue function, so the two cannot silently drift
/// apart.
fn assert_catalogue_matches_rust(document: &Value) {
    let catalogue = document["defaults_catalogue"]
        .as_object()
        .expect("golden data has a `defaults_catalogue` object");

    for (id, expected_defaults) in catalogue {
        let expected: Vec<(String, String)> = expected_defaults
            .as_array()
            .unwrap_or_else(|| panic!("defaults catalogue entry {id} is not an array"))
            .iter()
            .map(|entry| {
                let key = entry["key"].as_str().expect("default entry has a key");
                let note = entry["note"].as_str().expect("default entry has a note");
                (key.to_string(), note.to_string())
            })
            .collect();

        let actual: Vec<(String, String)> = select_catalogue_defaults(id)()
            .into_iter()
            .map(|tag| (tag.name, tag.note))
            .collect();

        assert_eq!(
            actual, expected,
            "Rust defaults catalogue {id:?} has drifted from the golden data"
        );
    }
}

fn check_intern(
    registry: &InternRegistry<GoldenTag>,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let key = op["key"].as_str().expect("intern op has a key");
    let note = op["note"].as_str().expect("intern op has a note");
    let expected_registered = op["expected"]["registered"]
        .as_bool()
        .expect("intern expectation has `registered`");
    let expected_note = op["expected"]["canonical_note"]
        .as_str()
        .expect("intern expectation has `canonical_note`");

    let outcome = registry.intern(build_golden_tag(key, note));
    let actual_registered = outcome.is_registered();
    let actual_note = outcome.canonical().note.clone();

    if actual_registered != expected_registered || actual_note != expected_note {
        mismatches.push(format!(
            "case {name} op {index}: expected registered={expected_registered} \
             canonical_note={expected_note:?}, got registered={actual_registered} \
             canonical_note={actual_note:?}"
        ));
    }
}

fn check_get(
    registry: &InternRegistry<GoldenTag>,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let key = op["key"].as_str().expect("get op has a key");
    let expected_note = op["expected"]
        .get("canonical_note")
        .expect("get expectation has `canonical_note`")
        .as_str();

    let actual_note = registry.get(key).map(|canonical| canonical.note.clone());

    if actual_note.as_deref() != expected_note {
        mismatches.push(format!(
            "case {name} op {index}: expected canonical_note={expected_note:?}, got \
             canonical_note={actual_note:?}"
        ));
    }
}

fn check_require(
    registry: &InternRegistry<GoldenTag>,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let key = op["key"].as_str().expect("require op has a key");
    let expected = &op["expected"];

    match registry.require(key) {
        Ok(canonical) => {
            let expected_note = expected["canonical_note"].as_str();
            if Some(canonical.note.as_str()) != expected_note {
                mismatches.push(format!(
                    "case {name} op {index}: expected canonical_note={expected_note:?}, got \
                     canonical_note={:?}",
                    canonical.note
                ));
            }
        }
        Err(error) => {
            let expected_error = expected["error"].as_str();
            if expected_error != Some("KeyError") {
                mismatches.push(format!(
                    "case {name} op {index}: expected {expected:?}, got error {error}"
                ));
            } else if error.key() != key {
                mismatches.push(format!(
                    "case {name} op {index}: error key {:?} does not match requested key {key:?}",
                    error.key()
                ));
            }
        }
    }
}

fn replay_op(
    registry: &InternRegistry<GoldenTag>,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    match op["op"].as_str().expect("op has a kind") {
        "intern" => check_intern(registry, name, index, op, mismatches),
        "get" => check_get(registry, name, index, op, mismatches),
        "require" => check_require(registry, name, index, op, mismatches),
        "clear" => registry.clear(),
        other => panic!("case {name} op {index}: unknown op kind {other:?}"),
    }
}

fn replay_case(case: &Value, mismatches: &mut Vec<String>) {
    let name = case["name"].as_str().expect("case has a name");
    let defaults_id = case["defaults"].as_str().expect("case has a defaults id");
    let ops = case["ops"].as_array().expect("case has an ops array");

    let registry =
        InternRegistry::<GoldenTag>::with_defaults(select_catalogue_defaults(defaults_id));

    for (index, op) in ops.iter().enumerate() {
        replay_op(&registry, name, index, op, mismatches);
    }
}

/// Parse a golden document, check its size and defaults catalogue, replay
/// every case, and return the mismatches found.
fn replay_golden_document(json: &str) -> Vec<String> {
    let document: Value = serde_json::from_str(json).expect("golden data is valid JSON");
    let cases = document["cases"]
        .as_array()
        .expect("golden data has a `cases` array");

    assert_case_and_op_counts(cases);
    assert_catalogue_matches_rust(&document);

    let mut mismatches = Vec::new();
    for case in cases {
        replay_case(case, &mut mismatches);
    }
    mismatches
}

/// Test the Rust `InternRegistry` reproduces every observation the Python
/// `InternedMixin` oracle recorded for the golden operation scripts.
#[test]
fn interned_registry_matches_the_python_oracle() {
    let mismatches = replay_golden_document(GOLDEN_JSON);

    assert!(
        mismatches.is_empty(),
        "found {} mismatch(es):\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
}

/// Test the Rust `InternRegistry` reproduces every observation the Python
/// oracle recorded for an expanded corpus, read from the file named by
/// `FHY_INTERNED_CORPUS` and written with the generator's corpus options.
#[test]
#[ignore = "requires an expanded corpus generated from the Python oracle"]
fn interned_registry_matches_the_python_oracle_on_an_expanded_corpus() {
    let path = std::env::var("FHY_INTERNED_CORPUS")
        .expect("FHY_INTERNED_CORPUS names an expanded corpus file");
    let json = std::fs::read_to_string(&path).expect("expanded corpus file is readable");

    let mismatches = replay_golden_document(&json);

    assert!(
        mismatches.is_empty(),
        "found {} mismatch(es) in {path}:\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
}
