//! Equivalence test replaying golden operation scripts from the Python
//! `OpAttribute`/`ValueDomain` oracle against `fhy_core::op_attribute` and
//! `fhy_core::value_domain`.
//!
//! The golden data is generated by
//! `rust/tests/golden/generate_tag_type_cases.py` and committed at
//! `rust/tests/golden/tag_type_cases.json`. This test only uses the public
//! `fhy_core::identifier`, `fhy_core::interned`, `fhy_core::op_attribute` and
//! `fhy_core::value_domain` APIs.
//!
//! Every script in the golden data runs against the process-global
//! `OpAttribute` and `ValueDomain` registries, because their constructors
//! have no other registry to intern into. Both `#[test]` functions below
//! therefore replay their whole corpus as ONE sequential loop, never split
//! across several `#[test]` functions: cargo schedules different `#[test]`
//! functions on separate threads, and running two of these concurrently
//! would race a `clear()` in one script against an intern in another.

use std::collections::hash_map::DefaultHasher;
use std::collections::HashMap;
use std::hash::{Hash, Hasher};

use fhy_core::identifier::Identifier;
use fhy_core::interned::{Canonical, InternOutcome, Interned};
use fhy_core::op_attribute::{OpAttribute, ASSOCIATIVE, COMMUTATIVE, ELEMENTWISE, PURE};
use fhy_core::value_domain::{ValueDomain, ADDRESS_DOMAIN, DATA_DOMAIN};
use serde_json::{json, Value};

const GOLDEN_JSON: &str = include_str!("golden/tag_type_cases.json");

/// Per-script table binding the identifier slots named in the golden data to
/// the `Identifier` minted for them in this process.
///
/// A slot's identifier is minted once, the first time the script refers to
/// it (mirroring the generator), and reused for the rest of the script. The
/// reverse lookup turns a registry's identifier back into the slot name the
/// golden data expects, so an encoded value or a domain's parent can be
/// compared in normalized (slot) form.
struct SlotTable {
    by_slot: HashMap<String, Identifier>,
    by_id: HashMap<u64, String>,
}

impl SlotTable {
    fn new() -> Self {
        Self {
            by_slot: HashMap::new(),
            by_id: HashMap::new(),
        }
    }

    fn bind_slot(&mut self, slot: &str, identifier: Identifier) {
        self.by_id.insert(identifier.id(), slot.to_string());
        self.by_slot.insert(slot.to_string(), identifier);
    }

    /// Return `slot`'s identifier, minting a fresh one on first use.
    fn resolve_identifier(&mut self, slot: &str) -> Identifier {
        if let Some(identifier) = self.by_slot.get(slot) {
            return identifier.clone();
        }
        let identifier = Identifier::new(slot);
        self.bind_slot(slot, identifier.clone());
        identifier
    }

    /// Return the slot name bound to `id`.
    ///
    /// # Panics
    ///
    /// Panics if `id` was never bound, which would mean the golden data
    /// refers to an identifier this replay never minted or seeded.
    fn find_slot_for_id(&self, id: u64) -> &str {
        self.by_id.get(&id).map_or_else(
            || panic!("identifier id {id} is not bound to any slot"),
            String::as_str,
        )
    }
}

/// Return `value`'s hash under the default hasher.
fn compute_hash<T: Hash>(value: &T) -> u64 {
    let mut hasher = DefaultHasher::new();
    value.hash(&mut hasher);
    hasher.finish()
}

fn create_op_attribute_slots() -> SlotTable {
    let mut slots = SlotTable::new();
    slots.bind_slot("commutative", COMMUTATIVE.name().clone());
    slots.bind_slot("associative", ASSOCIATIVE.name().clone());
    slots.bind_slot("pure", PURE.name().clone());
    slots.bind_slot("elementwise", ELEMENTWISE.name().clone());
    slots
}

fn create_value_domain_slots() -> SlotTable {
    let mut slots = SlotTable::new();
    slots.bind_slot("data", DATA_DOMAIN.name().clone());
    slots.bind_slot("address", ADDRESS_DOMAIN.name().clone());
    slots
}

// =============================================================================
// Normalization: a real encoded value has a numeric `id`; a normalized one
// (as recorded in the golden data) has the slot name that id belongs to.
// =============================================================================

fn denormalize_identifier(value: &Value, slots: &mut SlotTable) -> Value {
    let slot = value["id"]
        .as_str()
        .expect("a normalized identifier's id is a slot name");
    let name_hint = value["name_hint"]
        .as_str()
        .expect("a normalized identifier has a name_hint");
    let identifier = slots.resolve_identifier(slot);
    json!({"id": identifier.id(), "name_hint": name_hint})
}

fn denormalize_op_attribute(value: &Value, slots: &mut SlotTable) -> Value {
    json!({
        "name": denormalize_identifier(&value["name"], slots),
        "description": value["description"],
    })
}

fn denormalize_value_domain(value: &Value, slots: &mut SlotTable) -> Value {
    let parent = &value["parent"];
    let parent_value = if parent.is_null() {
        Value::Null
    } else {
        denormalize_value_domain(parent, slots)
    };
    json!({
        "name": denormalize_identifier(&value["name"], slots),
        "description": value["description"],
        "parent": parent_value,
    })
}

fn normalize_identifier(identifier: &Identifier, slots: &SlotTable) -> Value {
    json!({
        "id": slots.find_slot_for_id(identifier.id()),
        "name_hint": identifier.name_hint(),
    })
}

fn normalize_op_attribute(attribute: &OpAttribute, slots: &SlotTable) -> Value {
    json!({
        "name": normalize_identifier(attribute.name(), slots),
        "description": attribute.description(),
    })
}

fn normalize_value_domain(domain: &ValueDomain, slots: &SlotTable) -> Value {
    let parent = match domain.parent() {
        Some(parent) => normalize_value_domain(parent, slots),
        None => Value::Null,
    };
    json!({
        "name": normalize_identifier(domain.name(), slots),
        "description": domain.description(),
        "parent": parent,
    })
}

// =============================================================================
// `op_attribute` op replay
// =============================================================================

fn check_new_attribute(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"].as_str().expect("new op has a slot");
    let description = op["description"]
        .as_str()
        .expect("new op has a description");
    let identifier = slots.resolve_identifier(slot);

    let outcome = OpAttribute::new(identifier, description);
    let expected = &op["expected"];
    let expected_registered = expected["registered"]
        .as_bool()
        .expect("new expectation has `registered`");
    let expected_description = expected["canonical_description"]
        .as_str()
        .expect("new expectation has `canonical_description`");

    let actual_registered = outcome.is_registered();
    let canonical = outcome.into_canonical();

    if actual_registered != expected_registered || canonical.description() != expected_description {
        mismatches.push(format!(
            "case {name} op {index}: expected registered={expected_registered} \
             canonical_description={expected_description:?}, got registered={actual_registered} \
             canonical_description={:?}",
            canonical.description()
        ));
    }
}

fn check_get_attribute(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"].as_str().expect("get op has a slot");
    let identifier = slots.resolve_identifier(slot);
    let expected_description = op["expected"]["canonical_description"].as_str();

    let actual = OpAttribute::intern_registry().get(&identifier);
    let actual_description = actual.as_ref().map(|canonical| canonical.description());

    if actual_description != expected_description {
        mismatches.push(format!(
            "case {name} op {index}: expected canonical_description={expected_description:?}, \
             got {actual_description:?}"
        ));
    }
}

fn check_require_attribute(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"].as_str().expect("require op has a slot");
    let identifier = slots.resolve_identifier(slot);
    let expected = &op["expected"];

    match OpAttribute::intern_registry().require(&identifier) {
        Ok(canonical) => {
            let expected_description = expected["canonical_description"].as_str();
            if Some(canonical.description()) != expected_description {
                mismatches.push(format!(
                    "case {name} op {index}: expected canonical_description={expected_description:?}, \
                     got {:?}",
                    canonical.description()
                ));
            }
        }
        Err(error) => {
            let expected_error = expected["error"].as_str();
            if expected_error != Some("KeyError") {
                mismatches.push(format!(
                    "case {name} op {index}: expected {expected:?}, got error {error}"
                ));
            }
        }
    }
}

fn check_encode_attribute(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"].as_str().expect("encode op has a slot");
    let identifier = slots.resolve_identifier(slot);
    let canonical = OpAttribute::intern_registry()
        .require(&identifier)
        .expect("golden data only encodes an already-registered slot");

    let actual_encoding = normalize_op_attribute(&canonical, slots);
    let expected_encoding = &op["expected"]["encoding"];

    if &actual_encoding != expected_encoding {
        mismatches.push(format!(
            "case {name} op {index}: expected encoding={expected_encoding}, got {actual_encoding}"
        ));
    }
}

fn check_decode_attribute(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let real_payload = denormalize_op_attribute(&op["payload"], slots);
    let restored: Canonical<OpAttribute> =
        serde_json::from_value(real_payload).expect("golden decode payload deserializes");

    let expected = &op["expected"];
    let expected_slot = expected["canonical_slot"]
        .as_str()
        .expect("decode expectation has `canonical_slot`");
    let expected_description = expected["canonical_description"]
        .as_str()
        .expect("decode expectation has `canonical_description`");
    let actual_slot = slots.find_slot_for_id(restored.name().id());

    if actual_slot != expected_slot || restored.description() != expected_description {
        mismatches.push(format!(
            "case {name} op {index}: expected canonical_slot={expected_slot:?} \
             canonical_description={expected_description:?}, got canonical_slot={actual_slot:?} \
             canonical_description={:?}",
            restored.description()
        ));
    }
}

fn check_eq_attribute(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot_a = op["slot_a"].as_str().expect("eq op has slot_a");
    let slot_b = op["slot_b"].as_str().expect("eq op has slot_b");
    let a = OpAttribute::intern_registry()
        .require(&slots.resolve_identifier(slot_a))
        .expect("golden data only asks eq about registered slots");
    let b = OpAttribute::intern_registry()
        .require(&slots.resolve_identifier(slot_b))
        .expect("golden data only asks eq about registered slots");
    let expected = op["expected"]["result"]
        .as_bool()
        .expect("eq expectation has `result`");

    let actual = *a == *b;
    if actual != expected {
        mismatches.push(format!(
            "case {name} op {index}: expected result={expected}, got {actual}"
        ));
    }
}

/// Compare a slot's canonical attribute against a fresh, non-canonical
/// duplicate built for the same identifier.
///
/// `OpAttribute::new` on an already-registered identifier returns
/// `AlreadyCanonical { canonical, discarded }`; comparing those two exercises
/// `==` the way a discarded duplicate would, which `check_eq_attribute`
/// (always comparing two already-canonical, differently-named instances)
/// never reaches. This is the only way the golden data can catch `==`
/// wrongly including `description`, which equality must ignore.
fn check_eq_with_duplicate_attribute(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"]
        .as_str()
        .expect("eq_with_duplicate op has a slot");
    let other_description = op["other_description"]
        .as_str()
        .expect("eq_with_duplicate op has an other_description");
    let identifier = slots.resolve_identifier(slot);

    let outcome = OpAttribute::new(identifier, other_description);
    let InternOutcome::AlreadyCanonical {
        canonical,
        discarded,
    } = outcome
    else {
        panic!(
            "case {name} op {index}: golden data only builds eq_with_duplicate for an \
             already-registered slot"
        );
    };
    let expected = op["expected"]["result"]
        .as_bool()
        .expect("eq_with_duplicate expectation has `result`");

    let actual = *canonical == discarded;
    if actual != expected {
        mismatches.push(format!(
            "case {name} op {index}: expected result={expected}, got {actual}"
        ));
    }
}

fn replay_op_attribute_case(case: &Value, mismatches: &mut Vec<String>) {
    let name = case["name"].as_str().expect("case has a name");
    let ops = case["ops"].as_array().expect("case has an ops array");
    let mut slots = create_op_attribute_slots();

    for (index, op) in ops.iter().enumerate() {
        match op["op"].as_str().expect("op has a kind") {
            "new" => check_new_attribute(&mut slots, name, index, op, mismatches),
            "get" => check_get_attribute(&mut slots, name, index, op, mismatches),
            "require" => check_require_attribute(&mut slots, name, index, op, mismatches),
            "clear" => OpAttribute::intern_registry().clear(),
            "encode" => check_encode_attribute(&mut slots, name, index, op, mismatches),
            "decode" => check_decode_attribute(&mut slots, name, index, op, mismatches),
            "eq" => check_eq_attribute(&mut slots, name, index, op, mismatches),
            "eq_with_duplicate" => {
                check_eq_with_duplicate_attribute(&mut slots, name, index, op, mismatches);
            }
            other => panic!("case {name} op {index}: unknown op_attribute op kind {other:?}"),
        }
    }
}

// =============================================================================
// `value_domain` op replay
// =============================================================================

/// Resolve `op[key]` (a slot name, or `null`) into an already-registered
/// `ValueDomain` parent handle.
///
/// # Panics
///
/// Panics if `op[key]` names a slot with no canonical `ValueDomain`, since
/// the golden data only ever parents an operation on an already-registered
/// slot.
fn resolve_optional_parent(
    slots: &mut SlotTable,
    op: &Value,
    key: &str,
) -> Option<Canonical<ValueDomain>> {
    op[key].as_str().map(|parent_slot| {
        let parent_identifier = slots.resolve_identifier(parent_slot);
        ValueDomain::intern_registry()
            .require(&parent_identifier)
            .expect("golden data only names an already-registered slot for a parent field")
    })
}

fn check_new_domain(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"].as_str().expect("new op has a slot");
    let description = op["description"]
        .as_str()
        .expect("new op has a description");
    let identifier = slots.resolve_identifier(slot);
    let parent = resolve_optional_parent(slots, op, "parent_slot");

    let outcome = ValueDomain::new(identifier, description, parent);
    let expected = &op["expected"];
    let expected_registered = expected["registered"]
        .as_bool()
        .expect("new expectation has `registered`");
    let expected_description = expected["canonical_description"]
        .as_str()
        .expect("new expectation has `canonical_description`");
    let expected_parent_slot = expected["canonical_parent_slot"].as_str();

    let actual_registered = outcome.is_registered();
    let canonical = outcome.into_canonical();
    let actual_parent_slot = canonical
        .parent()
        .map(|parent| slots.find_slot_for_id(parent.name().id()));

    if actual_registered != expected_registered
        || canonical.description() != expected_description
        || actual_parent_slot != expected_parent_slot
    {
        mismatches.push(format!(
            "case {name} op {index}: expected registered={expected_registered} \
             canonical_description={expected_description:?} \
             canonical_parent_slot={expected_parent_slot:?}, got registered={actual_registered} \
             canonical_description={:?} canonical_parent_slot={actual_parent_slot:?}",
            canonical.description()
        ));
    }
}

fn check_get_domain(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"].as_str().expect("get op has a slot");
    let identifier = slots.resolve_identifier(slot);
    let expected = &op["expected"];
    let expected_description = expected["canonical_description"].as_str();
    let expected_parent_slot = expected["canonical_parent_slot"].as_str();

    let actual = ValueDomain::intern_registry().get(&identifier);
    let actual_description = actual.as_ref().map(|canonical| canonical.description());
    let actual_parent_slot = actual
        .as_ref()
        .and_then(|canonical| canonical.parent())
        .map(|parent| slots.find_slot_for_id(parent.name().id()));

    if actual_description != expected_description || actual_parent_slot != expected_parent_slot {
        mismatches.push(format!(
            "case {name} op {index}: expected canonical_description={expected_description:?} \
             canonical_parent_slot={expected_parent_slot:?}, got \
             canonical_description={actual_description:?} canonical_parent_slot={actual_parent_slot:?}"
        ));
    }
}

fn check_require_domain(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"].as_str().expect("require op has a slot");
    let identifier = slots.resolve_identifier(slot);
    let expected = &op["expected"];

    match ValueDomain::intern_registry().require(&identifier) {
        Ok(canonical) => {
            let expected_description = expected["canonical_description"].as_str();
            let expected_parent_slot = expected["canonical_parent_slot"].as_str();
            let actual_parent_slot = canonical
                .parent()
                .map(|parent| slots.find_slot_for_id(parent.name().id()));
            if Some(canonical.description()) != expected_description
                || actual_parent_slot != expected_parent_slot
            {
                mismatches.push(format!(
                    "case {name} op {index}: expected canonical_description={expected_description:?} \
                     canonical_parent_slot={expected_parent_slot:?}, got \
                     canonical_description={:?} canonical_parent_slot={actual_parent_slot:?}",
                    canonical.description()
                ));
            }
        }
        Err(error) => {
            let expected_error = expected["error"].as_str();
            if expected_error != Some("KeyError") {
                mismatches.push(format!(
                    "case {name} op {index}: expected {expected:?}, got error {error}"
                ));
            }
        }
    }
}

fn check_encode_domain(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"].as_str().expect("encode op has a slot");
    let identifier = slots.resolve_identifier(slot);
    let canonical = ValueDomain::intern_registry()
        .require(&identifier)
        .expect("golden data only encodes an already-registered slot");

    let actual_encoding = normalize_value_domain(&canonical, slots);
    let expected_encoding = &op["expected"]["encoding"];

    if &actual_encoding != expected_encoding {
        mismatches.push(format!(
            "case {name} op {index}: expected encoding={expected_encoding}, got {actual_encoding}"
        ));
    }
}

fn check_decode_domain(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let real_payload = denormalize_value_domain(&op["payload"], slots);
    let restored: Canonical<ValueDomain> =
        serde_json::from_value(real_payload).expect("golden decode payload deserializes");

    let expected = &op["expected"];
    let expected_slot = expected["canonical_slot"]
        .as_str()
        .expect("decode expectation has `canonical_slot`");
    let expected_description = expected["canonical_description"]
        .as_str()
        .expect("decode expectation has `canonical_description`");
    let expected_parent_slot = expected["canonical_parent_slot"].as_str();
    let actual_slot = slots.find_slot_for_id(restored.name().id());
    let actual_parent_slot = restored
        .parent()
        .map(|parent| slots.find_slot_for_id(parent.name().id()));

    if actual_slot != expected_slot
        || restored.description() != expected_description
        || actual_parent_slot != expected_parent_slot
    {
        mismatches.push(format!(
            "case {name} op {index}: expected canonical_slot={expected_slot:?} \
             canonical_description={expected_description:?} \
             canonical_parent_slot={expected_parent_slot:?}, got canonical_slot={actual_slot:?} \
             canonical_description={:?} canonical_parent_slot={actual_parent_slot:?}",
            restored.description()
        ));
    }
}

fn check_is_subdomain_of(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot_a = op["slot_a"]
        .as_str()
        .expect("is_subdomain_of op has slot_a");
    let slot_b = op["slot_b"]
        .as_str()
        .expect("is_subdomain_of op has slot_b");
    let a = ValueDomain::intern_registry()
        .require(&slots.resolve_identifier(slot_a))
        .expect("golden data only asks is_subdomain_of about registered slots");
    let b = ValueDomain::intern_registry()
        .require(&slots.resolve_identifier(slot_b))
        .expect("golden data only asks is_subdomain_of about registered slots");
    let expected = op["expected"]["result"]
        .as_bool()
        .expect("is_subdomain_of expectation has `result`");

    let actual = a.is_subdomain_of(&b);
    if actual != expected {
        mismatches.push(format!(
            "case {name} op {index}: expected result={expected}, got {actual}"
        ));
    }
}

fn check_eq_domain(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot_a = op["slot_a"].as_str().expect("eq op has slot_a");
    let slot_b = op["slot_b"].as_str().expect("eq op has slot_b");
    let a = ValueDomain::intern_registry()
        .require(&slots.resolve_identifier(slot_a))
        .expect("golden data only asks eq about registered slots");
    let b = ValueDomain::intern_registry()
        .require(&slots.resolve_identifier(slot_b))
        .expect("golden data only asks eq about registered slots");
    let expected = op["expected"]["result"]
        .as_bool()
        .expect("eq expectation has `result`");

    let actual = *a == *b;
    if actual != expected {
        mismatches.push(format!(
            "case {name} op {index}: expected result={expected}, got {actual}"
        ));
    }
}

/// Compare a slot's canonical domain against a fresh, non-canonical
/// duplicate built for the same identifier.
///
/// `ValueDomain::new` on an already-registered identifier returns
/// `AlreadyCanonical { canonical, discarded }`; comparing those two exercises
/// `==` the way a discarded duplicate would, which `check_eq_domain` (always
/// comparing two already-canonical, differently-named instances) never
/// reaches. This is the only way the golden data can catch `==` wrongly
/// dropping the `parent` comparison, which equality must include.
fn check_eq_with_duplicate_domain(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let slot = op["slot"]
        .as_str()
        .expect("eq_with_duplicate op has a slot");
    let other_description = op["other_description"]
        .as_str()
        .expect("eq_with_duplicate op has an other_description");
    let identifier = slots.resolve_identifier(slot);
    let other_parent = resolve_optional_parent(slots, op, "other_parent_slot");

    let outcome = ValueDomain::new(identifier, other_description, other_parent);
    let InternOutcome::AlreadyCanonical {
        canonical,
        discarded,
    } = outcome
    else {
        panic!(
            "case {name} op {index}: golden data only builds eq_with_duplicate for an \
             already-registered slot"
        );
    };
    let expected = op["expected"]["result"]
        .as_bool()
        .expect("eq_with_duplicate expectation has `result`");

    let actual = *canonical == discarded;
    if actual != expected {
        mismatches.push(format!(
            "case {name} op {index}: expected result={expected}, got {actual}"
        ));
    }
}

/// Test `is_subdomain_of` against a fresh duplicate rather than a canonical.
///
/// `is_subdomain_of` is defined in terms of `==`; passing a duplicate (built
/// the same way as `check_eq_with_duplicate_domain`) as `other` forces the
/// walk to compare against a value that shares a registered slot's name but
/// not necessarily its parent, which comparing two canonical handles never
/// exercises.
fn check_is_subdomain_of_with_duplicate(
    slots: &mut SlotTable,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let self_slot = op["self_slot"]
        .as_str()
        .expect("is_subdomain_of_with_duplicate op has self_slot");
    let other_slot = op["other_slot"]
        .as_str()
        .expect("is_subdomain_of_with_duplicate op has other_slot");
    let other_description = op["other_description"]
        .as_str()
        .expect("is_subdomain_of_with_duplicate op has an other_description");

    let self_domain = ValueDomain::intern_registry()
        .require(&slots.resolve_identifier(self_slot))
        .expect(
            "golden data only asks is_subdomain_of_with_duplicate about a registered self_slot",
        );
    let other_identifier = slots.resolve_identifier(other_slot);
    let other_parent = resolve_optional_parent(slots, op, "other_parent_slot");

    let outcome = ValueDomain::new(other_identifier, other_description, other_parent);
    let InternOutcome::AlreadyCanonical { discarded, .. } = outcome else {
        panic!(
            "case {name} op {index}: golden data only builds is_subdomain_of_with_duplicate for \
             an already-registered other_slot"
        );
    };

    let expected = op["expected"]["result"]
        .as_bool()
        .expect("is_subdomain_of_with_duplicate expectation has `result`");
    let actual = self_domain.is_subdomain_of(&discarded);
    if actual != expected {
        mismatches.push(format!(
            "case {name} op {index}: expected result={expected}, got {actual}"
        ));
    }
}

/// Set a slot's current canonical domain aside under the op's label.
fn hold_domain(
    slots: &mut SlotTable,
    held: &mut HashMap<String, Canonical<ValueDomain>>,
    op: &Value,
) {
    let slot = op["slot"].as_str().expect("hold op has a slot");
    let label = op["label"].as_str().expect("hold op has a label");
    let canonical = ValueDomain::intern_registry()
        .require(&slots.resolve_identifier(slot))
        .expect("golden data only holds a registered slot");
    held.insert(label.to_string(), canonical);
}

/// Compare a held domain with a slot's current canonical domain.
///
/// A held domain may predate a clear, so its parent is a different instance
/// from the current canonical's parent even when the two chains carry the
/// same names. Equal domains must also hash equally.
fn check_eq_held_domain(
    slots: &mut SlotTable,
    held: &HashMap<String, Canonical<ValueDomain>>,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let label = op["label"].as_str().expect("eq_held op has a label");
    let slot = op["slot"].as_str().expect("eq_held op has a slot");
    let held_domain = held
        .get(label)
        .unwrap_or_else(|| panic!("case {name} op {index}: nothing is held under {label:?}"));
    let canonical = ValueDomain::intern_registry()
        .require(&slots.resolve_identifier(slot))
        .expect("golden data only compares a held domain with a registered slot");
    let expected = op["expected"]["result"]
        .as_bool()
        .expect("eq_held expectation has `result`");

    let actual = **held_domain == *canonical;
    if actual != expected {
        mismatches.push(format!(
            "case {name} op {index}: expected result={expected}, got {actual}"
        ));
    }
    if actual && compute_hash(&**held_domain) != compute_hash(&*canonical) {
        mismatches.push(format!(
            "case {name} op {index}: equal domains hash differently"
        ));
    }
}

fn replay_value_domain_case(case: &Value, mismatches: &mut Vec<String>) {
    let name = case["name"].as_str().expect("case has a name");
    let ops = case["ops"].as_array().expect("case has an ops array");
    let mut slots = create_value_domain_slots();
    let mut held = HashMap::new();

    for (index, op) in ops.iter().enumerate() {
        match op["op"].as_str().expect("op has a kind") {
            "new" => check_new_domain(&mut slots, name, index, op, mismatches),
            "get" => check_get_domain(&mut slots, name, index, op, mismatches),
            "require" => check_require_domain(&mut slots, name, index, op, mismatches),
            "clear" => ValueDomain::intern_registry().clear(),
            "encode" => check_encode_domain(&mut slots, name, index, op, mismatches),
            "decode" => check_decode_domain(&mut slots, name, index, op, mismatches),
            "is_subdomain_of" => check_is_subdomain_of(&mut slots, name, index, op, mismatches),
            "eq" => check_eq_domain(&mut slots, name, index, op, mismatches),
            "eq_with_duplicate" => {
                check_eq_with_duplicate_domain(&mut slots, name, index, op, mismatches);
            }
            "is_subdomain_of_with_duplicate" => {
                check_is_subdomain_of_with_duplicate(&mut slots, name, index, op, mismatches);
            }
            "hold" => hold_domain(&mut slots, &mut held, op),
            "eq_held" => check_eq_held_domain(&mut slots, &held, name, index, op, mismatches),
            other => panic!("case {name} op {index}: unknown value_domain op kind {other:?}"),
        }
    }
}

// =============================================================================
// Document-level replay
// =============================================================================

fn replay_case(case: &Value, mismatches: &mut Vec<String>) {
    match case["type"].as_str().expect("case has a `type`") {
        "op_attribute" => replay_op_attribute_case(case, mismatches),
        "value_domain" => replay_value_domain_case(case, mismatches),
        other => panic!("case has an unknown type {other:?}"),
    }
}

/// Assert the golden data is large enough that an empty or truncated file
/// cannot pass this test.
fn assert_case_and_op_counts(cases: &[Value]) {
    assert!(
        cases.len() >= 100,
        "expected at least 100 golden cases, found {}",
        cases.len()
    );
    let total_ops: usize = cases
        .iter()
        .map(|case| case["ops"].as_array().map_or(0, Vec::len))
        .sum();
    assert!(
        total_ops >= 1000,
        "expected at least 1000 golden ops, found {total_ops}"
    );
}

/// Assert the golden data's default-slot names match the slots this replay
/// binds, so the two cannot silently drift apart.
fn assert_default_slots_match_rust(document: &Value) {
    let default_slots = document["default_slots"]
        .as_object()
        .expect("golden data has a `default_slots` object");

    let expected_op_attribute_slots: Vec<&str> =
        vec!["commutative", "associative", "pure", "elementwise"];
    let expected_value_domain_slots: Vec<&str> = vec!["data", "address"];

    for (kind, expected) in [
        ("op_attribute", &expected_op_attribute_slots),
        ("value_domain", &expected_value_domain_slots),
    ] {
        let actual: Vec<&str> = default_slots[kind]
            .as_array()
            .unwrap_or_else(|| panic!("default_slots.{kind} is not an array"))
            .iter()
            .map(|value| value.as_str().expect("a default slot name is a string"))
            .collect();
        assert_eq!(
            &actual, expected,
            "Rust's default slots for {kind} have drifted from the golden data"
        );
    }
}

/// Parse a golden document, check its size and default slots, replay every
/// case, and return the mismatches found.
fn replay_golden_document(json: &str) -> Vec<String> {
    let document: Value = serde_json::from_str(json).expect("golden data is valid JSON");
    let cases = document["cases"]
        .as_array()
        .expect("golden data has a `cases` array");

    assert_case_and_op_counts(cases);
    assert_default_slots_match_rust(&document);

    let mut mismatches = Vec::new();
    for case in cases {
        replay_case(case, &mut mismatches);
    }
    mismatches
}

/// Test the Rust `OpAttribute` and `ValueDomain` registries reproduce every
/// observation the Python oracle recorded for the golden operation scripts.
#[test]
fn tag_type_registries_match_the_python_oracle() {
    let mismatches = replay_golden_document(GOLDEN_JSON);

    assert!(
        mismatches.is_empty(),
        "found {} mismatch(es):\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
}

/// Test the Rust registries reproduce every observation the Python oracle
/// recorded for an expanded corpus, read from the file named by
/// `FHY_TAG_TYPE_CORPUS` and written with the generator's corpus options.
#[test]
#[ignore = "requires an expanded corpus generated from the Python oracle"]
fn tag_type_registries_match_the_python_oracle_on_an_expanded_corpus() {
    let path = std::env::var("FHY_TAG_TYPE_CORPUS")
        .expect("FHY_TAG_TYPE_CORPUS names an expanded corpus file");
    let json = std::fs::read_to_string(&path).expect("expanded corpus file is readable");

    let mismatches = replay_golden_document(&json);

    assert!(
        mismatches.is_empty(),
        "found {} mismatch(es) in {path}:\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
}
