from typing import final

from typing_extensions import override

def rust_available() -> bool: ...
def allocate_identifier_id() -> int: ...
def advance_identifier_counter_past(identifier_id: int, /) -> None: ...

@final
class Identifier:
    def __init__(self, name_hint: str) -> None: ...
    @property
    def id(self) -> int: ...
    @property
    def name_hint(self) -> str: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __repr__(self) -> str: ...
    def serialize_to_dict(self) -> dict[str, int | str]: ...
    @classmethod
    def deserialize_from_dict(cls, data: dict[str, int | str]) -> Identifier: ...
