from collections.abc import Iterable
from os import PathLike
from pathlib import Path
from typing import Any

from typing_extensions import Self

from fhy_core.identifier import Identifier
from fhy_core.serialization import SerializedDict
from fhy_core.term import AlphaRenaming

__version__: str

def allocate_identifier_id() -> int: ...
def advance_identifier_counter_past(identifier_id: int, /) -> None: ...

class OpAttribute:
    @property
    def name(self) -> Identifier: ...
    @property
    def description(self) -> str: ...
    @property
    def is_frozen(self) -> bool: ...
    @staticmethod
    def _new_canonical(
        target_class: type[Any], name: Identifier, description: str
    ) -> Any: ...
    def get_identifier(self) -> Identifier: ...
    def get_intern_key(self) -> Identifier: ...
    def is_structurally_equivalent(self, other: object) -> bool: ...
    def is_alpha_equivalent_under(
        self, other: object, renaming: AlphaRenaming
    ) -> bool: ...
    def freeze(self) -> None: ...
    def assert_frozen(self) -> None: ...
    def register_interned_instance(self) -> None: ...
    def serialize_to_dict(self) -> SerializedDict: ...
    @classmethod
    def get_interned(cls, key: Identifier) -> Self | None: ...
    @classmethod
    def require_interned(cls, key: Identifier) -> Self: ...
    @classmethod
    def construct_from_fields(cls, fields: Any) -> Self: ...
    @classmethod
    def deserialize_from_dict(cls, data: SerializedDict) -> Self: ...
    @classmethod
    def clear_interned_registry(cls) -> None: ...
    @classmethod
    def register_default_instances(cls) -> None: ...
    @classmethod
    def _register_public_class(cls) -> None: ...

class NoteKind:
    @property
    def name(self) -> Identifier: ...
    @property
    def description(self) -> str: ...
    @property
    def is_frozen(self) -> bool: ...
    @staticmethod
    def _new_canonical(
        target_class: type[Any], name: Identifier, description: str
    ) -> Any: ...
    def get_identifier(self) -> Identifier: ...
    def get_intern_key(self) -> Identifier: ...
    def is_structurally_equivalent(self, other: object) -> bool: ...
    def is_alpha_equivalent_under(
        self, other: object, renaming: AlphaRenaming
    ) -> bool: ...
    def freeze(self) -> None: ...
    def assert_frozen(self) -> None: ...
    def register_interned_instance(self) -> None: ...
    def serialize_to_dict(self) -> SerializedDict: ...
    @classmethod
    def get_interned(cls, key: Identifier) -> Self | None: ...
    @classmethod
    def require_interned(cls, key: Identifier) -> Self: ...
    @classmethod
    def construct_from_fields(cls, fields: Any) -> Self: ...
    @classmethod
    def deserialize_from_dict(cls, data: SerializedDict) -> Self: ...
    @classmethod
    def clear_interned_registry(cls) -> None: ...
    @classmethod
    def register_default_instances(cls) -> None: ...
    @classmethod
    def _register_public_class(cls) -> None: ...

class ValueDomain:
    @property
    def name(self) -> Identifier: ...
    @property
    def description(self) -> str: ...
    @property
    def parent(self) -> Self | None: ...
    @property
    def is_frozen(self) -> bool: ...
    @staticmethod
    def _new_canonical(
        target_class: type[Any],
        name: Identifier,
        description: str,
        parent: ValueDomain | None = None,
    ) -> Any: ...
    def get_identifier(self) -> Identifier: ...
    def get_intern_key(self) -> Identifier: ...
    def is_subdomain_of(self, other: object) -> bool: ...
    def is_structurally_equivalent(self, other: object) -> bool: ...
    def is_alpha_equivalent_under(
        self, other: object, renaming: AlphaRenaming
    ) -> bool: ...
    def freeze(self) -> None: ...
    def assert_frozen(self) -> None: ...
    def register_interned_instance(self) -> None: ...
    def serialize_to_dict(self) -> SerializedDict: ...
    @classmethod
    def get_interned(cls, key: Identifier) -> Self | None: ...
    @classmethod
    def require_interned(cls, key: Identifier) -> Self: ...
    @classmethod
    def construct_from_fields(cls, fields: Any) -> Self: ...
    @classmethod
    def deserialize_from_dict(cls, data: SerializedDict) -> Self: ...
    @classmethod
    def clear_interned_registry(cls) -> None: ...
    @classmethod
    def register_default_instances(cls) -> None: ...

class Note:
    def __new__(cls, message: str, kind: NoteKind = ...) -> Self: ...
    @property
    def message(self) -> str: ...
    @property
    def kind(self) -> NoteKind: ...
    @property
    def is_frozen(self) -> bool: ...
    def freeze(self) -> None: ...
    def assert_frozen(self) -> None: ...
    def serialize_to_dict(self) -> SerializedDict: ...
    @classmethod
    def deserialize_from_dict(cls, data: SerializedDict) -> Self: ...
    @classmethod
    def _register_public_class(cls) -> None: ...

class Diagnostic:
    def __new__(
        cls, level: str, message: Note, source: str, detail: str | None = None
    ) -> Self: ...
    @property
    def level(self) -> Any: ...
    @property
    def message(self) -> Note: ...
    @property
    def source(self) -> str: ...
    @property
    def detail(self) -> str | None: ...
    @property
    def message_text(self) -> str: ...
    @property
    def is_frozen(self) -> bool: ...
    def freeze(self) -> None: ...
    def assert_frozen(self) -> None: ...
    @classmethod
    def _register_public_class(cls) -> None: ...

class ValidationReport:
    def __new__(
        cls, diagnostics: Iterable[Diagnostic] = ..., records: Iterable[Any] = ...
    ) -> Self: ...
    @property
    def diagnostics(self) -> tuple[Diagnostic, ...]: ...
    @property
    def records(self) -> tuple[Any, ...]: ...
    @property
    def is_frozen(self) -> bool: ...
    def errors(self) -> tuple[Diagnostic, ...]: ...
    def warnings(self) -> tuple[Diagnostic, ...]: ...
    def infos(self) -> tuple[Diagnostic, ...]: ...
    def has_errors(self) -> bool: ...
    def format(self) -> str: ...
    def raise_if_failed(self) -> None: ...
    def freeze(self) -> None: ...
    def assert_frozen(self) -> None: ...
    @classmethod
    def _register_public_class(cls) -> None: ...

class Position:
    def __new__(cls, line: int, column: int) -> Self: ...
    @property
    def line(self) -> int: ...
    @property
    def column(self) -> int: ...
    @property
    def supports_ordering(self) -> bool: ...
    @property
    def supports_partial_ordering(self) -> bool: ...
    @property
    def is_frozen(self) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def freeze(self) -> None: ...
    def assert_frozen(self) -> None: ...
    def serialize_to_dict(self) -> SerializedDict: ...
    @classmethod
    def deserialize_from_dict(cls, data: SerializedDict) -> Self: ...
    @classmethod
    def _register_public_class(cls) -> None: ...

class Span:
    def __new__(
        cls,
        start_offset: int | None = None,
        end_offset: int | None = None,
        start_position: Position | None = None,
        end_position: Position | None = None,
    ) -> Self: ...
    @property
    def start_offset(self) -> int | None: ...
    @property
    def end_offset(self) -> int | None: ...
    @property
    def start_position(self) -> Position | None: ...
    @property
    def end_position(self) -> Position | None: ...
    @property
    def is_frozen(self) -> bool: ...
    def is_unknown(self) -> bool: ...
    def freeze(self) -> None: ...
    def assert_frozen(self) -> None: ...
    def serialize_to_dict(self) -> SerializedDict: ...
    @classmethod
    def deserialize_from_dict(cls, data: SerializedDict) -> Self: ...
    @classmethod
    def _register_public_class(cls) -> None: ...

class Provenance:
    @property
    def is_frozen(self) -> bool: ...
    @staticmethod
    def unknown() -> Provenance: ...
    @staticmethod
    def fuse(*provenances: Provenance, metadata: str | None = None) -> Provenance: ...
    def freeze(self) -> None: ...
    def assert_frozen(self) -> None: ...
    @classmethod
    def _register_public_class(cls) -> None: ...

class UnknownProvenance(Provenance):
    def __new__(cls) -> Self: ...
    def serialize_data_to_dict(self) -> SerializedDict: ...
    @classmethod
    def deserialize_data_from_dict(cls, data: SerializedDict) -> Self: ...

class FileProvenance(Provenance):
    def __new__(
        cls, file_path: str | PathLike[str], span: Span | None = None
    ) -> Self: ...
    @property
    def file_path(self) -> Path: ...
    @property
    def span(self) -> Span | None: ...
    def serialize_data_to_dict(self) -> SerializedDict: ...
    @classmethod
    def deserialize_data_from_dict(cls, data: SerializedDict) -> Self: ...

class NamedProvenance(Provenance):
    def __new__(cls, name: str, child: Provenance) -> Self: ...
    @property
    def name(self) -> str: ...
    @property
    def child(self) -> Provenance: ...
    def serialize_data_to_dict(self) -> SerializedDict: ...
    @classmethod
    def deserialize_data_from_dict(cls, data: SerializedDict) -> Self: ...

class CallSiteProvenance(Provenance):
    def __new__(cls, callee: Provenance, caller: Provenance) -> Self: ...
    @property
    def callee(self) -> Provenance: ...
    @property
    def caller(self) -> Provenance: ...
    def serialize_data_to_dict(self) -> SerializedDict: ...
    @classmethod
    def deserialize_data_from_dict(cls, data: SerializedDict) -> Self: ...

class FusedProvenance(Provenance):
    def __new__(
        cls, sources: Iterable[Provenance], metadata: str | None = None
    ) -> Self: ...
    @property
    def sources(self) -> tuple[Provenance, ...]: ...
    @property
    def metadata(self) -> str | None: ...
    def serialize_data_to_dict(self) -> SerializedDict: ...
    @classmethod
    def deserialize_data_from_dict(cls, data: SerializedDict) -> Self: ...
