from collections.abc import Iterable
from typing import Any

from typing_extensions import Self

from fhy_core.identifier import Identifier
from fhy_core.serialization import SerializedDict
from fhy_core.term import AlphaRenaming

__version__: str

def allocate_identifier_id() -> int: ...
def advance_identifier_counter_past(identifier_id: int, /) -> None: ...

class OpAttribute:
    @property
    def name(self) -> Identifier: ...
    @property
    def description(self) -> str: ...
    @property
    def is_frozen(self) -> bool: ...
    @staticmethod
    def _new_canonical(
        target_class: type[Any], name: Identifier, description: str
    ) -> Any: ...
    def get_identifier(self) -> Identifier: ...
    def get_intern_key(self) -> Identifier: ...
    def is_structurally_equivalent(self, other: object) -> bool: ...
    def is_alpha_equivalent_under(
        self, other: object, renaming: AlphaRenaming
    ) -> bool: ...
    def freeze(self) -> None: ...
    def assert_frozen(self) -> None: ...
    def register_interned_instance(self) -> None: ...
    def serialize_to_dict(self) -> SerializedDict: ...
    @classmethod
    def get_interned(cls, key: Identifier) -> Self | None: ...
    @classmethod
    def require_interned(cls, key: Identifier) -> Self: ...
    @classmethod
    def construct_from_fields(cls, fields: Any) -> Self: ...
    @classmethod
    def deserialize_from_dict(cls, data: SerializedDict) -> Self: ...
    @classmethod
    def clear_interned_registry(cls) -> None: ...
    @classmethod
    def register_default_instances(cls) -> None: ...
    @classmethod
    def _register_public_class(cls) -> None: ...

class NoteKind:
    @property
    def name(self) -> Identifier: ...
    @property
    def description(self) -> str: ...
    @property
    def is_frozen(self) -> bool: ...
    @staticmethod
    def _new_canonical(
        target_class: type[Any], name: Identifier, description: str
    ) -> Any: ...
    def get_identifier(self) -> Identifier: ...
    def get_intern_key(self) -> Identifier: ...
    def is_structurally_equivalent(self, other: object) -> bool: ...
    def is_alpha_equivalent_under(
        self, other: object, renaming: AlphaRenaming
    ) -> bool: ...
    def freeze(self) -> None: ...
    def assert_frozen(self) -> None: ...
    def register_interned_instance(self) -> None: ...
    def serialize_to_dict(self) -> SerializedDict: ...
    @classmethod
    def get_interned(cls, key: Identifier) -> Self | None: ...
    @classmethod
    def require_interned(cls, key: Identifier) -> Self: ...
    @classmethod
    def construct_from_fields(cls, fields: Any) -> Self: ...
    @classmethod
    def deserialize_from_dict(cls, data: SerializedDict) -> Self: ...
    @classmethod
    def clear_interned_registry(cls) -> None: ...
    @classmethod
    def register_default_instances(cls) -> None: ...
    @classmethod
    def _register_public_class(cls) -> None: ...

class ValueDomain:
    @property
    def name(self) -> Identifier: ...
    @property
    def description(self) -> str: ...
    @property
    def parent(self) -> Self | None: ...
    @property
    def is_frozen(self) -> bool: ...
    @staticmethod
    def _new_canonical(
        target_class: type[Any],
        name: Identifier,
        description: str,
        parent: ValueDomain | None = None,
    ) -> Any: ...
    def get_identifier(self) -> Identifier: ...
    def get_intern_key(self) -> Identifier: ...
    def is_subdomain_of(self, other: object) -> bool: ...
    def is_structurally_equivalent(self, other: object) -> bool: ...
    def is_alpha_equivalent_under(
        self, other: object, renaming: AlphaRenaming
    ) -> bool: ...
    def freeze(self) -> None: ...
    def assert_frozen(self) -> None: ...
    def register_interned_instance(self) -> None: ...
    def serialize_to_dict(self) -> SerializedDict: ...
    @classmethod
    def get_interned(cls, key: Identifier) -> Self | None: ...
    @classmethod
    def require_interned(cls, key: Identifier) -> Self: ...
    @classmethod
    def construct_from_fields(cls, fields: Any) -> Self: ...
    @classmethod
    def deserialize_from_dict(cls, data: SerializedDict) -> Self: ...
    @classmethod
    def clear_interned_registry(cls) -> None: ...
    @classmethod
    def register_default_instances(cls) -> None: ...

class Note:
    def __new__(cls, message: str, kind: NoteKind = ...) -> Self: ...
    @property
    def message(self) -> str: ...
    @property
    def kind(self) -> NoteKind: ...
    @property
    def is_frozen(self) -> bool: ...
    def freeze(self) -> None: ...
    def assert_frozen(self) -> None: ...
    def serialize_to_dict(self) -> SerializedDict: ...
    @classmethod
    def deserialize_from_dict(cls, data: SerializedDict) -> Self: ...
    @classmethod
    def _register_public_class(cls) -> None: ...

class Diagnostic:
    def __new__(
        cls, level: str, message: Note, source: str, detail: str | None = None
    ) -> Self: ...
    @property
    def level(self) -> Any: ...
    @property
    def message(self) -> Note: ...
    @property
    def source(self) -> str: ...
    @property
    def detail(self) -> str | None: ...
    @property
    def message_text(self) -> str: ...
    @property
    def is_frozen(self) -> bool: ...
    def freeze(self) -> None: ...
    def assert_frozen(self) -> None: ...
    @classmethod
    def _register_public_class(cls) -> None: ...

class ValidationReport:
    def __new__(
        cls, diagnostics: Iterable[Diagnostic] = ..., records: Iterable[Any] = ...
    ) -> Self: ...
    @property
    def diagnostics(self) -> tuple[Diagnostic, ...]: ...
    @property
    def records(self) -> tuple[Any, ...]: ...
    @property
    def is_frozen(self) -> bool: ...
    def errors(self) -> tuple[Diagnostic, ...]: ...
    def warnings(self) -> tuple[Diagnostic, ...]: ...
    def infos(self) -> tuple[Diagnostic, ...]: ...
    def has_errors(self) -> bool: ...
    def format(self) -> str: ...
    def raise_if_failed(self) -> None: ...
    def freeze(self) -> None: ...
    def assert_frozen(self) -> None: ...
    @classmethod
    def _register_public_class(cls) -> None: ...
