//! Equivalence test replaying golden operation scripts from the Python
//! `InternedMixin` oracle against `fhy_core::interned::InternRegistry`.
//!
//! The golden data is generated by
//! `rust/fhy-core/tests/golden/generate_interned_cases.py` and committed at
//! `rust/fhy-core/tests/golden/interned_cases.json`. This test only uses the public
//! `fhy_core::interned` API. Every script replays against a registry of its
//! own, so the replays share no state with the rest of the binary.

use fhy_core::interned::{InternRegistry, Interned};
use serde_json::Value;

/// Oracle-equivalent fixture type: a name-keyed tag carrying a `note` that
/// identifies the exact instance under test.
struct GoldenTag {
    name: String,
    note: String,
}

impl Interned for GoldenTag {
    type Key = String;

    fn intern_key(&self) -> &String {
        &self.name
    }

    // Required by `Interned`, but every script below builds its own local
    // registry via `InternRegistry::with_defaults`, so this process-wide
    // registry is never actually consulted.
    fn intern_registry() -> &'static InternRegistry<GoldenTag> {
        static REGISTRY: InternRegistry<GoldenTag> = InternRegistry::new();
        &REGISTRY
    }
}

fn build_golden_tag(name: &str, note: &str) -> GoldenTag {
    GoldenTag {
        name: name.to_string(),
        note: note.to_string(),
    }
}

fn create_no_defaults() -> Vec<GoldenTag> {
    Vec::new()
}

fn create_one_default() -> Vec<GoldenTag> {
    vec![build_golden_tag("a", "default-a")]
}

fn create_two_defaults() -> Vec<GoldenTag> {
    vec![
        build_golden_tag("a", "default-a"),
        build_golden_tag("b", "default-b"),
    ]
}

fn create_duplicate_defaults() -> Vec<GoldenTag> {
    vec![
        build_golden_tag("a", "default-a-first"),
        build_golden_tag("a", "default-a-second"),
    ]
}

/// Map a defaults-catalogue id from the golden data to the matching Rust
/// catalogue function.
fn select_catalogue_defaults(id: &str) -> fn() -> Vec<GoldenTag> {
    match id {
        "none" => create_no_defaults,
        "one" => create_one_default,
        "two" => create_two_defaults,
        "duplicate" => create_duplicate_defaults,
        other => panic!("unknown defaults catalogue id in golden data: {other}"),
    }
}

const GOLDEN_JSON: &str = include_str!("../../golden/interned_cases.json");

const MIN_CASES: usize = 120;

const MIN_OPS: usize = 1000;

/// Assert every defaults-catalogue entry in the golden data matches the
/// corresponding Rust catalogue function, so the two cannot silently drift
/// apart.
fn assert_catalogue_matches_rust(document: &Value) {
    let catalogue = document["defaults_catalogue"]
        .as_object()
        .expect("golden data has a `defaults_catalogue` object");

    for (id, expected_defaults) in catalogue {
        let expected: Vec<(String, String)> = expected_defaults
            .as_array()
            .unwrap_or_else(|| panic!("defaults catalogue entry {id} is not an array"))
            .iter()
            .map(|entry| {
                let key = entry["key"].as_str().expect("default entry has a key");
                let note = entry["note"].as_str().expect("default entry has a note");
                (key.to_string(), note.to_string())
            })
            .collect();

        let actual: Vec<(String, String)> = select_catalogue_defaults(id)()
            .into_iter()
            .map(|tag| (tag.name, tag.note))
            .collect();

        assert_eq!(
            actual, expected,
            "Rust defaults catalogue {id:?} has drifted from the golden data"
        );
    }
}

fn check_intern(
    registry: &InternRegistry<GoldenTag>,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let key = op["key"].as_str().expect("intern op has a key");
    let note = op["note"].as_str().expect("intern op has a note");
    let expected_registered = op["expected"]["registered"]
        .as_bool()
        .expect("intern expectation has `registered`");
    let expected_note = op["expected"]["canonical_note"]
        .as_str()
        .expect("intern expectation has `canonical_note`");

    let outcome = registry.intern(build_golden_tag(key, note));
    let actual_registered = outcome.is_registered();
    let actual_note = outcome.canonical().note.clone();

    if actual_registered != expected_registered || actual_note != expected_note {
        mismatches.push(format!(
            "case {name} op {index}: expected registered={expected_registered} \
             canonical_note={expected_note:?}, got registered={actual_registered} \
             canonical_note={actual_note:?}"
        ));
    }
}

fn check_get(
    registry: &InternRegistry<GoldenTag>,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let key = op["key"].as_str().expect("get op has a key");
    let expected_note = op["expected"]
        .get("canonical_note")
        .expect("get expectation has `canonical_note`")
        .as_str();

    let actual_note = registry.get(key).map(|canonical| canonical.note.clone());

    if actual_note.as_deref() != expected_note {
        mismatches.push(format!(
            "case {name} op {index}: expected canonical_note={expected_note:?}, got \
             canonical_note={actual_note:?}"
        ));
    }
}

fn check_require(
    registry: &InternRegistry<GoldenTag>,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    let key = op["key"].as_str().expect("require op has a key");
    let expected = &op["expected"];

    match registry.require(key) {
        Ok(canonical) => {
            let expected_note = expected["canonical_note"].as_str();
            if Some(canonical.note.as_str()) != expected_note {
                mismatches.push(format!(
                    "case {name} op {index}: expected canonical_note={expected_note:?}, got \
                     canonical_note={:?}",
                    canonical.note
                ));
            }
        }
        Err(error) => {
            let expected_error = expected["error"].as_str();
            if expected_error != Some("KeyError") {
                mismatches.push(format!(
                    "case {name} op {index}: expected {expected:?}, got error {error}"
                ));
            } else if error.key() != key {
                mismatches.push(format!(
                    "case {name} op {index}: error key {:?} does not match requested key {key:?}",
                    error.key()
                ));
            }
        }
    }
}

fn replay_op(
    registry: &mut InternRegistry<GoldenTag>,
    name: &str,
    index: usize,
    op: &Value,
    mismatches: &mut Vec<String>,
) {
    match op["op"].as_str().expect("op has a kind") {
        "intern" => check_intern(registry, name, index, op, mismatches),
        "get" => check_get(registry, name, index, op, mismatches),
        "require" => check_require(registry, name, index, op, mismatches),
        "clear" => registry.clear(),
        other => panic!("case {name} op {index}: unknown op kind {other:?}"),
    }
}

fn replay_case(case: &Value, mismatches: &mut Vec<String>) {
    let name = case["name"].as_str().expect("case has a name");
    let defaults_id = case["defaults"].as_str().expect("case has a defaults id");
    let ops = case["ops"].as_array().expect("case has an ops array");

    let mut registry =
        InternRegistry::<GoldenTag>::with_defaults(select_catalogue_defaults(defaults_id));

    for (index, op) in ops.iter().enumerate() {
        replay_op(&mut registry, name, index, op, mismatches);
    }
}

/// Assert `cases` is large enough that an empty or truncated golden file
/// cannot pass the calling test, checking both the case count and the total
/// op count across every case.
fn assert_case_and_op_counts(cases: &[Value], min_cases: usize, min_ops: usize) {
    assert!(
        cases.len() >= min_cases,
        "expected at least {min_cases} golden cases, found {}",
        cases.len()
    );
    let total_ops: usize = cases
        .iter()
        .map(|case| case["ops"].as_array().map_or(0, Vec::len))
        .sum();
    assert!(
        total_ops >= min_ops,
        "expected at least {min_ops} golden ops, found {total_ops}"
    );
}

/// Parse a golden document, check its size against `min_cases` and
/// `min_ops`, run `check_document` against the whole document, replay every
/// case in it with `replay_case`, and fail with the mismatches found.
///
/// `check_document` performs whatever document-level cross-check a test
/// needs beyond the case and op counts (for example, that a defaults
/// catalogue or a set of default slot names matches the Rust side); a test
/// with no such check passes a no-op closure. `corpus_path` names the
/// expanded-corpus file being replayed, included in the failure message; the
/// default (non-expanded) replay passes `None`.
fn replay_golden_document(
    json: &str,
    min_cases: usize,
    min_ops: usize,
    corpus_path: Option<&str>,
    check_document: impl FnOnce(&Value),
    mut replay_case: impl FnMut(&Value, &mut Vec<String>),
) {
    let document: Value = serde_json::from_str(json).expect("golden data is valid JSON");
    let cases = document["cases"]
        .as_array()
        .expect("golden data has a `cases` array");

    assert_case_and_op_counts(cases, min_cases, min_ops);
    check_document(&document);

    let mut mismatches = Vec::new();
    for case in cases {
        replay_case(case, &mut mismatches);
    }

    let location = corpus_path
        .map(|path| format!(" in {path}"))
        .unwrap_or_default();
    assert!(
        mismatches.is_empty(),
        "found {} mismatch(es){location}:\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
}

/// Read the expanded corpus file named by the environment variable
/// `var_name`, returning its path and contents.
///
/// # Panics
///
/// Panics if `var_name` is unset or the file it names cannot be read.
fn read_expanded_corpus(var_name: &str) -> (String, String) {
    let path = std::env::var(var_name)
        .unwrap_or_else(|_| panic!("{var_name} names an expanded corpus file"));
    let json = std::fs::read_to_string(&path).expect("expanded corpus file is readable");
    (path, json)
}

/// Test the Rust `InternRegistry` reproduces every observation the Python
/// `InternedMixin` oracle recorded for the golden operation scripts.
#[test]
fn interned_registry_matches_the_python_oracle() {
    replay_golden_document(
        GOLDEN_JSON,
        MIN_CASES,
        MIN_OPS,
        None,
        assert_catalogue_matches_rust,
        replay_case,
    );
}

/// Test the Rust `InternRegistry` reproduces every observation the Python
/// oracle recorded for an expanded corpus, read from the file named by
/// `FHY_INTERNED_CORPUS` and written with the generator's corpus options.
#[test]
#[ignore = "requires an expanded corpus generated from the Python oracle"]
fn interned_registry_matches_the_python_oracle_on_an_expanded_corpus() {
    let (path, json) = read_expanded_corpus("FHY_INTERNED_CORPUS");

    replay_golden_document(
        &json,
        MIN_CASES,
        MIN_OPS,
        Some(&path),
        assert_catalogue_matches_rust,
        replay_case,
    );
}
