"""`Frozen` trait and mixin."""

__all__ = [
    "Frozen",
    "FrozenMixin",
    "FrozenMutationError",
    "FrozenValidationError",
]

import functools
from abc import ABC
from dataclasses import FrozenInstanceError, is_dataclass
from types import MappingProxyType
from typing import TYPE_CHECKING, Any, ClassVar, Protocol, TypeVar, runtime_checkable

from frozendict import frozendict

from fhy_core.error import register_error

_FROZEN_FLAG = "_fhy_core_is_frozen"
_FROZEN_DISPATCH_FLAG = "_fhy_core_frozen_dispatch_installed"
_FREEZE_ON_INIT_WRAP_INSTALLED_FLAG = "_fhy_core_freeze_on_init_wrap_installed"
_FREEZE_ON_INIT_WRAPPER_FLAG = "_fhy_core_freeze_on_init_wrapper"
_IMMUTABLE_ATOMS = (str, bytes, int, float, complex, bool, type(None))

_FrozenMixinT = TypeVar("_FrozenMixinT", bound="FrozenMixin")


@register_error
class FrozenMutationError(AttributeError):
    """Raised when mutating a frozen object.

    Inherits from :class:`AttributeError` so callers that follow Python's
    standard ``__setattr__``/``__delattr__`` convention keep working,
    including code that catches :class:`AttributeError` (the base class
    of :class:`dataclasses.FrozenInstanceError`) without explicit
    knowledge of FhY's error type. Note that catching
    :class:`dataclasses.FrozenInstanceError` itself will *not* catch this
    error, as the two are sibling subclasses of :class:`AttributeError`.

    """


@register_error
class FrozenValidationError(RuntimeError):
    """Raised when runtime frozen verification fails."""


@runtime_checkable
class Frozen(Protocol):
    """Protocol for objects that support runtime freezing."""

    @property
    def is_frozen(self) -> bool: ...

    def freeze(self, *, deep: bool = False) -> None: ...

    def assert_frozen(self, *, deep: bool = False, strict: bool = False) -> None: ...

    def assert_write_protected(self) -> None: ...


class FrozenMixin(ABC):
    """Mixin that enforces runtime immutability after `freeze()`.

    Raises `FrozenMutationError` on any attribute assignment or deletion
    once frozen, including for subclasses also decorated with
    ``@dataclass(frozen=True)``.

    Auto-freeze on init:
        Subclasses may opt into automatic freezing at the end of
        ``__init__`` by passing ``freeze_on_init=True`` (and optionally
        ``freeze_on_init_deep=True``) as class-creation kwargs:

        ```python
        class MyClass(FrozenMixin, freeze_on_init=True, freeze_on_init_deep=True):
            def __init__(self, value):
                self.value = value
        ```

        The policy is sticky: once set on a base class, descendants
        inherit it unless they explicitly override the kwarg. Each
        subclass's ``__init__`` is wrapped so that the most-derived
        class's wrap calls ``self.freeze(deep=...)`` after construction.
        Inner wraps in a multi-level inheritance chain skip the freeze
        (so subclass state can be set after a parent's ``super().__init__``
        returns).

        The wrap is idempotent: a subclass ``__init__`` that already
        calls ``self.freeze(...)`` explicitly is unaffected because the
        wrap checks ``is_frozen`` before re-freezing.

    """

    _FREEZE_ON_INIT: ClassVar[bool] = False
    _FREEZE_ON_INIT_DEEP: ClassVar[bool] = False

    def __init_subclass__(
        cls,
        *,
        freeze_on_init: bool | None = None,
        freeze_on_init_deep: bool | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init_subclass__(**kwargs)

        if freeze_on_init is not None:
            cls._FREEZE_ON_INIT = freeze_on_init
        if freeze_on_init_deep is not None:
            cls._FREEZE_ON_INIT_DEEP = freeze_on_init_deep

    if not TYPE_CHECKING:
        # Defined only at runtime so it does not advertise a permissive
        # ``*args, **kwargs`` signature to type checkers, which would
        # silently disable constructor-call argument checking for every
        # ``FrozenMixin`` subclass. Subclass ``__init__`` signatures
        # (e.g. those generated by ``@dataclass``) drive type checking
        # of constructor calls.
        def __new__(
            cls: type[_FrozenMixinT], *args: Any, **kwargs: Any
        ) -> _FrozenMixinT:
            del args, kwargs
            if not cls.__dict__.get(_FROZEN_DISPATCH_FLAG, False):
                FrozenMixin._install_frozen_dispatch(cls)
            if cls._FREEZE_ON_INIT and not cls.__dict__.get(
                _FREEZE_ON_INIT_WRAP_INSTALLED_FLAG, False
            ):
                FrozenMixin._install_freeze_on_init_wrap(cls)
            return super().__new__(cls)

    @property
    def is_frozen(self) -> bool:
        return self._is_native_frozen_dataclass() or self._is_marked_frozen()

    def freeze(self, *, deep: bool = False) -> None:
        """Freeze this object and optionally deep-freeze its instance state.

        Args:
            deep: Whether to recursively freeze nested objects in the instance state.

        """
        if self._is_native_frozen_dataclass():
            if not deep:
                return
            seen: set[int] = {id(self)}
            for attribute_name, attribute_value in self._iter_instance_state_items():
                if attribute_name == _FROZEN_FLAG:
                    continue
                frozen_value = self._freeze_value(attribute_value, seen)
                object.__setattr__(self, attribute_name, frozen_value)
            return

        if self._is_marked_frozen():
            return
        object.__setattr__(self, _FROZEN_FLAG, True)
        if deep:
            seen_local: set[int] = {id(self)}
            for attribute_name, attribute_value in self._iter_instance_state_items():
                if attribute_name == _FROZEN_FLAG:
                    continue
                frozen_value = self._freeze_value(attribute_value, seen_local)
                object.__setattr__(self, attribute_name, frozen_value)

    def assert_frozen(self, *, deep: bool = False, strict: bool = False) -> None:
        """Assert that this object is frozen.

        Args:
            deep: Whether to verify deep immutability for the instance state.
            strict: Whether unknown nested object types are treated as mutable.

        Raises:
            FrozenValidationError: If frozen constraints are violated.

        """
        if not self.is_frozen:
            raise FrozenValidationError(f"{type(self).__name__} is not frozen.")
        self.assert_write_protected()
        if deep and not self._is_deeply_immutable(self, set(), strict=strict):
            raise FrozenValidationError(
                f'"{type(self).__name__}" failed deep immutability validation.'
            )

    def assert_write_protected(self) -> None:
        """Assert that normal `setattr` attempts are blocked for this object."""
        if not self.is_frozen:
            raise FrozenValidationError(
                f"{type(self).__name__} is not frozen, so write protection is inactive."
            )
        candidate_name: str | None = None
        for attribute_name, _ in self._iter_instance_state_items():
            if attribute_name == _FROZEN_FLAG:
                continue
            candidate_name = attribute_name
            break
        if candidate_name is None:
            return
        try:
            setattr(self, candidate_name, getattr(self, candidate_name))
        except FrozenMutationError:
            return
        except FrozenInstanceError:
            return
        except Exception as exc:
            raise FrozenValidationError(
                f'"{type(self).__name__}" write-protection probe failed '
                f"unexpectedly: {exc}"
            ) from exc
        raise FrozenValidationError(
            f'"{type(self).__name__}" accepted mutation while frozen.'
        )

    def __setattr__(self, name: str, value: Any) -> None:
        if name in {_FROZEN_FLAG, "__orig_class__"}:
            object.__setattr__(self, name, value)
            return
        if self.is_frozen:
            raise FrozenMutationError(
                f'Cannot modify "{name}" on frozen {type(self).__name__}.'
            )
        object.__setattr__(self, name, value)

    def __delattr__(self, name: str) -> None:
        if name != _FROZEN_FLAG and self.is_frozen:
            raise FrozenMutationError(
                f'Cannot delete "{name}" on frozen {type(self).__name__}.'
            )
        object.__delattr__(self, name)

    @staticmethod
    def _install_freeze_on_init_wrap(subclass: type) -> None:
        cls = subclass
        original_init = cls.__init__  # type: ignore[misc]

        @functools.wraps(original_init)
        def wrapped(self: "FrozenMixin", *args: Any, **kwargs: Any) -> None:
            original_init(self, *args, **kwargs)
            if type(self) is cls:
                self.freeze(deep=cls._FREEZE_ON_INIT_DEEP)

        setattr(wrapped, _FREEZE_ON_INIT_WRAPPER_FLAG, True)
        cls.__init__ = wrapped  # type: ignore[misc]
        setattr(cls, _FREEZE_ON_INIT_WRAP_INSTALLED_FLAG, True)

    @staticmethod
    def _install_frozen_dispatch(subclass: type) -> None:
        params = getattr(subclass, "__dataclass_params__", None)
        if params is not None and getattr(params, "frozen", False):
            if "__setattr__" in subclass.__dict__:
                type.__setattr__(subclass, "__setattr__", FrozenMixin.__setattr__)
            if "__delattr__" in subclass.__dict__:
                type.__setattr__(subclass, "__delattr__", FrozenMixin.__delattr__)
        type.__setattr__(subclass, _FROZEN_DISPATCH_FLAG, True)

    @staticmethod
    def _freeze_value(value: Any, seen: set[int]) -> Any:
        value_id = id(value)
        if value_id in seen:
            return value
        seen.add(value_id)

        if isinstance(value, list):
            return tuple(FrozenMixin._freeze_value(item, seen) for item in value)
        elif isinstance(value, tuple):
            return tuple(FrozenMixin._freeze_value(item, seen) for item in value)
        elif isinstance(value, set):
            return frozenset(FrozenMixin._freeze_value(item, seen) for item in value)
        elif isinstance(value, frozenset):
            return frozenset(FrozenMixin._freeze_value(item, seen) for item in value)
        elif isinstance(value, dict):
            frozen_dict = {
                FrozenMixin._freeze_value(key, seen): FrozenMixin._freeze_value(
                    item_value, seen
                )
                for key, item_value in value.items()
            }
            return frozendict(frozen_dict)
        elif isinstance(value, MappingProxyType):
            frozen_dict = {
                FrozenMixin._freeze_value(key, seen): FrozenMixin._freeze_value(
                    item_value, seen
                )
                for key, item_value in value.items()
            }
            return frozendict(frozen_dict)
        elif isinstance(value, bytearray):
            return bytes(value)
        elif isinstance(value, FrozenMixin):
            if value.is_frozen:
                return value
            value.freeze(deep=True)
            return value
        else:
            return value

    @staticmethod
    def _is_deeply_immutable(value: Any, seen: set[int], *, strict: bool) -> bool:
        value_id = id(value)
        if value_id in seen:
            return True
        seen.add(value_id)

        if isinstance(value, _IMMUTABLE_ATOMS):
            return True
        elif isinstance(value, tuple):
            return all(
                FrozenMixin._is_deeply_immutable(item, seen, strict=strict)
                for item in value
            )
        elif isinstance(value, frozenset):
            return all(
                FrozenMixin._is_deeply_immutable(item, seen, strict=strict)
                for item in value
            )
        elif isinstance(value, (frozendict, MappingProxyType)):
            return all(
                FrozenMixin._is_deeply_immutable(key, seen, strict=strict)
                and FrozenMixin._is_deeply_immutable(item_value, seen, strict=strict)
                for key, item_value in value.items()
            )
        elif isinstance(value, FrozenMixin):
            if not value.is_frozen:
                return False
            return all(
                FrozenMixin._is_deeply_immutable(item_value, seen, strict=strict)
                for _, item_value in value._iter_instance_state_items()
                if _ != _FROZEN_FLAG
            )
        elif isinstance(value, (list, set, dict, bytearray)):
            return False
        elif strict and FrozenMixin._has_instance_state(value):
            return False
        else:
            return True

    def _iter_instance_state_items(self) -> list[tuple[str, Any]]:
        state: dict[str, Any] = {}
        instance_dict = getattr(self, "__dict__", None)
        if isinstance(instance_dict, dict):
            state.update(instance_dict)

        for klass in type(self).mro():
            slots = getattr(klass, "__slots__", ())
            if isinstance(slots, str):
                slot_names = (slots,)
            else:
                slot_names = tuple(slots)
            for slot_name in slot_names:
                if slot_name in {"__dict__", "__weakref__"}:
                    continue
                if slot_name in state:
                    continue
                try:
                    state[slot_name] = object.__getattribute__(self, slot_name)
                except AttributeError:
                    continue

        return list(state.items())

    def _is_marked_frozen(self) -> bool:
        try:
            return bool(object.__getattribute__(self, _FROZEN_FLAG))
        except AttributeError:
            return False

    def _is_native_frozen_dataclass(self) -> bool:
        params = getattr(type(self), "__dataclass_params__", None)
        return bool(is_dataclass(self) and params is not None and params.frozen)

    @staticmethod
    def _has_instance_state(value: Any) -> bool:
        if hasattr(value, "__dict__"):
            return True
        for klass in type(value).mro():
            slots = getattr(klass, "__slots__", ())
            if isinstance(slots, str):
                if slots not in {"__dict__", "__weakref__"}:
                    return True
            else:
                for slot_name in slots:
                    if slot_name not in {"__dict__", "__weakref__"}:
                        return True
        return False
