//! Replay of the serialization corpus: the V2 text the Python package
//! writes for each case reads into its Rust type and writes back
//! byte-identically.
//!
//! The corpus is generated by
//! `rust/fhy-core/tests/golden/generate_serialization_cases.py` and committed
//! at `rust/fhy-core/tests/golden/serialization_cases.json`. Each case names
//! the Rust type of its value and lists the type ids of the foreign parts it
//! holds. A case without foreign parts reads through the type's own
//! `Deserialize`; every case also reads through its wire form, which keeps
//! foreign parts as they are, and a case with foreign parts is refused by
//! the plain `Deserialize`, naming its first part's type id.

use std::fmt::Debug;

use fhy_core::constraint::wire::{ConstraintData, ConstraintSystemData, ValueData};
use fhy_core::constraint::{Constraint, ConstraintSystem, Value};
use fhy_core::diagnostic::{Note, NoteKind};
use fhy_core::expression::Expression;
use fhy_core::identifier::Identifier;
use fhy_core::interned::Canonical;
use fhy_core::op_attribute::OpAttribute;
use fhy_core::param::wire::{ParamAssignmentData, ParamData, ParamDomainData};
use fhy_core::param::{Param, ParamAssignment, ParamDomain};
use fhy_core::provenance::{Position, Provenance, Span};
use fhy_core::symbol_table::wire::{SymbolFrameData, SymbolTableData};
use fhy_core::symbol_table::{SymbolFrame, SymbolTable};
use fhy_core::types::wire::{DataTypeData, TypeData};
use fhy_core::types::{DataType, Type};
use fhy_core::value_domain::ValueDomain;
use serde::Serialize;
use serde::de::DeserializeOwned;
use serde_json::Value as Json;

const GOLDEN_JSON: &str = include_str!("../golden/serialization_cases.json");

/// The fewest cases the committed corpus holds.
const MIN_CASES: usize = 20;

/// Assert `text` reads as a `T` and writes back as itself.
fn assert_rewrites<T: DeserializeOwned + Serialize>(name: &str, text: &str) {
    let value: T = serde_json::from_str(text)
        .unwrap_or_else(|error| panic!("case {name} does not read: {error}\n{text}"));
    let written = serde_json::to_string(&value)
        .unwrap_or_else(|error| panic!("case {name} does not write: {error}"));
    assert_eq!(written, text, "case {name} writes back differently");
}

/// Assert `text` does not read as a `T`, naming `type_id`.
fn assert_refuses<T: DeserializeOwned + Debug>(name: &str, text: &str, type_id: &str) {
    let error = serde_json::from_str::<T>(text).expect_err("a foreign part is refused");
    assert!(
        error.to_string().contains(&format!("`{type_id}`")),
        "case {name} is refused for another reason: {error}"
    );
}

/// Replay one case through the value type `T` and its wire form `D`.
fn replay<T: DeserializeOwned + Serialize + Debug, D: DeserializeOwned + Serialize>(
    name: &str,
    text: &str,
    foreign: &[String],
) {
    assert_rewrites::<D>(name, text);
    match foreign.first() {
        None => assert_rewrites::<T>(name, text),
        Some(type_id) => assert_refuses::<T>(name, text, type_id),
    }
}

/// Replay one case by the name of its Rust type.
fn replay_case(name: &str, rust_type: &str, text: &str, foreign: &[String]) {
    match rust_type {
        "Identifier" => replay::<Identifier, Identifier>(name, text, foreign),
        "Position" => replay::<Position, Position>(name, text, foreign),
        "Span" => replay::<Span, Span>(name, text, foreign),
        "Note" => replay::<Note, Note>(name, text, foreign),
        "NoteKind" => replay::<Canonical<NoteKind>, Canonical<NoteKind>>(name, text, foreign),
        "OpAttribute" => {
            replay::<Canonical<OpAttribute>, Canonical<OpAttribute>>(name, text, foreign);
        }
        "ValueDomain" => {
            replay::<Canonical<ValueDomain>, Canonical<ValueDomain>>(name, text, foreign);
        }
        "Provenance" => replay::<Provenance, Provenance>(name, text, foreign),
        "Expression" => replay::<Expression, Expression>(name, text, foreign),
        "Type" => replay::<Type, TypeData>(name, text, foreign),
        "DataType" => replay::<DataType, DataTypeData>(name, text, foreign),
        "SymbolFrame" => replay::<SymbolFrame, SymbolFrameData>(name, text, foreign),
        "SymbolTable" => {
            replay::<SymbolTable<SymbolFrame>, SymbolTableData<SymbolFrameData>>(
                name, text, foreign,
            );
        }
        "Value" => replay::<Value, ValueData>(name, text, foreign),
        "Constraint" => replay::<Constraint, ConstraintData>(name, text, foreign),
        "ConstraintSystem" => {
            replay::<ConstraintSystem, ConstraintSystemData>(name, text, foreign);
        }
        "ParamDomain" => replay::<ParamDomain, ParamDomainData>(name, text, foreign),
        "Param" => replay::<Param, ParamData>(name, text, foreign),
        "ParamAssignment" => replay::<ParamAssignment, ParamAssignmentData>(name, text, foreign),
        other => panic!("case {name} names an unknown Rust type {other}"),
    }
}

/// Replay every case of a corpus document, returning how many there were.
fn replay_document(document: &Json) -> usize {
    let cases = document["cases"]
        .as_array()
        .expect("the corpus lists cases");
    for case in cases {
        let name = case["name"].as_str().expect("a case has a name");
        let rust_type = case["rust_type"].as_str().expect("a case has a Rust type");
        let text = case["v2"].as_str().expect("a case has its V2 text");
        let foreign: Vec<String> = case["foreign"]
            .as_array()
            .expect("a case lists its foreign parts")
            .iter()
            .map(|type_id| type_id.as_str().expect("a type id").to_owned())
            .collect();
        replay_case(name, rust_type, text, &foreign);
    }
    cases.len()
}

#[test]
fn every_committed_case_rewrites_byte_identically() {
    let document: Json = serde_json::from_str(GOLDEN_JSON).expect("the corpus is JSON");

    let count = replay_document(&document);

    assert!(count >= MIN_CASES, "the corpus holds only {count} cases");
}

/// Replay the expanded corpus the generator writes with its random-case
/// options, named by `FHY_SERIALIZATION_CORPUS`.
#[test]
#[ignore = "requires an expanded corpus generated from the Python package"]
fn every_expanded_case_rewrites_byte_identically() {
    let path = std::env::var("FHY_SERIALIZATION_CORPUS")
        .expect("FHY_SERIALIZATION_CORPUS names an expanded corpus file");
    let text = std::fs::read_to_string(&path).expect("the expanded corpus is readable");
    let document: Json = serde_json::from_str(&text).expect("the corpus is JSON");

    replay_document(&document);
}
