"""General expression tree utility."""

__all__ = [
    "BUILTIN_CONSTANTS",
    "BUILTIN_FUNCTIONS",
    "BinaryExpression",
    "BinaryOperation",
    "BuiltinConstants",
    "BuiltinFunctions",
    "CallExpression",
    "EntryLookupError",
    "EntryRegistrationError",
    "Expression",
    "FunctionArityError",
    "FunctionSort",
    "IdentifierExpression",
    "LiteralExpression",
    "LiteralType",
    "NativeConstant",
    "NativeFunction",
    "NativeResultSortError",
    "ParseError",
    "UndecidableError",
    "RegisteredEntry",
    "RegisteredFunction",
    "TernaryExpression",
    "UnaryExpression",
    "UnaryOperation",
    "assert_expression_implies",
    "assert_holds_for_all_free_assignments",
    "call",
    "check_expression_type",
    "collect_identifiers",
    "convert_expression_to_sympy_expression",
    "convert_expression_to_z3_expression",
    "convert_sympy_expression_to_expression",
    "evaluate_expression",
    "get_core_data_type_from_literal_type",
    "get_registered_entry",
    "get_registered_entries",
    "get_result_core_data_type_for_sort",
    "does_expression_imply",
    "holds_for_all_free_assignments",
    "inline_functions",
    "is_core_data_type_compatible_with_sort",
    "is_entry_registered",
    "is_python_value_compatible_with_sort",
    "logical_and",
    "logical_or",
    "make_binary_expression",
    "make_unary_expression",
    "parse_expression",
    "pformat_expression",
    "register_function",
    "register_native_constant",
    "register_native_function",
    "replace_identifiers",
    "ternary",
    "simplify_expression",
    "substitute_identifiers",
    "substitute_sympy_expression_variables",
    "synthesize_expression_type",
    "tokenize_expression",
]

from .builtins import (
    BUILTIN_CONSTANTS,
    BUILTIN_FUNCTIONS,
    BuiltinConstants,
    BuiltinFunctions,
)
from .core import (
    BinaryExpression,
    BinaryOperation,
    CallExpression,
    Expression,
    IdentifierExpression,
    LiteralExpression,
    LiteralType,
    TernaryExpression,
    UnaryExpression,
    UnaryOperation,
    call,
    logical_and,
    logical_or,
    make_binary_expression,
    make_unary_expression,
    ternary,
)
from .errors import NativeResultSortError, UndecidableError
from .parser import ParseError, parse_expression, tokenize_expression
from .passes.basic import (
    collect_identifiers,
    replace_identifiers,
    substitute_identifiers,
)
from .passes.evaluate import evaluate_expression
from .passes.inline import FunctionArityError, inline_functions
from .passes.sympy import (
    convert_expression_to_sympy_expression,
    convert_sympy_expression_to_expression,
    simplify_expression,
    substitute_sympy_expression_variables,
)
from .passes.type_checker import (
    check_expression_type,
    get_core_data_type_from_literal_type,
    synthesize_expression_type,
)
from .passes.z3 import (
    assert_expression_implies,
    assert_holds_for_all_free_assignments,
    convert_expression_to_z3_expression,
    does_expression_imply,
    holds_for_all_free_assignments,
)
from .pprint import pformat_expression
from .registry import (
    EntryLookupError,
    EntryRegistrationError,
    NativeConstant,
    NativeFunction,
    RegisteredEntry,
    RegisteredFunction,
    get_registered_entries,
    get_registered_entry,
    is_entry_registered,
    register_function,
    register_native_constant,
    register_native_function,
)
from .sort import (
    FunctionSort,
    get_result_core_data_type_for_sort,
    is_core_data_type_compatible_with_sort,
    is_python_value_compatible_with_sort,
)
